"use client";

import {useEffect,useMemo,useState} from "react";
import {clearPddSession,currentPddSession,type PddSession} from "../../../lib/pdd-auth";
import {readBidSpreadsheet} from "../../../lib/bidSpreadsheet";

type Customer={id:string;company:string;contact_name:string;email:string;phone:string;address1:string;address2:string;city:string;region:string;postal_code:string;country:string;has_account:boolean};
type PublicLine={line:number;quantity:number;values:Record<string,string>};
type DealSummary={deal_number:string;title:string;quantity:number;closes_at:string};
type Deal={deal_number:string;title:string;description:string;quantity:number;closes_at:string;public_lines:PublicLine[];spreadsheet_filename:string};
type BidEntry={unitBid:string;comments:string};
type ContactDraft={company:string;contactName:string;email:string;phone:string;address1:string;address2:string;city:string;region:string;postalCode:string;country:string};
const emptyContact:ContactDraft={company:"",contactName:"",email:"",phone:"",address1:"",address2:"",city:"",region:"",postalCode:"",country:"United States"};
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"});

export default function CustomerBidUpload(){
 const [session,setSession]=useState<PddSession|null>(null),[customers,setCustomers]=useState<Customer[]>([]),[deals,setDeals]=useState<DealSummary[]>([]),[customerId,setCustomerId]=useState(""),[contact,setContact]=useState<ContactDraft>(emptyContact),[dealNumber,setDealNumber]=useState(""),[deal,setDeal]=useState<Deal|null>(null),[entries,setEntries]=useState<Record<number,BidEntry>>({}),[fileName,setFileName]=useState(""),[notes,setNotes]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[confirmation,setConfirmation]=useState("");
 useEffect(()=>{void(async()=>{const active=await currentPddSession();if(!active){window.location.replace("/employee-login?return_to=/employee/customer-bid");return}setSession(active);const headers={Authorization:`Bearer ${active.access_token}`};const [customerResponse,dealResponse]=await Promise.all([fetch("/api/admin/contacts",{headers}),fetch("/api/deals")]);if(customerResponse.status===401){clearPddSession();window.location.replace("/employee-login");return}if(!customerResponse.ok||!dealResponse.ok){setError("Customers or open deals could not be loaded.");setLoading(false);return}const customerData=await customerResponse.json() as {customers:Customer[]};const dealData=await dealResponse.json() as {deals:DealSummary[]};setCustomers(customerData.customers||[]);setDeals(dealData.deals||[]);setLoading(false)})()},[]);
 useEffect(()=>{setEntries({});setFileName("");setConfirmation("");setMessage("");if(!dealNumber){setDeal(null);return}setBusy(true);fetch(`/api/deals/${encodeURIComponent(dealNumber)}`).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||"The deal could not be opened.");setDeal(data.deal)}).catch(reason=>setError(reason instanceof Error?reason.message:"The deal could not be opened.")).finally(()=>setBusy(false))},[dealNumber]);
 const customer=customers.find(item=>item.id===customerId)||null;
 useEffect(()=>{if(!customer){setContact(emptyContact);return}setContact({company:customer.company,contactName:customer.contact_name,email:customer.email,phone:customer.phone,address1:customer.address1,address2:customer.address2,city:customer.city,region:customer.region,postalCode:customer.postal_code,country:customer.country||"United States"})},[customer]);
 const selected=useMemo(()=>deal?.public_lines.map((line,index)=>({line,index,entry:entries[index]})).filter(item=>Number(item.entry?.unitBid)>0)||[],[deal,entries]);
 const total=selected.reduce((sum,item)=>sum+item.line.quantity*Number(item.entry.unitBid),0),totalQty=selected.reduce((sum,item)=>sum+item.line.quantity,0);
 const missingContact=[contact.company,contact.contactName,contact.email,contact.phone,contact.address1,contact.city,contact.region,contact.postalCode,contact.country].filter(value=>!value.trim()).length;
 const validEmail=/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(contact.email);
 const contactComplete=missingContact===0&&validEmail;
 const updateContact=(field:keyof ContactDraft,value:string)=>setContact(current=>({...current,[field]:value}));
 async function importSheet(file:File){if(!deal)return;setError("");setMessage("");setConfirmation("");try{const imported=await readBidSpreadsheet(file);const next:Record<number,BidEntry>={};let priced=0;for(const item of imported){const numeric=/^\d+$/.test(item.lineId),legacy=item.lineId.startsWith(`${deal.deal_number}-`),index=(numeric?Number(item.lineId):legacy?Number(item.lineId.slice(deal.deal_number.length+1)):0)-1;if((!numeric&&!legacy)||!Number.isInteger(index)||index<0||index>=deal.public_lines.length){if(Number(item.unitBid)>0)throw new Error(`Line ${item.lineId||"(blank)"} does not belong to ${deal.deal_number}.`);continue}if(Number(item.unitBid)>0){next[index]={unitBid:item.unitBid,comments:item.comments};priced++}}if(!priced)throw new Error("No positive Unit Bid amounts were found in the spreadsheet.");setEntries(next);setFileName(file.name);setMessage(`${priced} priced lines matched ${deal.deal_number}. Review the customer and total, then submit.`)}catch(reason){setEntries({});setFileName("");setError(reason instanceof Error?reason.message:"The spreadsheet could not be imported.")}}
 async function submit(){if(!session||!deal||!customer||!selected.length)return;if(!contactComplete){setError(validEmail?"Complete all required customer contact and address fields.":"Enter a valid customer email address.");return}setBusy(true);setError("");setConfirmation("");const lineItems=selected.map(({line,entry})=>({lineNumber:line.line,assetId:"",brand:line.values.MFG||line.values.Manufacturer||"",model:line.values.Model||"",modelNumber:line.values["Model Number"]||line.values["Part Number"]||line.values["Part #"]||"",processor:line.values.CPU||line.values.Processor||"",ram:line.values.RAM||"",hardDrive:line.values.Storage||line.values["Hard Drive"]||"",condition:line.values.Condition||line.values["Grading Description"]||"",issues:Object.entries(line.values).map(([key,value])=>`${key}: ${value}`).join(" · "),quantity:line.quantity,unitBid:Number(entry.unitBid),comments:entry.comments}));try{const response=await fetch("/api/line-item-bids",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({dealNumber:deal.deal_number,company:contact.company,contactName:contact.contactName,email:contact.email,phone:contact.phone,address1:contact.address1,address2:contact.address2,city:contact.city,region:contact.region,postalCode:contact.postalCode,country:contact.country,customerNotes:notes,lineItems,submittedOnBehalf:true,customerUserId:customer.has_account?customer.id:null,customerKey:customer.id,uploadedFileName:fileName})});const data=await response.json();if(!response.ok)throw new Error(data.error||"The customer bid could not be submitted.");setConfirmation(data.internalBidNumber);setMessage(`Bid submitted for ${contact.company}. ${data.lineCount} lines · ${money.format(data.totalBid)}.`)}catch(reason){setError(reason instanceof Error?reason.message:"The customer bid could not be submitted.")}finally{setBusy(false)}}
 if(loading)return <main className="employeeCustomerBid"><p>Loading customers and open deals…</p></main>;
 return <main className="employeeCustomerBid"><header><div><p className="eyebrow">EMPLOYEE TOOL</p><h1>Submit a Customer Bid</h1><p>Upload a completed bid spreadsheet received by email and record it under the correct customer.</p></div><a href="/employee">← Deal Workbook</a></header>
 <section className="customerBidSteps"><article className={dealNumber?"complete":""}><span>1</span><h2>Select the open deal</h2><label>Deal<select value={dealNumber} onChange={event=>{setDealNumber(event.target.value);setError("")}}><option value="">Choose a deal…</option>{deals.map(item=><option key={item.deal_number} value={item.deal_number}>{item.deal_number} · {item.title}</option>)}</select></label></article>
 <article className={customer?"complete":""}><span>2</span><h2>Select the customer</h2><label>Customer<select value={customerId} onChange={event=>{setCustomerId(event.target.value);setConfirmation("")}}><option value="">Choose a saved customer…</option>{customers.map(item=><option key={item.id} value={item.id}>{item.company||item.email} · {item.contact_name||item.email}</option>)}</select></label>{customer&&<div className="selectedCustomer"><strong>{customer.company}</strong><small>{customer.contact_name} · {customer.email}</small><small>{customer.phone} · {[customer.city,customer.region].filter(Boolean).join(", ")}</small></div>}</article>
 <article className={selected.length?"complete":""}><span>3</span><h2>Upload completed spreadsheet</h2><label className={`customerBidUpload ${!deal||!customer?"disabled":""}`}><input type="file" disabled={!deal||!customer||busy} accept=".xls,.xlsx,.xml,.csv" onChange={event=>{const file=event.target.files?.[0];if(file)void importSheet(file);event.currentTarget.value=""}}/><b>{fileName||"Choose completed bid file"}</b><small>{deal&&customer?"Excel or CSV · up to 10 MB":"Select both the deal and customer first"}</small></label></article></section>
 {customer&&<section className="customerBidContact"><div className="customerBidContactHeading"><div><span>CUSTOMER DETAILS</span><h2>Confirm contact and address</h2><p>Complete any missing information before submitting the bid.</p></div><b className={contactComplete?"complete":"incomplete"}>{contactComplete?"Ready":`${missingContact+(validEmail?0:1)} required ${missingContact+(validEmail?0:1)===1?"field":"fields"} missing`}</b></div><div className="customerBidContactFields"><label>Company<input required value={contact.company} onChange={event=>updateContact("company",event.target.value)}/></label><label>Contact name<input required value={contact.contactName} onChange={event=>updateContact("contactName",event.target.value)}/></label><label>Email<input required type="email" value={contact.email} onChange={event=>updateContact("email",event.target.value)}/></label><label>Phone<input required type="tel" value={contact.phone} onChange={event=>updateContact("phone",event.target.value)}/></label><label className="wide">Address<input required value={contact.address1} onChange={event=>updateContact("address1",event.target.value)}/></label><label className="wide">Address line 2 <small>Optional</small><input value={contact.address2} onChange={event=>updateContact("address2",event.target.value)}/></label><label>City<input required value={contact.city} onChange={event=>updateContact("city",event.target.value)}/></label><label>State / Region<input required value={contact.region} onChange={event=>updateContact("region",event.target.value)}/></label><label>ZIP / Postal code<input required value={contact.postalCode} onChange={event=>updateContact("postalCode",event.target.value)}/></label><label>Country<input required value={contact.country} onChange={event=>updateContact("country",event.target.value)}/></label></div></section>}
 {selected.length>0&&customer&&<section className="customerBidReview"><div><span>CUSTOMER</span><strong>{contact.company||customer.company}</strong><small>{contact.contactName||customer.contact_name} · {contact.email||customer.email}</small></div><div><span>DEAL</span><strong>{deal?.deal_number}</strong><small>{fileName}</small></div><div><span>PRICED LINES</span><strong>{selected.length}</strong><small>{totalQty.toLocaleString()} total units</small></div><div><span>BID TOTAL</span><strong>{money.format(total)}</strong><small>Calculated from unit bids</small></div><label>Internal notes<textarea rows={3} value={notes} onChange={event=>setNotes(event.target.value)} placeholder="Optional notes about the emailed offer"/></label><button onClick={submit} disabled={busy||Boolean(confirmation)||!contactComplete}>{busy?"Submitting customer bid…":confirmation?"Bid submitted ✓":contactComplete?"Submit Bid for Customer":"Complete Customer Details to Submit"}</button></section>}
 {message&&<p className="customerBidMessage">{message}</p>}{confirmation&&<section className="customerBidConfirmation"><span>INTERNAL BID NUMBER</span><strong>{confirmation}</strong><a href="/employee/deals">Open Deal Management</a></section>}{error&&<p className="customerBidError" role="alert">{error}</p>}</main>;
}
