"use client";
import {useEffect,useMemo,useState} from "react";
import {clearPddSession,currentPddSession} from "../../../lib/pdd-auth";
import "./applications.css";

type Kind="customer"|"vendor";type Site="m2m"|"brainfarm";
type Attachment={id:string;filename:string;content_type:string;size_bytes:number;created_at:string};
type Application={id:string;reference:string;site:string;kind:Kind;company:string;contact_name:string;email:string;phone:string;payload:string;status:string;created_at:string;attachments?:Attachment[]};
type Draft={company:string;contactName:string;email:string;phone:string;status:string;payload:Record<string,string>};
const special:Record<string,string>={dba:"DBA",federalId:"Federal ID",duns:"DUNS",ceoName:"CEO / President",cfoName:"CFO / Treasurer",accountsPayableName:"Accounts Payable",routingSwiftCode:"Routing / SWIFT Code",certificateR2v3:"R2v3",certificateISO9001:"ISO 9001",certificateISO14001:"ISO 14001",certificateISO45001:"ISO 45001",certificateESteward:"e-Stewards"};
const label=(key:string)=>special[key]||key.replace(/([A-Z])/g," $1").replace(/^./,letter=>letter.toUpperCase());
const when=(value:string)=>new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));
const parse=(value:string)=>{try{return JSON.parse(value||"{}") as Record<string,string>}catch{return {}}};
export default function Applications(){
 const [items,setItems]=useState<Application[]>([]),[kind,setKind]=useState<Kind>("customer"),[site,setSite]=useState<Site>("m2m"),[canEdit,setCanEdit]=useState(false),[open,setOpen]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[editing,setEditing]=useState(""),[draft,setDraft]=useState<Draft|null>(null),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 async function session(){const active=await currentPddSession();if(!active){window.location.replace("/employee-login?return_to=/employee/applications");return null}return active}
 async function load(selectedSite:Site){setLoading(true);setError("");setOpen("");setEditing("");const active=await session();if(!active)return;const response=await fetch(`/api/onboarding?site=${selectedSite}`,{headers:{Authorization:`Bearer ${active.access_token}`},cache:"no-store"});if(response.status===401){clearPddSession();window.location.replace("/employee-login?return_to=/employee/applications");return}if(response.status===403){window.location.replace("/employee");return}const data=await response.json().catch(()=>({})) as {applications?:Application[];canEdit?:boolean;error?:string};if(!response.ok)setError(data.error||"Onboarding records could not be loaded.");else{setItems(data.applications||[]);setCanEdit(Boolean(data.canEdit))}setLoading(false)}
 useEffect(()=>{const params=new URLSearchParams(window.location.search),selectedSite=params.get("site")==="brainfarm"?"brainfarm":"m2m";setSite(selectedSite);if(params.get("type")==="vendor")setKind("vendor");void load(selectedSite)},[]);
 const filtered=useMemo(()=>items.filter(item=>item.kind===kind),[items,kind]);
 function edit(item:Application){setDraft({company:item.company,contactName:item.contact_name,email:item.email,phone:item.phone,status:item.status,payload:parse(item.payload)});setEditing(item.id);setMessage("")}
 async function save(item:Application){if(!draft?.company.trim())return;setSaving(true);setMessage("");const active=await session();if(!active)return;const response=await fetch(`/api/onboarding?site=${site}`,{method:"PATCH",headers:{Authorization:`Bearer ${active.access_token}`,"content-type":"application/json"},body:JSON.stringify({id:item.id,...draft})}),data=await response.json().catch(()=>({})) as {error?:string};if(!response.ok){setMessage(data.error||"Application could not be saved.");setSaving(false);return}setItems(current=>current.map(row=>row.id===item.id?{...row,company:draft.company.trim(),contact_name:draft.contactName.trim(),email:draft.email.trim(),phone:draft.phone.trim(),status:draft.status,payload:JSON.stringify(draft.payload)}:row));setEditing("");setDraft(null);setSaving(false);setMessage(`${item.reference} saved.`)}
 async function download(file:Attachment){const active=await session();if(!active)return;const response=await fetch(`/api/onboarding/attachments?id=${encodeURIComponent(file.id)}&site=${site}`,{headers:{Authorization:`Bearer ${active.access_token}`}});if(!response.ok){setMessage("The document could not be downloaded.");return}const url=URL.createObjectURL(await response.blob()),anchor=document.createElement("a");anchor.href=url;anchor.download=file.filename;document.body.appendChild(anchor);anchor.click();anchor.remove();URL.revokeObjectURL(url)}
 return <main className="applicationRecordsPage"><header><div><p className="eyebrow">BUSINESS RECORDS</p><h1>Customer &amp; Vendor Onboarding</h1><p>{canEdit?"Review and update records submitted through the onboarding forms.":"View records submitted through the onboarding forms."}</p></div><a href="/employee">← Dashboard</a></header>
 <section className="applicationRecordTools"><div className="applicationRecordTabs"><button className={site==="m2m"?"active":""} onClick={()=>{setSite("m2m");void load("m2m")}}>Mac2MacOnline</button><button className={site==="brainfarm"?"active":""} onClick={()=>{setSite("brainfarm");void load("brainfarm")}}>BrainFarm</button></div><div className="applicationRecordTabs"><button className={kind==="customer"?"active":""} onClick={()=>setKind("customer")}>Customer Onboarding <span>{items.filter(x=>x.kind==="customer").length}</span></button><button className={kind==="vendor"?"active":""} onClick={()=>setKind("vendor")}>Vendor Onboarding <span>{items.filter(x=>x.kind==="vendor").length}</span></button></div></section>
 {message&&<p className="applicationRecordSaved">{message}</p>}{loading?<p className="applicationRecordMessage">Loading onboarding records…</p>:error?<p className="applicationRecordMessage error">{error}</p>:filtered.length===0?<p className="applicationRecordMessage">No {kind} onboarding records have been submitted yet.</p>:<section className="applicationRecordList">{filtered.map(item=>{const payload=parse(item.payload),details=[["Company",item.company],["Contact name",item.contact_name],["Email",item.email],["Phone",item.phone],["Site",item.site],["Status",item.status],...Object.entries(payload).map(([key,value])=>[label(key),value])].filter(([,value])=>String(value||"").trim());return <article className={open===item.id?"open":""} key={item.id}><button className="applicationRecordSummary" onClick={()=>{setOpen(open===item.id?"":item.id);setEditing("");setDraft(null)}}><div><span>{item.reference}</span><h2>{item.company}</h2><p>{item.contact_name||item.email||"No contact entered"}</p></div><div><small>Submitted</small><strong>{when(item.created_at)}</strong></div><b>{open===item.id?"Close":"View"}</b></button>{open===item.id&&<div className="applicationRecordDetails">
 {item.attachments?.length?<section className="applicationRecordAttachments"><h3>Attached Documents</h3>{item.attachments.map(file=><button type="button" key={file.id} onClick={()=>void download(file)}><b>{file.filename}</b><span>{(file.size_bytes/1024/1024).toFixed(2)} MB · Download</span></button>)}</section>:null}
 {editing===item.id&&draft?<form className="applicationRecordEditor" onSubmit={event=>{event.preventDefault();void save(item)}}><label>Company<input value={draft.company} onChange={event=>setDraft({...draft,company:event.target.value})} required/></label><label>Contact name<input value={draft.contactName} onChange={event=>setDraft({...draft,contactName:event.target.value})}/></label><label>Email<input type="email" value={draft.email} onChange={event=>setDraft({...draft,email:event.target.value})}/></label><label>Phone<input value={draft.phone} onChange={event=>setDraft({...draft,phone:event.target.value})}/></label><label>Status<select value={draft.status} onChange={event=>setDraft({...draft,status:event.target.value})}><option value="new">New</option><option value="reviewing">Reviewing</option><option value="approved">Approved</option><option value="declined">Declined</option><option value="completed">Completed</option></select></label>{Object.entries(draft.payload).map(([key,value])=><label key={key}>{label(key)}<textarea rows={String(value).length>90?3:1} value={value} onChange={event=>setDraft({...draft,payload:{...draft.payload,[key]:event.target.value}})}/></label>)}<div className="applicationRecordEditActions"><button type="button" className="button secondary" onClick={()=>{setEditing("");setDraft(null)}}>Cancel</button><button className="button" disabled={saving}>{saving?"Saving…":"Save Changes"}</button></div></form>:<><dl>{details.map(([name,value])=><div key={name}><dt>{name}</dt><dd>{name==="Email"?<a href={`mailto:${value}`}>{value}</a>:name.includes("Phone")?<a href={`tel:${value}`}>{value}</a>:value}</dd></div>)}</dl>{canEdit&&<div className="applicationRecordActions"><button className="button" onClick={()=>edit(item)}>Edit Onboarding</button></div>}</>}</div>}</article>})}</section>}</main>
}
