"use client";
import {useEffect,useMemo,useState} from "react";
import {clearPddSession,currentPddSession,pddAuthFetch} from "../../../lib/pdd-auth";

type PurchaseLine={id:string;line_number:number;product_sku:string;product_description:string;quantity:number;unit_cost:number;line_total:number;order:{po_number:string;deal_number:string;created_at:string;purchasing_owner_name:string;purchasing_owner_email:string;vendor:{company_name:string}|null}};
type SalesLine={id:string;line_number:number;product_sku:string;product_description:string;quantity:number;unit_price:number;line_total:number;order:{so_number:string;deal_number:string;created_at:string;sales_owner_name:string;sales_owner_email:string;customer_company:string}};
type ReportRow={kind:"Purchase"|"Sale";number:string;date:string;employee:string;email:string;party:string;sku:string;description:string;quantity:number;unitAmount:number;total:number;purchasePrice:number|null;profit:number|null};
type EmployeeTotal={employee:string;purchased:number;purchaseValue:number;sold:number;salesValue:number;salesPurchasePrice:number;profit:number};
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"});
const day=(value:string)=>value.slice(0,10);
const csvCell=(value:string|number)=>`"${String(value).replaceAll('"','""')}"`;
const reportEmployees=["Daren Spencer","Darrell Pierro","Frankie Kitchell"] as const;
const reportEmployee=(value:string)=>{const name=String(value||"").trim().toLowerCase();if(name.startsWith("daren"))return "Daren Spencer";if(name.startsWith("darrell"))return "Darrell Pierro";if(name.startsWith("frankie"))return "Frankie Kitchell";return ""};

export default function ReportsPage(){
 const [rows,setRows]=useState<ReportRow[]>([]),[team,setTeam]=useState<string[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[scope,setScope]=useState<"all"|"sales"|"purchases">("all"),[query,setQuery]=useState(""),[employee,setEmployee]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState("");
 useEffect(()=>{void(async()=>{
  const session=await currentPddSession();if(!session){window.location.replace("/employee-login?return_to=/employee/reports");return}
  const headers={Authorization:`Bearer ${session.access_token}`};
  const [purchases,sales]=await Promise.all([
   pddAuthFetch("/rest/v1/pdd_purchase_order_lines?select=id,line_number,product_sku,product_description,quantity,unit_cost,line_total,order:pdd_purchase_orders!inner(po_number,deal_number,created_at,purchasing_owner_name,purchasing_owner_email,vendor:pdd_vendors(company_name))&order=created_at.desc",{headers}),
   pddAuthFetch("/rest/v1/pdd_sales_order_lines?select=id,line_number,product_sku,product_description,quantity,unit_price,line_total,order:pdd_sales_orders!inner(so_number,deal_number,created_at,sales_owner_name,sales_owner_email,customer_company)&order=created_at.desc",{headers})
  ]);
  if(purchases.status===401||sales.status===401){clearPddSession();window.location.replace("/employee-login");return}
  if(!purchases.ok||!sales.ok){setMessage("Reports could not be loaded.");setLoading(false);return}
  const purchaseRows=await purchases.json() as PurchaseLine[],salesRows=await sales.json() as SalesLine[];
  const purchasePriceByDealLine=new Map(purchaseRows.map(line=>[`${line.order.deal_number}:${line.line_number}`,Number(line.line_total)]));
  const combined:ReportRow[]=[
   ...purchaseRows.map(line=>({kind:"Purchase" as const,number:line.order.po_number,date:line.order.created_at,employee:line.order.purchasing_owner_name||"Unassigned",email:line.order.purchasing_owner_email||"",party:line.order.vendor?.company_name||"Vendor",sku:line.product_sku||"",description:line.product_description,quantity:Number(line.quantity),unitAmount:Number(line.unit_cost),total:Number(line.line_total),purchasePrice:null,profit:null})),
   ...salesRows.map(line=>{const purchasePrice=purchasePriceByDealLine.get(`${line.order.deal_number}:${line.line_number}`)??null,total=Number(line.line_total);return {kind:"Sale" as const,number:line.order.so_number,date:line.order.created_at,employee:line.order.sales_owner_name||"Unassigned",email:line.order.sales_owner_email||"",party:line.order.customer_company,sku:line.product_sku||"",description:line.product_description,quantity:Number(line.quantity),unitAmount:Number(line.unit_price),total,purchasePrice,profit:purchasePrice===null?null:total-purchasePrice}})
  ].map(row=>({...row,employee:reportEmployee(row.employee)})).filter(row=>Boolean(row.employee));
  setRows(combined);
  setTeam([...reportEmployees]);
  setLoading(false);
 })()},[]);
 const employees=useMemo(()=>[...team].sort((a,b)=>a.localeCompare(b)),[team]);
 const visible=useMemo(()=>{const search=query.trim().toLowerCase();return rows.filter(row=>(scope==="all"||scope==="sales"&&row.kind==="Sale"||scope==="purchases"&&row.kind==="Purchase")&&(!employee||row.employee===employee)&&(!from||day(row.date)>=from)&&(!to||day(row.date)<=to)&&(!search||`${row.sku} ${row.description} ${row.party} ${row.number}`.toLowerCase().includes(search)))},[rows,scope,query,employee,from,to]);
 const totals=useMemo(()=>{const sales=visible.filter(row=>row.kind==="Sale"),salesValue=sales.reduce((sum,row)=>sum+row.total,0),salesPurchasePrice=sales.reduce((sum,row)=>sum+(row.purchasePrice||0),0),totalProfit=sales.reduce((sum,row)=>sum+(row.profit||0),0);return {purchased:visible.filter(row=>row.kind==="Purchase").reduce((sum,row)=>sum+row.quantity,0),purchaseValue:visible.filter(row=>row.kind==="Purchase").reduce((sum,row)=>sum+row.total,0),sold:sales.reduce((sum,row)=>sum+row.quantity,0),salesValue,salesPurchasePrice,totalProfit,profitMargin:salesValue?totalProfit/salesValue*100:0}},[visible]);
 const byPerson=useMemo(()=>{const names=employee?[employee]:employees,result=new Map<string,EmployeeTotal>(names.map(name=>[name,{employee:name,purchased:0,purchaseValue:0,sold:0,salesValue:0,salesPurchasePrice:0,profit:0}]));for(const row of visible){const current=result.get(row.employee)||{employee:row.employee,purchased:0,purchaseValue:0,sold:0,salesValue:0,salesPurchasePrice:0,profit:0};if(row.kind==="Purchase"){current.purchased+=row.quantity;current.purchaseValue+=row.total}else{current.sold+=row.quantity;current.salesValue+=row.total;current.salesPurchasePrice+=row.purchasePrice||0;current.profit+=row.profit||0}result.set(row.employee,current)}return [...result.values()].sort((a,b)=>a.employee.localeCompare(b.employee))},[visible,employees,employee]);
 const maxEmployeeValue=Math.max(1,...byPerson.flatMap(row=>[row.salesValue,row.purchaseValue,Math.max(0,row.profit)]));
 const byProduct=useMemo(()=>{const result=new Map<string,{sku:string;description:string;purchased:number;purchaseValue:number;sold:number;salesValue:number;salesPurchasePrice:number;profit:number}>();for(const row of visible){const key=(row.sku||row.description).trim().toLowerCase(),current=result.get(key)||{sku:row.sku,description:row.description,purchased:0,purchaseValue:0,sold:0,salesValue:0,salesPurchasePrice:0,profit:0};if(row.kind==="Purchase"){current.purchased+=row.quantity;current.purchaseValue+=row.total}else{current.sold+=row.quantity;current.salesValue+=row.total;current.salesPurchasePrice+=row.purchasePrice||0;current.profit+=row.profit||0}result.set(key,current)}return [...result.values()].sort((a,b)=>b.sold+b.purchased-a.sold-a.purchased)},[visible]);
 function downloadReport(){const header=["Type","Order","Date","Employee","Employee Email","Vendor / Customer","SKU","Description","Quantity","Unit Amount","Total","Purchase Price","Profit Margin","Total Profit"],csv=[header.map(csvCell).join(","),...visible.map(row=>[row.kind,row.number,day(row.date),row.employee,row.email,row.party,row.sku,row.description,row.quantity,row.unitAmount.toFixed(2),row.total.toFixed(2),row.purchasePrice===null?"":row.purchasePrice.toFixed(2),row.profit===null||!row.total?"":`${(row.profit/row.total*100).toFixed(2)}%`,row.profit===null?"":row.profit.toFixed(2)].map(csvCell).join(","))].join("\n"),url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})),link=document.createElement("a");link.href=url;link.download=`M2M-${scope}-report-${from||"all"}-${to||"current"}.csv`;link.click();URL.revokeObjectURL(url)}
 if(loading)return <main className="reportsPage"><p>Loading purchasing and sales reports…</p></main>;
 return <main className="reportsPage"><header><div><p className="eyebrow">BUSINESS RECORDS</p><h1>Employee Sales &amp; Purchasing Reports</h1><p>Compare every employee, filter the records and generate a report.</p></div><a href="/employee">← Dashboard</a></header>
 <section className="reportFilters"><div className="reportTabs"><button className={scope==="all"?"active":""} onClick={()=>setScope("all")}>All</button><button className={scope==="sales"?"active":""} onClick={()=>setScope("sales")}>Sales</button><button className={scope==="purchases"?"active":""} onClick={()=>setScope("purchases")}>Purchases</button></div><label>Product, SKU or party<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="16GB PC4-2133P"/></label><label>Employee<select value={employee} onChange={event=>setEmployee(event.target.value)}><option value="">All employees</option>{employees.map(name=><option key={name}>{name}</option>)}</select></label><label>From<input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>To<input type="date" value={to} onChange={event=>setTo(event.target.value)}/></label></section>
 <div className="reportGenerateActions"><button className="button" type="button" onClick={downloadReport} disabled={!visible.length}>Download Report</button><button className="button secondary" type="button" onClick={()=>window.print()}>Print Report</button></div>
 {message?<p className="reportMessage">{message}</p>:<><section className="reportTotals"><article><span>Purchased units</span><strong>{totals.purchased.toLocaleString()}</strong><small>{money.format(totals.purchaseValue)}</small></article><article><span>Sold units</span><strong>{totals.sold.toLocaleString()}</strong><small>{money.format(totals.salesValue)}</small></article><article><span>Purchase value</span><strong>{money.format(totals.purchaseValue)}</strong><small>{visible.filter(row=>row.kind==="Purchase").length} lines</small></article><article><span>Sales revenue</span><strong>{money.format(totals.salesValue)}</strong><small>{visible.filter(row=>row.kind==="Sale").length} lines</small></article><article><span>Sales purchase price</span><strong>{money.format(totals.salesPurchasePrice)}</strong><small>Cost of goods sold</small></article><article><span>Profit margin</span><strong>{totals.profitMargin.toFixed(2)}%</strong><small>Profit ÷ sales revenue</small></article><article><span>Total profit</span><strong>{money.format(totals.totalProfit)}</strong><small>Sales less purchase price</small></article></section>
 <section className="reportPanel employeeGraphicPanel"><header><div><h2>All employees</h2><p>Sales, purchasing value and profit by employee</p></div><span>{byPerson.length} employees</span></header><div className="employeeReportLegend"><span className="salesLegend">Sales</span><span className="purchaseLegend">Purchasing</span><span className="profitLegend">Profit</span></div><div className="employeeReportChart">{byPerson.map(row=><article key={row.employee}><strong>{row.employee}</strong><div className="employeeBarRow"><span>Sales</span><div><i className="salesBar" style={{width:`${row.salesValue/maxEmployeeValue*100}%`}}/></div><b>{money.format(row.salesValue)}</b></div><div className="employeeBarRow"><span>Buy</span><div><i className="purchaseBar" style={{width:`${row.purchaseValue/maxEmployeeValue*100}%`}}/></div><b>{money.format(row.purchaseValue)}</b></div><div className="employeeBarRow"><span>Profit</span><div><i className="profitBar" style={{width:`${Math.max(0,row.profit)/maxEmployeeValue*100}%`}}/></div><b>{money.format(row.profit)}</b></div></article>)}</div></section>
 <section className="reportPanel"><header><h2>Employee details</h2><span>{byPerson.length} employees</span></header><div className="reportTable"><table><thead><tr><th>Employee</th><th>Purchased</th><th>Purchase value</th><th>Sold</th><th>Sales revenue</th><th>Purchase price</th><th>Profit margin</th><th>Total profit</th></tr></thead><tbody>{byPerson.map(row=><tr key={row.employee}><td><b>{row.employee}</b></td><td>{row.purchased.toLocaleString()}</td><td>{money.format(row.purchaseValue)}</td><td>{row.sold.toLocaleString()}</td><td>{money.format(row.salesValue)}</td><td>{money.format(row.salesPurchasePrice)}</td><td>{row.salesValue?(row.profit/row.salesValue*100).toFixed(2):"0.00"}%</td><td>{money.format(row.profit)}</td></tr>)}</tbody></table></div></section>
 <section className="reportPanel"><header><h2>By product description / SKU</h2><span>{byProduct.length} products</span></header><div className="reportTable"><table><thead><tr><th>SKU</th><th>Description</th><th>Purchased</th><th>Purchase value</th><th>Sold</th><th>Sales revenue</th><th>Purchase price</th><th>Profit margin</th><th>Total profit</th></tr></thead><tbody>{byProduct.map((row,index)=><tr key={`${row.sku}-${index}`}><td><b>{row.sku||"—"}</b></td><td>{row.description}</td><td>{row.purchased.toLocaleString()}</td><td>{money.format(row.purchaseValue)}</td><td>{row.sold.toLocaleString()}</td><td>{money.format(row.salesValue)}</td><td>{money.format(row.salesPurchasePrice)}</td><td>{row.salesValue?(row.profit/row.salesValue*100).toFixed(2):"0.00"}%</td><td>{money.format(row.profit)}</td></tr>)}</tbody></table></div></section></>}</main>;
}
