"use client";
import {useEffect,useMemo,useState} from "react";
import {clearPddSession,currentPddSession,pddAuthFetch} from "../../../lib/pdd-auth";

type PurchaseLine={id:string;product_sku:string;product_description:string;quantity:number;unit_cost:number;line_total:number;order:{po_number:string;created_at:string;purchasing_owner_name:string;purchasing_owner_email:string;vendor:{company_name:string}|null}};
type SalesLine={id:string;product_sku:string;product_description:string;quantity:number;unit_price:number;line_total:number;order:{so_number:string;created_at:string;sales_owner_name:string;sales_owner_email:string;customer_company:string}};
type ReportRow={kind:"Purchase"|"Sale";number:string;date:string;employee:string;email:string;party:string;sku:string;description:string;quantity:number;unitAmount:number;total:number};
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"});
const day=(value:string)=>value.slice(0,10);

export default function ReportsPage(){
 const [rows,setRows]=useState<ReportRow[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[scope,setScope]=useState<"all"|"sales"|"purchases">("all"),[query,setQuery]=useState(""),[employee,setEmployee]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState("");
 useEffect(()=>{void(async()=>{const session=await currentPddSession();if(!session){window.location.replace("/employee-login?return_to=/employee/reports");return}const headers={Authorization:`Bearer ${session.access_token}`};const [purchases,sales]=await Promise.all([pddAuthFetch("/rest/v1/pdd_purchase_order_lines?select=id,product_sku,product_description,quantity,unit_cost,line_total,order:pdd_purchase_orders!inner(po_number,created_at,purchasing_owner_name,purchasing_owner_email,vendor:pdd_vendors(company_name))&order=created_at.desc",{headers}),pddAuthFetch("/rest/v1/pdd_sales_order_lines?select=id,product_sku,product_description,quantity,unit_price,line_total,order:pdd_sales_orders!inner(so_number,created_at,sales_owner_name,sales_owner_email,customer_company)&order=created_at.desc",{headers})]);if(purchases.status===401||sales.status===401){clearPddSession();window.location.replace("/employee-login");return}if(!purchases.ok||!sales.ok){setMessage("Reports could not be loaded. The order-line database update may still need to be published.");setLoading(false);return}const purchaseRows=await purchases.json() as PurchaseLine[],salesRows=await sales.json() as SalesLine[];setRows([...purchaseRows.map(line=>({kind:"Purchase" as const,number:line.order.po_number,date:line.order.created_at,employee:line.order.purchasing_owner_name||"Unassigned",email:line.order.purchasing_owner_email||"",party:line.order.vendor?.company_name||"Vendor",sku:line.product_sku||"",description:line.product_description,quantity:Number(line.quantity),unitAmount:Number(line.unit_cost),total:Number(line.line_total)})),...salesRows.map(line=>({kind:"Sale" as const,number:line.order.so_number,date:line.order.created_at,employee:line.order.sales_owner_name||"Unassigned",email:line.order.sales_owner_email||"",party:line.order.customer_company,sku:line.product_sku||"",description:line.product_description,quantity:Number(line.quantity),unitAmount:Number(line.unit_price),total:Number(line.line_total)}))]);setLoading(false)})()},[]);
 const employees=useMemo(()=>[...new Set(rows.map(row=>row.employee))].sort(),[rows]);
 const visible=useMemo(()=>{const search=query.trim().toLowerCase();return rows.filter(row=>(scope==="all"||scope==="sales"&&row.kind==="Sale"||scope==="purchases"&&row.kind==="Purchase")&&(!employee||row.employee===employee)&&(!from||day(row.date)>=from)&&(!to||day(row.date)<=to)&&(!search||`${row.sku} ${row.description} ${row.party} ${row.number}`.toLowerCase().includes(search)))},[rows,scope,query,employee,from,to]);
 const totals=useMemo(()=>({purchased:visible.filter(row=>row.kind==="Purchase").reduce((sum,row)=>sum+row.quantity,0),purchaseValue:visible.filter(row=>row.kind==="Purchase").reduce((sum,row)=>sum+row.total,0),sold:visible.filter(row=>row.kind==="Sale").reduce((sum,row)=>sum+row.quantity,0),salesValue:visible.filter(row=>row.kind==="Sale").reduce((sum,row)=>sum+row.total,0)}),[visible]);
 const byPerson=useMemo(()=>{const result=new Map<string,{employee:string;purchased:number;purchaseValue:number;sold:number;salesValue:number}>();for(const row of visible){const current=result.get(row.employee)||{employee:row.employee,purchased:0,purchaseValue:0,sold:0,salesValue:0};if(row.kind==="Purchase"){current.purchased+=row.quantity;current.purchaseValue+=row.total}else{current.sold+=row.quantity;current.salesValue+=row.total}result.set(row.employee,current)}return [...result.values()].sort((a,b)=>b.salesValue+b.purchaseValue-a.salesValue-a.purchaseValue)},[visible]);
 const byProduct=useMemo(()=>{const result=new Map<string,{sku:string;description:string;purchased:number;purchaseValue:number;sold:number;salesValue:number}>();for(const row of visible){const key=(row.sku||row.description).trim().toLowerCase(),current=result.get(key)||{sku:row.sku,description:row.description,purchased:0,purchaseValue:0,sold:0,salesValue:0};if(row.kind==="Purchase"){current.purchased+=row.quantity;current.purchaseValue+=row.total}else{current.sold+=row.quantity;current.salesValue+=row.total}result.set(key,current)}return [...result.values()].sort((a,b)=>b.sold+b.purchased-a.sold-a.purchased)},[visible]);
 if(loading)return <main className="reportsPage"><p>Loading purchasing and sales reports…</p></main>;
 return <main className="reportsPage"><header><div><p className="eyebrow">DEAL WORKBOOK</p><h1>Purchasing &amp; Sales Reports</h1><p>Sales follow the customer owner. Purchases follow the vendor owner.</p></div><a href="/employee">← Deal Workbook</a></header>
 <section className="reportFilters"><div className="reportTabs"><button className={scope==="all"?"active":""} onClick={()=>setScope("all")}>All</button><button className={scope==="sales"?"active":""} onClick={()=>setScope("sales")}>Sales</button><button className={scope==="purchases"?"active":""} onClick={()=>setScope("purchases")}>Purchases</button></div><label>Product, SKU or party<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="16GB PC4-2133P"/></label><label>Employee<select value={employee} onChange={event=>setEmployee(event.target.value)}><option value="">All employees</option>{employees.map(name=><option key={name}>{name}</option>)}</select></label><label>From<input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>To<input type="date" value={to} onChange={event=>setTo(event.target.value)}/></label></section>
 {message?<p className="reportMessage">{message}</p>:<><section className="reportTotals"><article><span>Purchased units</span><strong>{totals.purchased.toLocaleString()}</strong><small>{money.format(totals.purchaseValue)}</small></article><article><span>Sold units</span><strong>{totals.sold.toLocaleString()}</strong><small>{money.format(totals.salesValue)}</small></article><article><span>Purchase value</span><strong>{money.format(totals.purchaseValue)}</strong><small>{visible.filter(row=>row.kind==="Purchase").length} lines</small></article><article><span>Sales revenue</span><strong>{money.format(totals.salesValue)}</strong><small>{visible.filter(row=>row.kind==="Sale").length} lines</small></article></section>
 <section className="reportPanel"><header><h2>By employee</h2><span>{byPerson.length} employees</span></header><div className="reportTable"><table><thead><tr><th>Employee</th><th>Purchased</th><th>Purchase value</th><th>Sold</th><th>Sales revenue</th></tr></thead><tbody>{byPerson.map(row=><tr key={row.employee}><td><b>{row.employee}</b></td><td>{row.purchased.toLocaleString()}</td><td>{money.format(row.purchaseValue)}</td><td>{row.sold.toLocaleString()}</td><td>{money.format(row.salesValue)}</td></tr>)}</tbody></table></div></section>
 <section className="reportPanel"><header><h2>By product description / SKU</h2><span>{byProduct.length} products</span></header><div className="reportTable"><table><thead><tr><th>SKU</th><th>Description</th><th>Purchased</th><th>Purchase value</th><th>Sold</th><th>Sales revenue</th></tr></thead><tbody>{byProduct.map((row,index)=><tr key={`${row.sku}-${index}`}><td><b>{row.sku||"—"}</b></td><td>{row.description}</td><td>{row.purchased.toLocaleString()}</td><td>{money.format(row.purchaseValue)}</td><td>{row.sold.toLocaleString()}</td><td>{money.format(row.salesValue)}</td></tr>)}</tbody></table></div></section></>}</main>;
}
