import {env} from "cloudflare:workers";
import {employeeUser} from "../../../lib/employee-server";

type Photo={id:string;deal_number:string;filename:string;content_type:string;sort_order:number};
const allowed=new Set(["image/jpeg","image/png","image/webp","image/gif"]);
const clean=(value:unknown)=>String(value||"").trim().toUpperCase();

export async function GET(request:Request){const deal=clean(new URL(request.url).searchParams.get("deal"));if(!deal)return Response.json({photos:[]});const rows=await env.DB.prepare("SELECT id,deal_number,filename,content_type,sort_order FROM deal_photos WHERE deal_number=? ORDER BY sort_order,created_at").bind(deal).all<Photo>();return Response.json({photos:(rows.results||[]).map(photo=>({...photo,url:`/api/deal-photos/${photo.id}`}))},{headers:{"Cache-Control":"no-store"}})}

export async function POST(request:Request){const employee=await employeeUser(request);if(!employee)return Response.json({error:"Employee access required."},{status:401});const form=await request.formData(),deal=clean(form.get("deal")),files=form.getAll("photos").filter((value):value is File=>value instanceof File);if(!deal)return Response.json({error:"Deal number is required."},{status:400});if(!files.length)return Response.json({error:"Choose at least one picture."},{status:400});const current=await env.DB.prepare("SELECT COUNT(*) total FROM deal_photos WHERE deal_number=?").bind(deal).first<{total:number}>(),remaining=Math.max(0,12-Number(current?.total||0));if(!remaining)return Response.json({error:"This deal already has the maximum of 12 pictures."},{status:400});const now=new Date().toISOString(),saved=[];for(const [index,file] of files.slice(0,remaining).entries()){if(!allowed.has(file.type)||file.size>10*1024*1024)continue;const id=crypto.randomUUID(),extension=file.type==="image/png"?"png":file.type==="image/webp"?"webp":file.type==="image/gif"?"gif":"jpg",key=`deal-photos/${deal}/${id}.${extension}`;await env.BUCKET.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type},customMetadata:{deal}});await env.DB.prepare("INSERT INTO deal_photos (id,deal_number,object_key,filename,content_type,sort_order,uploaded_by,created_at) VALUES (?,?,?,?,?,?,?,?)").bind(id,deal,key,file.name,file.type,Number(current?.total||0)+index,employee.email,now).run();saved.push({id,deal_number:deal,filename:file.name,content_type:file.type,sort_order:Number(current?.total||0)+index,url:`/api/deal-photos/${id}`})}if(!saved.length)return Response.json({error:"Use JPG, PNG, WebP or GIF pictures under 10MB each."},{status:400});return Response.json({photos:saved})}

export async function DELETE(request:Request){const employee=await employeeUser(request);if(!employee)return Response.json({error:"Employee access required."},{status:401});const id=new URL(request.url).searchParams.get("id")||"",photo=await env.DB.prepare("SELECT object_key FROM deal_photos WHERE id=?").bind(id).first<{object_key:string}>();if(!photo)return Response.json({error:"Picture not found."},{status:404});await env.BUCKET.delete(photo.object_key);await env.DB.prepare("DELETE FROM deal_photos WHERE id=?").bind(id).run();return Response.json({ok:true})}
