"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";
import {Shell} from "@/components/SiteShell";
import "./line-bid.css";

type SourceRow=Record<string,string>;
type BidEntry={unitBid:string;comments:string};
function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[];let cell="";let quoted=false;for(let i=0;i<text.length;i++){const char=text[i];if(quoted){if(char==='"'&&text[i+1]==='"'){cell+='"';i++}else if(char==='"')quoted=false;else cell+=char}else if(char==='"')quoted=true;else if(char===","){row.push(cell);cell=""}else if(char==="\n"){row.push(cell.replace(/\r$/,"").trim());rows.push(row);row=[];cell=""}else cell+=char}if(cell||row.length){row.push(cell.replace(/\r$/,"").trim());rows.push(row)}const headers=rows.shift()||[];return rows.filter(values=>values.some(Boolean)).map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]||""])))}
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"});

export default function LineItemBid(){
 const [rows,setRows]=useState<SourceRow[]>([]);const [entries,setEntries]=useState<Record<number,BidEntry>>({});const [loading,setLoading]=useState(true);const [submitting,setSubmitting]=useState(false);const [error,setError]=useState("");const [confirmation,setConfirmation]=useState<{number:string;lines:number;total:number}|null>(null);
 useEffect(()=>{fetch("/deals/itamg-server-lot-source.csv").then(r=>r.text()).then(text=>setRows(parseCsv(text))).catch(()=>setError("The server list could not be loaded.")).finally(()=>setLoading(false))},[]);
 const selected=useMemo(()=>rows.map((row,index)=>({row,index,entry:entries[index]})).filter(item=>Number(item.entry?.unitBid)>0),[rows,entries]);
 const total=useMemo(()=>selected.reduce((sum,item)=>sum+Number(item.entry.unitBid),0),[selected]);
 function update(index:number,patch:Partial<BidEntry>){setEntries(current=>({...current,[index]:{unitBid:current[index]?.unitBid||"",comments:current[index]?.comments||"",...patch}}))}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");setConfirmation(null);if(!selected.length){setError("Enter a unit bid on at least one server line.");return}setSubmitting(true);const form=new FormData(event.currentTarget);const lineItems=selected.map(({row,index,entry})=>({lineNumber:index+1,assetId:row["Asset ID"],brand:row.Brand,model:row.Model,modelNumber:row["Model#"],processor:row.Processor,ram:row.RAM,hardDrive:row.Hard_Drive,condition:row.Condition||row.Unit_Condition,issues:row["Issues & Comments"],quantity:1,unitBid:Number(entry.unitBid),comments:entry.comments}));try{const response=await fetch("/api/line-item-bids",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({dealNumber:"B082126-01",company:form.get("company"),contactName:form.get("contact"),email:form.get("email"),phone:form.get("phone"),customerNotes:form.get("notes"),lineItems})});const data=await response.json();if(!response.ok)throw new Error(data.error||"The bid could not be submitted.");setConfirmation({number:data.internalBidNumber,lines:data.lineCount,total:data.totalBid});window.scrollTo({top:0,behavior:"smooth"})}catch(reason){setError(reason instanceof Error?reason.message:"The bid could not be submitted.")}finally{setSubmitting(false)}}
 return <Shell><main className="lineBid"><section className="lineBidHero"><a href="/public-deal-desk">← Back to Public Deal Desk</a><p>LINE-ITEM BID ENTRY</p><h1>B082126-01</h1><h2>181-Unit Mixed Enterprise Server Lot</h2><div><span>Closes Aug 28, 2026 · 5:00 PM PT</span><span>Bid on any or all units</span><span>Prices in USD</span></div></section>
 {confirmation&&<section className="bidConfirmation"><strong>Internal bid generated</strong><h2>{confirmation.number}</h2><p>{confirmation.lines} line items · {money.format(confirmation.total)} total</p><p>Please save this confirmation number. Mac2MacOnline will contact you after bids are reviewed.</p></section>}
 <form className="lineBidForm" onSubmit={submit}><section className="bidderPanel"><div><h2>Bidder information</h2><p>All pricing is confidential.</p></div><label>Company<input required name="company"/></label><label>Contact name<input required name="contact"/></label><label>Email<input required type="email" name="email"/></label><label>Phone<input required name="phone" inputMode="tel"/></label><label className="wide">General bid notes<textarea name="notes" rows={3} placeholder="Shipping timing, payment terms or overall conditions"/></label></section>
 <section className="bidSummary"><div><span>Lines bid</span><strong>{selected.length}</strong></div><div><span>Total units</span><strong>{selected.length}</strong></div><div><span>Total bid</span><strong>{money.format(total)}</strong></div><button disabled={submitting||!selected.length}>{submitting?"Generating internal bid…":"Submit Line-Item Bid"}</button></section>
 {error&&<p className="lineBidError">{error}</p>}
 <section className="lineItems"><div className="lineItemsHeading"><div><h2>Enter your price by server</h2><p>Leave the bid field blank for any unit you do not want.</p></div><strong>{loading?"Loading…":`${rows.length} available units`}</strong></div><div className="lineTableWrap"><table><thead><tr><th>Line</th><th>Asset ID</th><th>Server</th><th>Configuration</th><th>Condition</th><th>Unit Bid</th><th>Bid Comments</th></tr></thead><tbody>{rows.map((row,index)=><tr className={Number(entries[index]?.unitBid)>0?"hasBid":""} key={`${row["Asset ID"]}-${index}`}><td>{index+1}</td><td>{row["Asset ID"]}</td><td><b>{row.Brand} {row.Model}</b><small>{row["Model#"]}</small></td><td><b>{row.Processor}</b><small>RAM: {row.RAM||"—"} · Drive: {row.Hard_Drive||"—"}</small></td><td>{row.Condition||row.Unit_Condition||"—"}<small>{row["Issues & Comments"]}</small></td><td><div className="priceInput"><span>$</span><input aria-label={`Unit bid for line ${index+1}`} type="number" min="0" step="0.01" value={entries[index]?.unitBid||""} onChange={e=>update(index,{unitBid:e.target.value})}/></div></td><td><input aria-label={`Comments for line ${index+1}`} value={entries[index]?.comments||""} onChange={e=>update(index,{comments:e.target.value})} placeholder="Optional"/></td></tr>)}</tbody></table></div></section>
 <section className="bidSubmitBar"><div><span>{selected.length} lines selected</span><strong>{money.format(total)}</strong></div><button disabled={submitting||!selected.length}>{submitting?"Generating internal bid…":"Submit Line-Item Bid"}</button></section></form></main></Shell>
}
