"use client";
import {useEffect,useMemo,useState} from "react";
import {clearPddSession,currentPddSession,pddAuthFetch} from "../../../lib/pdd-auth";
import "./commissions.css";
import "./fees.css";

type Session={access_token:string};type User={id:string};type Profile={email:string;display_name:string};
type PO={id:string;po_number:string;deal_number:string;vendor_total:number;purchasing_owner_name:string;purchasing_owner_email:string;vendor:{company_name:string}|null};
type SO={id:string;so_number:string;deal_number:string;sales_total:number;sales_owner_name:string;sales_owner_email:string;customer_company:string};
type Commission={id:string;purchase_order_number:string;sales_order_number:string;buyer_name:string;salesperson_name:string;purchase_cost:number;sales_total:number;shipping_cost:number;credit_card_fee:number;gross_profit:number;buyer_rate:number;salesperson_rate:number;buyer_commission:number;salesperson_commission:number;commission_rule:string;created_at:string};
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"});const round=(value:number)=>Math.round(value*100)/100;const normalized=(value:string)=>value.trim().toLowerCase();

export default function CommissionsPage(){
 const [session,setSession]=useState<Session|null>(null),[user,setUser]=useState<User|null>(null),[profile,setProfile]=useState<Profile|null>(null),[purchaseOrders,setPurchaseOrders]=useState<PO[]>([]),[salesOrders,setSalesOrders]=useState<SO[]>([]),[records,setRecords]=useState<Commission[]>([]),[poId,setPoId]=useState(""),[soId,setSoId]=useState(""),[shipping,setShipping]=useState("0"),[ccFee,setCcFee]=useState("0"),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 async function load(active:Session){const headers={Authorization:`Bearer ${active.access_token}`};const [userResponse,profileResponse,poResponse,soResponse,commissionResponse]=await Promise.all([pddAuthFetch("/auth/v1/user",{headers}),pddAuthFetch("/rest/v1/pdd_employee_access?select=email,display_name&limit=1",{headers}),pddAuthFetch("/rest/v1/pdd_purchase_orders?select=id,po_number,deal_number,vendor_total,purchasing_owner_name,purchasing_owner_email,vendor:pdd_vendors(company_name)&order=created_at.desc",{headers}),pddAuthFetch("/rest/v1/pdd_sales_orders?select=id,so_number,deal_number,sales_total,sales_owner_name,sales_owner_email,customer_company&order=created_at.desc",{headers}),pddAuthFetch("/rest/v1/pdd_commissions?select=*&order=created_at.desc",{headers})]);if([userResponse,profileResponse,poResponse,soResponse].some(response=>response.status===401)){clearPddSession();window.location.replace("/employee-login?return_to=/employee/commissions");return}if(!userResponse.ok||!profileResponse.ok||!poResponse.ok||!soResponse.ok)throw new Error("Orders could not be loaded.");setUser(await userResponse.json() as User);setProfile((await profileResponse.json() as Profile[])[0]||null);setPurchaseOrders(await poResponse.json() as PO[]);setSalesOrders(await soResponse.json() as SO[]);if(commissionResponse.ok)setRecords(await commissionResponse.json() as Commission[])}
 useEffect(()=>{void(async()=>{const active=await currentPddSession();if(!active){window.location.replace("/employee-login?return_to=/employee/commissions");return}setSession(active);try{await load(active)}catch(error){setMessage(error instanceof Error?error.message:"Commission data could not be loaded.")}finally{setLoading(false)}})()},[]);
 const po=useMemo(()=>purchaseOrders.find(item=>item.id===poId)||null,[purchaseOrders,poId]),so=useMemo(()=>salesOrders.find(item=>item.id===soId)||null,[salesOrders,soId]);
 const calculation=useMemo(()=>{if(!po||!so)return null;const cost=Number(po.vendor_total),sale=Number(so.sales_total),shippingCost=Math.max(0,Number(shipping)||0),creditCardFee=Math.max(0,Number(ccFee)||0),profit=round(sale-cost-shippingCost-creditCardFee),base=Math.max(0,profit),buyerEmail=normalized(po.purchasing_owner_email||""),sellerEmail=normalized(so.sales_owner_email||""),buyerName=normalized(po.purchasing_owner_name||""),sellerName=normalized(so.sales_owner_name||""),same=Boolean(buyerEmail&&sellerEmail&&buyerEmail===sellerEmail||buyerName&&sellerName&&buyerName===sellerName),darrell=buyerName.includes("darrell")||buyerEmail.includes("darrell");let buyerRate=15,sellerRate=15,rule="Different buyer and salesperson — 15% each";if(same){buyerRate=30;sellerRate=0;rule="Same employee bought and sold — 30%"}else if(darrell){buyerRate=0;sellerRate=20;rule="Darrell purchased — salesperson receives 20%"}return{cost,sale,shippingCost,creditCardFee,profit,buyerRate,sellerRate,buyerCommission:round(base*buyerRate/100),sellerCommission:round(base*sellerRate/100),rule}},[po,so,shipping,ccFee]);
 async function save(){if(!session||!user||!profile||!po||!so||!calculation)return;const buyer=po.purchasing_owner_name?.trim(),seller=so.sales_owner_name?.trim();if(!buyer||buyer==="Unassigned"||!seller||seller==="Unassigned"){setMessage("Assign the vendor owner and customer salesperson before calculating commission.");return}if(Number(shipping)<0||Number(ccFee)<0){setMessage("Shipping and credit card fees cannot be negative.");return}setSaving(true);setMessage("");const record={purchase_order_id:po.id,sales_order_id:so.id,purchase_order_number:po.po_number,sales_order_number:so.so_number,buyer_name:buyer,buyer_email:po.purchasing_owner_email||"",salesperson_name:seller,salesperson_email:so.sales_owner_email||"",purchase_cost:calculation.cost,sales_total:calculation.sale,shipping_cost:calculation.shippingCost,credit_card_fee:calculation.creditCardFee,gross_profit:calculation.profit,buyer_rate:calculation.buyerRate,salesperson_rate:calculation.sellerRate,buyer_commission:calculation.buyerCommission,salesperson_commission:calculation.sellerCommission,commission_rule:calculation.rule,created_by:user.id,created_by_name:profile.display_name,created_by_email:profile.email,updated_at:new Date().toISOString()};try{const response=await pddAuthFetch("/rest/v1/pdd_commissions?on_conflict=purchase_order_id,sales_order_id",{method:"POST",headers:{Authorization:`Bearer ${session.access_token}`,Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify(record)});if(!response.ok)throw new Error("Commission record could not be saved.");const saved=(await response.json() as Commission[])[0];setRecords(current=>[saved,...current.filter(item=>item.id!==saved.id)]);setMessage(`Commission saved. Total commission: ${money.format(calculation.buyerCommission+calculation.sellerCommission)}.`)}catch(error){setMessage(error instanceof Error?error.message:"Commission record could not be saved.")}finally{setSaving(false)}}
 if(loading)return <main className="commissionsPage"><p>Loading commissions…</p></main>;
 return <main className="commissionsPage"><header><div><p className="eyebrow">DEAL WORKBOOK</p><h1>Commissions</h1><p>Match a purchase order to a sales order. Employee credit comes from the owners attached to those orders.</p></div><div className="commissionLinks"><a href="/employee/reverse-offer">Create PO</a><a href="/employee/purchase-order-upload">PO From Spreadsheet</a><a href="/employee/sales-order">Create Sales Order</a></div></header>
 <section className="commissionBuilder"><h2>Calculate commission</h2><p>Select both sides of the deal, then add any costs that reduce gross profit.</p><div className="commissionSelectors"><label>Purchase side (cost)<select value={poId} onChange={event=>setPoId(event.target.value)}><option value="">Select purchase order…</option>{purchaseOrders.map(item=><option key={item.id} value={item.id}>{item.po_number} · {item.vendor?.company_name||"Vendor"} · {money.format(Number(item.vendor_total))} · {item.purchasing_owner_name||"Unassigned"}</option>)}</select></label><label>Sales side (revenue)<select value={soId} onChange={event=>setSoId(event.target.value)}><option value="">Select sales order…</option>{salesOrders.map(item=><option key={item.id} value={item.id}>{item.so_number} · {item.customer_company} · {money.format(Number(item.sales_total))} · {item.sales_owner_name||"Unassigned"}</option>)}</select></label></div><div className="commissionFees"><label>Shipping cost ($)<input type="number" min="0" step="0.01" value={shipping} onChange={event=>setShipping(event.target.value)} placeholder="0.00"/></label><label>Credit card fee ($)<input type="number" min="0" step="0.01" value={ccFee} onChange={event=>setCcFee(event.target.value)} placeholder="0.00"/></label><small>These costs are deducted from gross profit before commissions are calculated.</small></div>{calculation&&<><div className="commissionSummary"><article><span>Purchase cost</span><strong>{money.format(calculation.cost)}</strong></article><article><span>Sales total</span><strong>{money.format(calculation.sale)}</strong></article><article><span>Shipping</span><strong>{money.format(calculation.shippingCost)}</strong></article><article><span>CC fee</span><strong>{money.format(calculation.creditCardFee)}</strong></article><article><span>Net gross profit</span><strong>{money.format(calculation.profit)}</strong></article><article><span>{po?.purchasing_owner_name||"Buyer"} ({calculation.buyerRate}%)</span><strong>{money.format(calculation.buyerCommission)}</strong></article><article><span>{so?.sales_owner_name||"Seller"} ({calculation.sellerRate}%)</span><strong>{money.format(calculation.sellerCommission)}</strong></article><article><span>Total commission</span><strong>{money.format(calculation.buyerCommission+calculation.sellerCommission)}</strong></article></div><p className={`commissionRule ${calculation.profit<=0?"warning":""}`}>{calculation.profit<=0?"No positive gross profit, so commission is $0. ":""}{calculation.rule}.</p><button className="button" disabled={saving} onClick={()=>void save()}>{saving?"Saving…":"Save Commission"}</button></>}{message&&<p className="commissionMessage">{message}</p>}</section>
 <section className="commissionHistory"><header><h2>Commission history</h2><span>{records.length} records</span></header><div className="commissionTable"><table><thead><tr><th>Orders</th><th>Buyer</th><th>Salesperson</th><th>Cost</th><th>Sale</th><th>Shipping</th><th>CC fee</th><th>Net gross profit</th><th>Buyer commission</th><th>Sales commission</th><th>Total</th><th>Rule</th></tr></thead><tbody>{records.map(item=><tr key={item.id}><td><strong>{item.purchase_order_number}</strong><small>{item.sales_order_number}</small></td><td>{item.buyer_name}</td><td>{item.salesperson_name}</td><td>{money.format(Number(item.purchase_cost))}</td><td>{money.format(Number(item.sales_total))}</td><td>{money.format(Number(item.shipping_cost||0))}</td><td>{money.format(Number(item.credit_card_fee||0))}</td><td>{money.format(Number(item.gross_profit))}</td><td>{money.format(Number(item.buyer_commission))} <small>{Number(item.buyer_rate)}%</small></td><td>{money.format(Number(item.salesperson_commission))} <small>{Number(item.salesperson_rate)}%</small></td><td className="commissionTotal">{money.format(Number(item.buyer_commission)+Number(item.salesperson_commission))}</td><td>{item.commission_rule}<small>{new Date(item.created_at).toLocaleDateString()}</small></td></tr>)}{!records.length&&<tr><td colSpan={12}>No commissions saved yet.</td></tr>}</tbody></table></div></section></main>;
}
