"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";
import {Shell} from "@/components/SiteShell";
import "../b082126-01/line-bid.css";
import "../line-bid-download.css";

type SourceRow={Brand:string;Capacity:string;Model:string;Speed:string;Quantity:string};
type BidEntry={unitBid:string;comments:string};
function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[];let cell="";let quoted=false;for(let i=0;i<text.length;i++){const char=text[i];if(quoted){if(char==='"'&&text[i+1]==='"'){cell+='"';i++}else if(char==='"')quoted=false;else cell+=char}else if(char==='"')quoted=true;else if(char===","){row.push(cell);cell=""}else if(char==="\n"){row.push(cell.replace(/\r$/,"").trim());rows.push(row);row=[];cell=""}else cell+=char}if(cell||row.length){row.push(cell.replace(/\r$/,"").trim());rows.push(row)}const headers=rows.shift()||[];return rows.filter(values=>values.some(Boolean)).map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]||""])) as SourceRow)}
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"});

export default function MemoryLineItemBid(){
 const [rows,setRows]=useState<SourceRow[]>([]);const [entries,setEntries]=useState<Record<number,BidEntry>>({});const [loading,setLoading]=useState(true);const [submitting,setSubmitting]=useState(false);const [error,setError]=useState("");const [confirmation,setConfirmation]=useState<{number:string;lines:number;units:number;total:number}|null>(null);
 useEffect(()=>{fetch("/deals/b081026-01-memory.csv").then(r=>r.text()).then(text=>setRows(parseCsv(text))).catch(()=>setError("The memory list could not be loaded.")).finally(()=>setLoading(false))},[]);
 const selected=useMemo(()=>rows.map((row,index)=>({row,index,entry:entries[index]})).filter(item=>Number(item.entry?.unitBid)>0),[rows,entries]);
 const totalUnits=useMemo(()=>selected.reduce((sum,item)=>sum+Number(item.row.Quantity),0),[selected]);
 const total=useMemo(()=>selected.reduce((sum,item)=>sum+(Number(item.row.Quantity)*Number(item.entry.unitBid)),0),[selected]);
 function update(index:number,patch:Partial<BidEntry>){setEntries(current=>({...current,[index]:{unitBid:current[index]?.unitBid||"",comments:current[index]?.comments||"",...patch}}))}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");setConfirmation(null);if(!selected.length){setError("Enter a unit offer on at least one memory line.");return}setSubmitting(true);const form=new FormData(event.currentTarget);const lineItems=selected.map(({row,index,entry})=>({lineNumber:index+1,assetId:`B081026-01-${index+1}`,brand:row.Brand,model:"Server Memory",modelNumber:row.Model,processor:row.Speed,ram:row.Capacity,hardDrive:"",condition:"",issues:"",quantity:Number(row.Quantity),unitBid:Number(entry.unitBid),comments:entry.comments}));try{const response=await fetch("/api/line-item-bids",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({dealNumber:"B081026-01",company:form.get("company"),contactName:form.get("contact"),email:form.get("email"),phone:form.get("phone"),customerNotes:form.get("notes"),lineItems})});const data=await response.json();if(!response.ok)throw new Error(data.error||"The offer could not be submitted.");setConfirmation({number:data.internalBidNumber,lines:data.lineCount,units:data.totalQuantity,total:data.totalBid});window.scrollTo({top:0,behavior:"smooth"})}catch(reason){setError(reason instanceof Error?reason.message:"The offer could not be submitted.")}finally{setSubmitting(false)}}
 return <Shell><main className="lineBid"><section className="lineBidHero"><div className="lineBidHeroNav"><a href="/public-deal-desk">← Back to Public Deal Desk</a><a className="lineBidDownload" href="/deals/B081026-01-Public-Inventory.xlsx" download>Download Excel</a></div><p>LINE-ITEM OFFER ENTRY</p><h1>B081026-01</h1><h2>435-Piece DDR5 Server Memory Offering</h2><div><span>Open for offers</span><span>Bid on any or all line items</span><span>No asking prices published</span></div></section>
 {confirmation&&<section className="bidConfirmation"><strong>Internal offer generated</strong><h2>{confirmation.number}</h2><p>{confirmation.lines} line items · {confirmation.units} units · {money.format(confirmation.total)} total</p><p>Please save this confirmation number. Mac2MacOnline will contact you after offers are reviewed.</p></section>}
 <form className="lineBidForm" onSubmit={submit}><section className="bidderPanel"><div><h2>Buyer information</h2><p>Your offer remains confidential.</p></div><label>Company<input required name="company"/></label><label>Contact name<input required name="contact"/></label><label>Email<input required type="email" name="email"/></label><label>Phone<input required name="phone" inputMode="tel"/></label><label className="wide">General offer notes<textarea name="notes" rows={3} placeholder="Shipping timing, payment terms or overall conditions"/></label></section>
 <section className="bidSummary"><div><span>Lines selected</span><strong>{selected.length}</strong></div><div><span>Total units</span><strong>{totalUnits}</strong></div><div><span>Total offer</span><strong>{money.format(total)}</strong></div><button disabled={submitting||!selected.length}>{submitting?"Generating internal offer…":"Submit Line-Item Offer"}</button></section>
 {error&&<p className="lineBidError">{error}</p>}
 <section className="lineItems"><div className="lineItemsHeading"><div><h2>Memory inventory</h2><p>Each line is take-all. Enter a unit offer to bid on the full available quantity shown for that line.</p></div><div className="lineItemsTools"><strong>{loading?"Loading…":`${rows.length} line items · 435 modules`}</strong><a className="lineItemsDownload" href="/deals/B081026-01-Public-Inventory.xlsx" download>Download Excel</a></div></div><div className="lineTableWrap"><table><thead><tr><th>Line</th><th>Brand</th><th>Capacity</th><th>Model</th><th>Speed</th><th>Take-All Qty</th><th>Your Unit Offer</th><th>Comments</th></tr></thead><tbody>{rows.map((row,index)=><tr className={Number(entries[index]?.unitBid)>0?"hasBid":""} key={`${row.Model}-${index}`}><td>{index+1}</td><td><b>{row.Brand}</b></td><td>{row.Capacity}</td><td><b>{row.Model}</b></td><td>{row.Speed}</td><td><b>{Number(row.Quantity)}</b></td><td><div className="priceInput"><span>$</span><input aria-label={`Unit offer for line ${index+1}`} type="number" min="0.01" step="0.01" value={entries[index]?.unitBid||""} onChange={e=>update(index,{unitBid:e.target.value})}/></div></td><td><input aria-label={`Comments for line ${index+1}`} value={entries[index]?.comments||""} onChange={e=>update(index,{comments:e.target.value})} placeholder="Optional"/></td></tr>)}</tbody></table></div></section>
 <section className="bidSubmitBar"><div><span>{selected.length} lines · {totalUnits} units</span><strong>{money.format(total)}</strong></div><button disabled={submitting||!selected.length}>{submitting?"Generating internal offer…":"Submit Line-Item Offer"}</button></section></form></main></Shell>
}
