"use client";
import { useEffect, useMemo, useState } from "react";
import { clearPddSession, currentPddSession, pddAuthFetch, type PddSession } from "../../../lib/pdd-auth";
import "./finalize-deal.css";

type Deal={id:string;deal_number:string;title:string;status:string;direction:string;vendor_name:string};
type Bid={internal_bid_number:string;deal_number:string;company:string;total_bid:number;status:"submitted"|"won"|"lost"};
type Estimate={deal_number:string;proposed_amount:number};
type Order={id:string;number:string;status:string;pdf:string|null};
type Finalization={vendor_accepted:number;vendor_accepted_by:string;vendor_accepted_at:string|null;customer_email_sent_to:string;customer_email_sent_at:string|null;vendor_email_sent_to:string;vendor_email_sent_at:string|null;terms_conditions:string;finalized_by:string;finalized_at:string|null};
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"});

export default function FinalizeDeal(){
  const [session,setSession]=useState<PddSession|null>(null),[deals,setDeals]=useState<Deal[]>([]),[allBids,setAllBids]=useState<Bid[]>([]),[estimates,setEstimates]=useState<Estimate[]>([]),[selected,setSelected]=useState(""),[orders,setOrders]=useState<{so:Order|null;po:Order|null}>({so:null,po:null}),[finalization,setFinalization]=useState<Finalization|null>(null),[terms,setTerms]=useState(""),[message,setMessage]=useState("Loading deal workflow…"),[busy,setBusy]=useState("");
  useEffect(()=>{void(async()=>{const active=await currentPddSession();if(!active){window.location.replace("/employee-login?return_to=/employee/finalize-deal");return}setSession(active);const headers={Authorization:`Bearer ${active.access_token}`};const [dealResponse,bidResponse]=await Promise.all([fetch("/api/admin/deals",{headers}),fetch("/api/admin/bids",{headers})]);if(dealResponse.status===401||bidResponse.status===401){clearPddSession();window.location.replace("/employee-login?return_to=/employee/finalize-deal");return}if(!dealResponse.ok||!bidResponse.ok){setMessage("Deals could not be loaded.");return}const dealData=await dealResponse.json(),bidData=await bidResponse.json(),offeredDeals=new Set<string>(bidData.dealNumbersWithOffers||[]),params=new URLSearchParams(window.location.search);const list=(dealData.deals||[]).filter((deal:Deal)=>deal.direction!=="buying"&&!deal.deal_number.startsWith("WTB")&&offeredDeals.has(deal.deal_number));setDeals(list);setAllBids(bidData.bids||[]);setEstimates(dealData.estimates||[]);const requested=params.get("deal")?.toUpperCase();setSelected(list.some((deal:Deal)=>deal.deal_number===requested)?requested:"");setMessage(params.get("email")==="vendor"?"Vendor email sent.":params.get("email")==="customer"?"Customer email sent.":list.length?"":"No LBB deals currently have customer offers.")})()},[]);
  async function refresh(deal=selected){if(!session||!deal)return;const headers={Authorization:`Bearer ${session.access_token}`};const [stateResponse,soResponse,poResponse,bidResponse]=await Promise.all([fetch(`/api/admin/finalization?deal=${encodeURIComponent(deal)}`,{headers}),pddAuthFetch(`/rest/v1/pdd_sales_orders?deal_number=eq.${encodeURIComponent(deal)}&select=id,so_number,order_status,pdf_storage_path&limit=1`,{headers}),pddAuthFetch(`/rest/v1/pdd_purchase_orders?deal_number=eq.${encodeURIComponent(deal)}&select=id,po_number,order_status,pdf_storage_path&limit=1`,{headers}),fetch(`/api/admin/bids?deal=${encodeURIComponent(deal)}`,{headers})]);const stateData=stateResponse.ok?await stateResponse.json():{};const sales=soResponse.ok?await soResponse.json():[],purchases=poResponse.ok?await poResponse.json():[];if(bidResponse.ok){const bidData=await bidResponse.json();setAllBids(current=>[...current.filter(item=>item.deal_number!==deal),...(bidData.bids||[])])}setFinalization(stateData.finalization||null);setTerms(stateData.finalization?.terms_conditions||stateData.defaultTerms||"");setOrders({so:sales[0]?{id:sales[0].id,number:sales[0].so_number,status:sales[0].order_status,pdf:sales[0].pdf_storage_path}:null,po:purchases[0]?{id:purchases[0].id,number:purchases[0].po_number,status:purchases[0].order_status,pdf:purchases[0].pdf_storage_path}:null})}
  useEffect(()=>{if(selected)void refresh(selected)},[selected,session]);
  const deal=deals.find(item=>item.deal_number===selected),bids=useMemo(()=>allBids.filter(item=>item.deal_number===selected).sort((a,b)=>b.total_bid-a.total_bid),[allBids,selected]),highest=bids[0],winner=bids.find(item=>item.status==="won"),offer=estimates.find(item=>item.deal_number===selected)?.proposed_amount,accepted=Boolean(finalization?.vendor_accepted),customerSent=Boolean(finalization?.customer_email_sent_at),vendorSent=Boolean(finalization?.vendor_email_sent_at),done=Boolean(finalization?.finalized_at);
  async function action(name:string,extra:Record<string,string>={}){if(!session||!selected)return;setBusy(name);setMessage("");try{const response=await fetch("/api/admin/finalization",{method:"POST",headers:{Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({action:name,dealNumber:selected,...extra})});const data=await response.json();if(!response.ok)throw new Error(data.error||"This step could not be completed.");setFinalization(data.finalization);if(name==="finalize"){window.location.assign("/employee/active-bids");return}setMessage(name==="send_customer"?"Customer email sent.":name==="send_vendor"?"Vendor email sent.":"Step completed successfully.");await refresh()}catch(error){setMessage(error instanceof Error?error.message:"This step could not be completed.")}finally{setBusy("")}}
  async function award(){if(!session||!highest)return;setBusy("award");const response=await fetch("/api/admin/bids",{method:"PATCH",headers:{Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({bidNumber:highest.internal_bid_number,status:"won"})});const data=await response.json();setBusy("");if(!response.ok){setMessage(data.error||"The customer could not be awarded.");return}setMessage(`${highest.company} was awarded the deal.`);await refresh()}
  const steps=[
    {title:"Deal posted on the LBB",complete:Boolean(deal),body:deal?`${deal.deal_number} · ${deal.title}`:"Select a deal to begin.",action:null},
    {title:"Customer offers received",complete:bids.length>0,body:bids.length?`${bids.length} offer${bids.length===1?"":"s"}; highest is ${highest.company} at ${money.format(highest.total_bid)}.`:"No customer offers have been received yet.",action:null},
    {title:"Offer made to vendor",complete:offer!==undefined,body:offer!==undefined?`Recorded vendor offer: ${money.format(offer)}. Highest customer bid: ${highest?money.format(highest.total_bid):"not available"}.`:"Prepare and record the vendor offer based on the highest customer bid.",action:<a className="button" href={`/employee/vendor-bid?deal=${encodeURIComponent(selected)}`}>Prepare Vendor Offer</a>},
    {title:"Vendor accepts our offer",complete:accepted,body:accepted?`Accepted${finalization?.vendor_accepted_by?` and recorded by ${finalization.vendor_accepted_by}`:""}.`:"Confirm acceptance only after the vendor has agreed to our offer.",action:offer!==undefined&&!accepted?<button className="button" onClick={()=>void action("vendor_accepted")} disabled={Boolean(busy)}>{busy==="vendor_accepted"?"Recording…":"Confirm Vendor Acceptance"}</button>:null},
    {title:"Award customer and send sales order",complete:customerSent,body:customerSent?`Award email sent to ${finalization?.customer_email_sent_to}.`:winner?`${winner.company} is awarded. ${orders.so?`${orders.so.number} is ready.`:"Create the sales order next."}`:"Award the highest customer offer after vendor acceptance.",action:accepted&&!winner&&highest?<button className="button" onClick={()=>void award()} disabled={Boolean(busy)}>{busy==="award"?"Awarding…":`Award ${highest.company}`}</button>:winner&&!orders.so?<a className="button" href={`/employee/sales-order?bid=${encodeURIComponent(winner.internal_bid_number)}`}>Create Sales Order</a>:orders.so&&!customerSent?<button className="button" onClick={()=>void action("send_customer")} disabled={Boolean(busy)}>{busy==="send_customer"?"Sending…":"Email Award + Sales Order"}</button>:null},
    {title:"Send purchase order to vendor",complete:vendorSent,body:vendorSent?`Award email, purchase order, and terms sent to ${finalization?.vendor_email_sent_to}.`:orders.po?`${orders.po.number} is ready to send with the terms below.`:"Create the purchase order after awarding the customer.",action:winner&&!orders.po?<a className="button" href={`/employee/reverse-offer?bid=${encodeURIComponent(winner.internal_bid_number)}`}>Create Purchase Order</a>:orders.po&&!vendorSent?<><textarea value={terms} onChange={event=>setTerms(event.target.value)} rows={5} aria-label="Vendor terms and conditions"/><button className="button" onClick={()=>void action("send_vendor",{terms})} disabled={Boolean(busy)||!terms.trim()}>{busy==="send_vendor"?"Sending…":"Email Award + PO + Terms"}</button></>:null},
    {title:"Place both orders in final status",complete:done,body:done?`Sales order and proforma purchase order are Awarded — Pending Fulfillment.`:"Once both award emails are sent, place both orders into Awarded — Pending Fulfillment.",action:customerSent&&vendorSent&&!done?<button className="button" onClick={()=>void action("finalize")} disabled={Boolean(busy)}>{busy==="finalize"?"Finalizing…":"Finalize Both Orders"}</button>:null}
  ];
  return <main className="finalizeDealPage"><header><div><p className="eyebrow">DEAL WORKFLOW</p><h1>Deal Finalization</h1><p>Follow each step to turn a customer bid and vendor acceptance into awarded orders.</p></div><a className="button secondary" href="/employee">← Deal Workbook</a></header><section className="finalizeChooser"><label>Deal to finalize<select value={selected} onChange={event=>setSelected(event.target.value)} disabled={!deals.length}><option value="">{deals.length?"Select a deal with offers":"No deals with offers"}</option>{deals.map(item=><option key={item.id} value={item.deal_number}>{item.deal_number} — {item.title}</option>)}</select></label>{deal&&<div><b>{deal.vendor_name}</b><span>Vendor</span></div>}</section>{message&&<p className="finalizeMessage">{message}</p>}<section className="finalizeSteps">{steps.map((step,index)=><article key={step.title} className={step.complete?"complete":""}><div className="stepNumber">{step.complete?"✓":index+1}</div><div><span>STEP {index+1}</span><h2>{step.title}</h2><p>{step.body}</p>{step.action&&<div className="stepAction">{step.action}</div>}</div></article>)}</section></main>
}
