"use client";
import {FormEvent,useEffect,useState} from "react";
import {clearPddSession,currentPddSession,pddSupabaseKey,pddSupabaseUrl,type PddSession} from "../../../lib/pdd-auth";

type Employee={display_name:string;email:string;role:"administrator"|"employee";active:boolean;account_created:boolean;account_created_at:string|null;last_sign_in_at:string|null;invited_at:string|null};
function date(value:string|null){return value?new Date(value).toLocaleString():"—"}
export default function EmployeeAccess(){
 const [session,setSession]=useState<PddSession|null>(null),[employees,setEmployees]=useState<Employee[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[busy,setBusy]=useState(""),[currentEmail,setCurrentEmail]=useState("");
 const [name,setName]=useState(""),[email,setEmail]=useState(""),[role,setRole]=useState<"employee"|"administrator">("employee");
 async function call(active:PddSession,init?:RequestInit){const headers=new Headers(init?.headers);headers.set("apikey",pddSupabaseKey);headers.set("Authorization",`Bearer ${active.access_token}`);headers.set("Content-Type","application/json");const response=await fetch(`${pddSupabaseUrl}/functions/v1/admin-pdd-employees`,{...init,headers});const data=await response.json();if(response.status===401){clearPddSession();window.location.replace("/employee-login?return_to=/employee/access");throw new Error("Session expired.")}if(!response.ok)throw new Error(data.error||"Employee access could not be updated.");setEmployees(data.employees||[]);setCurrentEmail(data.currentEmail||"");return data}
 useEffect(()=>{void(async()=>{try{const active=await currentPddSession();if(!active){window.location.replace("/employee-login?return_to=/employee/access");return}setSession(active);await call(active)}catch(error){setMessage(error instanceof Error?error.message:"Employee access could not be loaded.")}finally{setLoading(false)}})()},[]);
 async function add(event:FormEvent){event.preventDefault();if(!session)return;setBusy("add");setMessage("");try{await call(session,{method:"POST",body:JSON.stringify({action:"add",displayName:name,email,role})});setName("");setEmail("");setRole("employee");setMessage("Employee approved. They can now activate their account.")}catch(error){setMessage(error instanceof Error?error.message:"Employee could not be added.")}finally{setBusy("")}}
 async function update(item:Employee,changes:{role?:Employee["role"];active?:boolean}){if(!session)return;setBusy(item.email);setMessage("");try{await call(session,{method:"POST",body:JSON.stringify({action:"update",email:item.email,...changes})});setMessage("Employee access updated.")}catch(error){setMessage(error instanceof Error?error.message:"Employee could not be updated.")}finally{setBusy("")}}
 return <main className="accessPage"><header><div><p className="eyebrow">ADMINISTRATOR</p><h1>Employee Access</h1><p>Approve employees, assign roles and see who has activated an account.</p></div><nav><a href="/employee">← Deal Workbook</a><a href="/employee/deals">Manage Deals</a></nav></header>
 <section className="accessSummary"><article><b>{employees.length}</b><span>Approved people</span></article><article><b>{employees.filter(item=>item.account_created).length}</b><span>Accounts created</span></article><article><b>{employees.filter(item=>item.active).length}</b><span>Active access</span></article><article><b>{employees.filter(item=>item.role==="administrator"&&item.active).length}</b><span>Administrators</span></article></section>
 <section className="accessAdd"><div><p className="eyebrow">ADD EMPLOYEE</p><h2>Approve a new person</h2><p>They will use “Activate an approved account” on the Employee Login page.</p></div><form onSubmit={add}><label>Full name<input value={name} onChange={event=>setName(event.target.value)} placeholder="First and last name" required/></label><label>Email address<input type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="name@mac2maconline.com" required/></label><label>Role<select value={role} onChange={event=>setRole(event.target.value as typeof role)}><option value="employee">Employee</option><option value="administrator">Administrator</option></select></label><button disabled={busy==="add"}>{busy==="add"?"Adding…":"Approve Employee"}</button></form></section>
 {message&&<p className="accessMessage" role="status">{message}</p>}
 <section className="accessList"><div className="accessListHeading"><div><p className="eyebrow">APPROVED ACCESS</p><h2>Employee accounts</h2></div><span>{employees.filter(item=>item.account_created).length} of {employees.length} activated</span></div>{loading?<p className="accessLoading">Loading employee accounts…</p>:employees.map(item=><article className={`accessRow ${item.active?"":"inactive"}`} key={item.email}><div className="accessPerson"><span className="accessInitials">{item.display_name.split(/\s+/).filter(Boolean).map(word=>word[0]).slice(0,2).join("").toUpperCase()}</span><div><h3>{item.display_name}</h3><p>{item.email}</p></div></div><div className="accessStatus"><b className={item.account_created?"created":"pending"}>{item.account_created?"Account created":"Awaiting activation"}</b><small>Created: {date(item.account_created_at)}</small><small>Last sign-in: {date(item.last_sign_in_at)}</small></div><label className="accessRole">Role<select aria-label={`Role for ${item.display_name}`} value={item.role} disabled={busy===item.email||item.email===currentEmail} onChange={event=>update(item,{role:event.target.value as Employee["role"]})}><option value="employee">Employee</option><option value="administrator">Administrator</option></select></label><label className="accessToggle"><input type="checkbox" checked={item.active} disabled={busy===item.email||item.email===currentEmail} onChange={event=>update(item,{active:event.target.checked})}/><span>{item.active?"Active":"Inactive"}</span></label></article>)}</section></main>
}
