"use client";
import {useEffect,useState} from "react";
import {clearPddSession,currentPddSession,pddAuthFetch} from "../../lib/pdd-auth";
import {Shell} from "../../components/SiteShell";
type Profile={email:string;display_name:string;role:"administrator"|"employee"};
export default function EmployeeDashboard(){
 const [profile,setProfile]=useState<Profile|null>(null);const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const session=await currentPddSession();if(!session){window.location.replace("/employee-login");return}const response=await pddAuthFetch("/rest/v1/pdd_employee_access?select=email,display_name,role",{headers:{Authorization:`Bearer ${session.access_token}`}});if(!response.ok){clearPddSession();window.location.replace("/employee-login");return}const rows=await response.json() as Profile[];if(!rows[0]){clearPddSession();window.location.replace("/employee-login");return}setProfile(rows[0]);setLoading(false)})()},[]);
 function signOut(){clearPddSession();window.location.assign("/employee-login")}
 if(loading)return <Shell><main className="employeeDashboard"><p>Loading your Deal Desk…</p></main></Shell>;
 return <Shell><main className="employeeDashboard"><header><div><p className="eyebrow">M2M DEAL WORKBOOK</p><h1>Welcome, {profile?.display_name}</h1><p>{profile?.email} · {profile?.role==="administrator"?"Administrator":"Employee"}</p></div><button className="button secondary" onClick={signOut}>Sign out</button></header><section className="employeeDashboardGrid groupedDashboard">
 <article><span>DEALS</span><h2>Deal workflow</h2><p>Upload, continue and manage customer bidding opportunities.</p><div className="workbookActionList"><a href="/public-deal-desk/deal-builder?new=1">Upload New Deal <b>→</b></a><a href="/public-deal-desk/deal-builder">Continue Last Deal <b>→</b></a><a href="/employee/deals">Manage Deals &amp; Awards <b>→</b></a></div></article>
 <article><span>SALES</span><h2>Customer sales</h2><p>Record customer offers, create sales orders and review sales history.</p><div className="workbookActionList"><a href="/employee/customer-bid">Submit Customer Bid <b>→</b></a><a href="/employee/sales-order">Create Sales Order <b>→</b></a><a href="/employee/orders?type=sales">Sales Order History <b>→</b></a></div></article>
 <article><span>PURCHASING</span><h2>Vendor purchasing</h2><p>Create vendor purchase orders and manage vendor purchasing records.</p><div className="workbookActionList"><a href="/employee/reverse-offer">PO From Winning Offer <b>→</b></a><a href="/employee/purchase-order-upload">PO From Spreadsheet <b>→</b></a><a href="/employee/orders?type=purchase">Purchase Order History <b>→</b></a><a href="/employee/contacts?type=vendors">Vendor Directory <b>→</b></a></div></article>
 <article><span>RECORDS &amp; REPORTS</span><h2>Business records</h2><p>Find contacts, review all orders and report by employee, product or SKU.</p><div className="workbookActionList"><a href="/employee/orders">All Order History <b>→</b></a><a href="/employee/contacts">Vendors &amp; Customers <b>→</b></a><a href="/employee/reports">Purchasing &amp; Sales Reports <b>→</b></a></div></article>
 <article><span>COMMISSIONS</span><h2>Commission tracking</h2><p>Match purchase orders to sales orders and calculate employee commissions from gross profit.</p><div className="workbookActionList"><a href="/employee/commissions">Calculate Commissions <b>→</b></a><a href="/employee/reverse-offer">Create Purchase Order <b>→</b></a><a href="/employee/sales-order">Create Sales Order <b>→</b></a></div></article>
 <article><span>CONTRACT TARGETS</span><h2>Prospect directory</h2><p>Build relationships with end users, universities, medical organizations and government contractors.</p><div className="workbookActionList"><a href="/employee/end-user-customers">Open Contract Targets <b>→</b></a></div></article>
 {profile?.role==="administrator"&&<article className="administrationCard"><span>ADMINISTRATION</span><h2>Employee access</h2><p>Approve employees, manage roles and control active access.</p><div className="workbookActionList"><a href="/employee/access">Manage Employee Access <b>→</b></a></div></article>}
 </section></main></Shell>;
}
