"use client";

import {FormEvent,useEffect,useMemo,useRef,useState} from "react";
import {Shell} from "@/components/SiteShell";
import {downloadBidSpreadsheet,readBidSpreadsheet} from "@/lib/bidSpreadsheet";
import {currentCustomerSession} from "@/lib/customer-auth";
import type {PddSession} from "@/lib/pdd-auth";
import InternationalPhoneField from "@/components/InternationalPhoneField";
import BidderAddressFields from "@/components/BidderAddressFields";
import "../line-bid.css";
import "../line-bid-download.css";
import "../line-item-totals.css";
import "../bidder-fields.css";
import "../bidder-tighter.css";

type PublicLine={line:number;quantity:number;values:Record<string,string>};
type Deal={deal_number:string;title:string;description:string;quantity:number;closes_at:string;location:string;public_lines:PublicLine[];spreadsheet_filename:string};
type BidEntry={unitBid:string;comments:string};
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"});

export default function DynamicLineItemBid(){
 const autoDownloaded=useRef(false);const [deal,setDeal]=useState<Deal|null>(null);const [entries,setEntries]=useState<Record<number,BidEntry>>({});const [loading,setLoading]=useState(true);const [submitting,setSubmitting]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [confirmation,setConfirmation]=useState<{number:string;lines:number;total:number}|null>(null);const [customerSession,setCustomerSession]=useState<PddSession|null>(null);const [profile,setProfile]=useState<Record<string,string>>({});const [editProfile,setEditProfile]=useState(false);
 useEffect(()=>{const dealNumber=decodeURIComponent(window.location.pathname.split("/").filter(Boolean).pop()||"").toUpperCase();fetch(`/api/deals/${encodeURIComponent(dealNumber)}`).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||"This deal could not be opened.");setDeal(data.deal)}).catch(reason=>setError(reason instanceof Error?reason.message:"This deal could not be opened.")).finally(()=>setLoading(false))},[]);
 useEffect(()=>{(async()=>{const session=await currentCustomerSession();if(!session)return;setCustomerSession(session);let local:Record<string,string>={};try{local=JSON.parse(localStorage.getItem("m2m-pdd-customer-profile")||"{}") as Record<string,string>;if(Object.keys(local).length)setProfile(local)}catch{}const response=await fetch("/api/customer/profile",{headers:{Authorization:`Bearer ${session.access_token}`}});if(response.ok){const data=await response.json();const remote=(data.profile||{}) as Record<string,string>;const merged={...local,...Object.fromEntries(Object.entries(remote).filter(([,value])=>Boolean(value)))};setProfile(merged);if(Object.keys(merged).length)localStorage.setItem("m2m-pdd-customer-profile",JSON.stringify(merged))}})()},[]);
 const lines=deal?.public_lines||[];const headers=useMemo(()=>[...new Set(lines.flatMap(line=>Object.keys(line.values)))],[lines]);const lots=useMemo(()=>{const grouped=new Map<string,number[]>();lines.forEach((line,index)=>{const name=line.values["Source Tab"]||"All Items";grouped.set(name,[...(grouped.get(name)||[]),index])});return [...grouped.entries()]},[lines]);
 const selected=useMemo(()=>lines.map((line,index)=>({line,index,entry:entries[index]})).filter(item=>Number(item.entry?.unitBid)>0),[lines,entries]);
 const profileComplete=Boolean(profile.company&&profile.contact_name&&profile.email&&profile.phone&&profile.address1&&profile.city&&profile.region&&profile.postal_code&&profile.country);
 const total=selected.reduce((sum,item)=>sum+(item.line.quantity*Number(item.entry.unitBid)),0);const totalQty=selected.reduce((sum,item)=>sum+item.line.quantity,0);
 function update(index:number,patch:Partial<BidEntry>){setEntries(current=>({...current,[index]:{unitBid:current[index]?.unitBid||"",comments:current[index]?.comments||"",...patch}}))}
 function downloadSheet(){if(!deal)return;downloadBidSpreadsheet(deal.deal_number,lines.length,[...headers.map(header=>({header,value:(index:number)=>lines[index].values[header]||""})),{header:"Qty",value:(index:number)=>lines[index].quantity}],deal.spreadsheet_filename)}
 useEffect(()=>{if(deal&&!autoDownloaded.current&&new URLSearchParams(window.location.search).get("download")==="1"){autoDownloaded.current=true;downloadSheet()}},[deal]);
 async function importSheet(file:File){if(!deal)return;setError("");setNotice("");try{const imported=await readBidSpreadsheet(file);const next:Record<number,BidEntry>={};let priced=0;for(const item of imported){const numericId=/^\d+$/.test(item.lineId),legacyId=item.lineId.startsWith(`${deal.deal_number}-`),index=(numericId?Number(item.lineId):legacyId?Number(item.lineId.slice(deal.deal_number.length+1)):0)-1;if((!numericId&&!legacyId)||!Number.isInteger(index)||index<0||index>=lines.length){if(Number(item.unitBid)>0)throw new Error(`Line ${item.lineId||"(blank)"} was not found.`);continue}if(Number(item.unitBid)>0){next[index]={unitBid:item.unitBid,comments:item.comments};priced++}}if(!priced)throw new Error("No positive Unit Bid amounts were found in the spreadsheet.");setEntries(next);setNotice(`${priced} spreadsheet bids were placed into their matching lines. Review and submit below.`)}catch(reason){setError(reason instanceof Error?reason.message:"The spreadsheet could not be imported.")}}
 async function saveBidderProfile(form:HTMLFormElement){if(!customerSession)return;setError("");const data=new FormData(form);const bidder={company:String(data.get("company")||""),contactName:String(data.get("contact")||""),email:String(data.get("email")||""),phone:String(data.get("phone")||""),address1:String(data.get("address1")||""),address2:String(data.get("address2")||""),city:String(data.get("city")||""),region:String(data.get("region")||""),postalCode:String(data.get("postalCode")||""),country:String(data.get("country")||"")};if(!bidder.company||!bidder.contactName||!bidder.email||!bidder.phone||!bidder.address1||!bidder.city||!bidder.region||!bidder.postalCode||!bidder.country){setError("Complete all required bidder information before saving.");return}const saved={company:bidder.company,contact_name:bidder.contactName,email:bidder.email,phone:bidder.phone,address1:bidder.address1,address2:bidder.address2,city:bidder.city,region:bidder.region,postal_code:bidder.postalCode,country:bidder.country};setProfile(saved);localStorage.setItem("m2m-pdd-customer-profile",JSON.stringify(saved));setEditProfile(false);setNotice("Your bidder information is saved and will be used for future bids.");try{await fetch("/api/customer/profile",{method:"PUT",headers:{"Content-Type":"application/json",Authorization:`Bearer ${customerSession.access_token}`},body:JSON.stringify(bidder)})}catch{/* The locally saved profile remains available while remote sync recovers. */}}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!deal||!selected.length)return;setSubmitting(true);setError("");const form=new FormData(event.currentTarget);const bidder={company:form.get("company"),contactName:form.get("contact"),email:form.get("email"),phone:form.get("phone"),address1:form.get("address1"),address2:form.get("address2"),city:form.get("city"),region:form.get("region"),postalCode:form.get("postalCode"),country:form.get("country")};const lineItems=selected.map(({line,entry})=>({lineNumber:line.line,assetId:"",brand:line.values.MFG||line.values.Manufacturer||"",model:line.values.Model||"",modelNumber:line.values["Model Number"]||line.values["Part Number"]||"",processor:line.values.CPU||line.values.Processor||"",ram:line.values.RAM||"",hardDrive:line.values.Storage||line.values["Hard Drive"]||"",condition:line.values.Condition||line.values["Grading Description"]||"",issues:Object.entries(line.values).map(([key,value])=>`${key}: ${value}`).join(" · "),quantity:line.quantity,unitBid:Number(entry.unitBid),comments:entry.comments}));try{const headers:Record<string,string>={"Content-Type":"application/json"};if(customerSession)headers.Authorization=`Bearer ${customerSession.access_token}`;const response=await fetch("/api/line-item-bids",{method:"POST",headers,body:JSON.stringify({dealNumber:deal.deal_number,...bidder,customerNotes:form.get("notes"),lineItems})});const data=await response.json();if(!response.ok)throw new Error(data.error||"The bid could not be submitted.");if(customerSession)await fetch("/api/customer/profile",{method:"PUT",headers,body:JSON.stringify(bidder)});setConfirmation({number:data.internalBidNumber,lines:data.lineCount,total:data.totalBid});window.scrollTo({top:0,behavior:"smooth"})}catch(reason){setError(reason instanceof Error?reason.message:"The bid could not be submitted.")}finally{setSubmitting(false)}}
 if(loading)return <Shell><main className="lineBid"><p className="lineBidError">Opening deal…</p></main></Shell>;
 if(!deal)return <Shell><main className="lineBid"><p className="lineBidError">{error||"This deal is not open."}</p></main></Shell>;
 return <Shell><main className="lineBid"><section className="lineBidHero"><div className="lineBidHeroNav"><a href="/public-deal-desk">← Back to Public Deal Desk</a><button className="lineBidDownload" type="button" onClick={downloadSheet}>Download Bid Excel</button></div><p>LINE-ITEM BID ENTRY</p><h1>{deal.deal_number}</h1><h2>{deal.title}</h2><div><span>Closes {new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit",timeZone:"America/Los_Angeles",timeZoneName:"short"}).format(new Date(deal.closes_at))}</span><span>{deal.quantity.toLocaleString()} total items</span><span>No asking prices published</span></div></section>
 {confirmation&&<section className="bidConfirmation"><strong>Internal bid generated</strong><h2>{confirmation.number}</h2><p>{confirmation.lines} line items · {money.format(confirmation.total)} total</p><p>Please save this confirmation number. Mac2MacOnline will contact you after bids are reviewed.</p></section>}
 <form className="lineBidForm" onSubmit={submit}><section className={`bidderPanel ${customerSession&&profileComplete&&!editProfile?"savedProfilePanel":""}`}><div className="bidderIntro"><h2>Bidder information</h2>{customerSession?<p>Signed in · <a href="/my-bids">View My Bids</a></p>:<><p>You may bid as a visitor or create an account to save your information and track results.</p><div className="bidderAccountActions"><a href="/customer-login">Create Customer Account</a><span>or continue below as a visitor</span></div></>}</div>{customerSession&&profileComplete&&!editProfile?<><div className="savedBidder"><span>Submitting as</span><strong>{profile.company}</strong><p>{profile.contact_name} · {profile.email} · {profile.phone}</p><p>{profile.address1}{profile.address2?`, ${profile.address2}`:""} · {profile.city}, {profile.region} {profile.postal_code} · {profile.country}</p><button type="button" onClick={()=>setEditProfile(true)}>Edit information</button></div><input type="hidden" name="company" value={profile.company}/><input type="hidden" name="contact" value={profile.contact_name}/><input type="hidden" name="email" value={profile.email}/><input type="hidden" name="phone" value={profile.phone}/><input type="hidden" name="address1" value={profile.address1}/><input type="hidden" name="address2" value={profile.address2||""}/><input type="hidden" name="city" value={profile.city}/><input type="hidden" name="region" value={profile.region}/><input type="hidden" name="postalCode" value={profile.postal_code}/><input type="hidden" name="country" value={profile.country}/></>:<><label>Company<input required name="company" defaultValue={profile.company||""}/></label><label>Contact name<input required name="contact" defaultValue={profile.contact_name||""}/></label><label>Email<input required type="email" name="email" defaultValue={profile.email||customerSession?.user?.email||""}/></label><InternationalPhoneField required name="phone" initialValue={profile.phone||""}/><BidderAddressFields profile={profile}/></>}<label className="wide">General bid notes<textarea name="notes" rows={3}/></label></section>
 {(!profileComplete||editProfile)&&<div className="saveBidderRow"><button type="button" onClick={event=>{if(!customerSession){window.location.assign("/customer-login");return}if(event.currentTarget.form)void saveBidderProfile(event.currentTarget.form)}}>Save Bidder Information</button><span>{customerSession?"Save once to hide these fields on future bids.":"Sign in to save these details, or continue bidding as a visitor."}</span></div>}
 <section className="bidMethod"><div><span>OPTION 1</span><h2>Enter bids online</h2><p>Type a unit bid directly into any line below.</p></div><div><span>OPTION 2</span><h2>Use the Excel bid sheet</h2><p>Download the spreadsheet, enter only Unit Bid and Bid Comments, then upload it here.</p><div className="sheetActions"><button type="button" onClick={downloadSheet}>Download Bid Spreadsheet</button><label>Upload Completed Spreadsheet<input type="file" accept=".xls,.xlsx,.xml,.csv" onChange={event=>{const file=event.target.files?.[0];if(file)void importSheet(file);event.currentTarget.value=""}}/></label></div></div></section>
 {notice&&<p className="sheetImportNotice">{notice}</p>}<section className="bidSummary"><div><span>Lines bid</span><strong>{selected.length}</strong></div><div><span>Total units</span><strong>{totalQty}</strong></div><div><span>Grand total</span><strong>{money.format(total)}</strong></div><button disabled={submitting||!selected.length}>{submitting?"Generating internal bid…":"Submit Line-Item Bid"}</button></section>{error&&<p className="lineBidError">{error}</p>}
 <section className="lineItems"><div className="lineItemsHeading"><div><h2>Enter your unit price by line</h2><p>The blue Unit Bid box is next to each quantity. Leave it blank for lines you do not want.</p></div><strong>{lines.length} quantified lines</strong></div><div className="lineTableWrap"><table className="pricingTable"><thead><tr><th>Line</th>{headers.map(header=><th key={header}>{header}</th>)}<th>Bid Comments</th><th className="bidSticky bidQty">Qty</th><th className="bidSticky bidPrice">Unit Bid</th><th className="bidSticky bidTotal">Line Total</th></tr></thead><tbody>{lines.map((line,index)=><tr className={Number(entries[index]?.unitBid)>0?"hasBid":""} key={line.line}><td>{line.line}</td>{headers.map(header=><td className="detailCell" title={line.values[header]||""} key={header}>{line.values[header]||"—"}</td>)}<td><input value={entries[index]?.comments||""} onChange={event=>update(index,{comments:event.target.value})} placeholder="Optional"/></td><td className="bidSticky bidQty"><b>{line.quantity}</b></td><td className="bidSticky bidPrice"><div className="priceInput"><span>$</span><input aria-label={`Unit bid for line ${line.line}`} type="number" min="0" step="0.01" value={entries[index]?.unitBid||""} onChange={event=>update(index,{unitBid:event.target.value})}/></div></td><td className="bidSticky bidTotal"><output className="lineTotal">{money.format(line.quantity*Number(entries[index]?.unitBid||0))}</output></td></tr>)}</tbody></table></div></section><section className="bidSubmitBar"><div><span>Grand total · {selected.length} lines selected</span><strong>{money.format(total)}</strong></div><button disabled={submitting||!selected.length}>Submit Line-Item Bid</button></section></form></main></Shell>
}
