"use client";
import {FormEvent,useEffect,useState} from "react";
import {Shell} from "../../../components/SiteShell";
import {currentPddSession,type PddSession} from "../../../lib/pdd-auth";
import MailchimpCampaignBuilder from "../../../components/MailchimpCampaignBuilder";

type Config={connected:boolean;audienceId?:string;serverPrefix?:string;senderName?:string;senderEmail?:string;syncCustomers?:boolean;syncProspects?:boolean;syncVendors?:boolean;audienceName?:string};
type Summary={total:number;new:number;existing:number;suppressed:number;invalid:number;missing:number};
type PreviewRow={email:string;company:string;contactName:string;tags:string[];status:string;mailchimpStatus:string};

export default function MailchimpSetupPage(){
 const [session,setSession]=useState<PddSession|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[connected,setConnected]=useState(false),[apiKey,setApiKey]=useState(""),[audienceId,setAudienceId]=useState(""),[serverPrefix,setServerPrefix]=useState(""),[senderName,setSenderName]=useState(""),[senderEmail,setSenderEmail]=useState(""),[syncCustomers,setSyncCustomers]=useState(true),[syncProspects,setSyncProspects]=useState(true),[syncVendors,setSyncVendors]=useState(false),[audienceName,setAudienceName]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState(""),[summary,setSummary]=useState<Summary|null>(null),[rows,setRows]=useState<PreviewRow[]>([]),[truncated,setTruncated]=useState(false);
 useEffect(()=>{currentPddSession().then(async active=>{if(!active){window.location.replace("/employee-login");return}setSession(active);const response=await fetch("/api/admin/mailchimp",{headers:{Authorization:`Bearer ${active.access_token}`},cache:"no-store"}),data=await response.json().catch(()=>({})) as Config&{error?:string};if(!response.ok)setError(data.error||"Mailchimp settings could not be loaded.");else{setConnected(data.connected);setAudienceId(data.audienceId||"");setServerPrefix(data.serverPrefix||"");setSenderName(data.senderName||"");setSenderEmail(data.senderEmail||"");setSyncCustomers(data.syncCustomers??true);setSyncProspects(data.syncProspects??true);setSyncVendors(data.syncVendors??false);setAudienceName(data.audienceName||"")}setLoading(false)})},[]);
 async function request(action:string,payload:Record<string,unknown>={}){if(!session)return null;setBusy(true);setMessage("");setError("");const response=await fetch("/api/admin/mailchimp",{method:"POST",headers:{Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({action,...payload})}),data=await response.json().catch(()=>({})) as Record<string,any>;if(!response.ok){setError(String(data.error||"Mailchimp request failed."));setBusy(false);return null}setBusy(false);return data}
 async function save(event:{preventDefault():void},action:"test"|"save"){event.preventDefault();const data=await request(action,{apiKey,audienceId,serverPrefix,senderName,senderEmail,syncCustomers,syncProspects,syncVendors});if(!data)return;setAudienceName(data.audienceName||"");if(data.saved){setConnected(true);setApiKey("");setSummary(null);setRows([])}setMessage(data.saved?`Connected to ${data.audienceName}.`:`Connection successful: ${data.audienceName}.`)}
 async function preview(){const data=await request("preview");if(!data)return;setSummary(data.summary as Summary);setRows(data.rows as PreviewRow[]);setTruncated(Boolean(data.truncated));setMessage("Preview complete. Review the counts before syncing.")}
 async function sync(){if(!summary||!window.confirm(`Queue ${summary.new+summary.existing+summary.suppressed} valid contacts for Mailchimp? Existing unsubscribe and cleaned statuses will not be changed.`))return;const data=await request("sync");if(!data)return;setMessage(String(data.message||"The Mailchimp sync was queued."))}
 if(loading)return <Shell><main className="mailchimpSetupPage"><p>Loading Mailchimp setup…</p></main></Shell>;
 return <Shell><main className="mailchimpSetupPage"><header><div><p className="eyebrow">M2M DEAL WORKBOOK · EMAIL MARKETING</p><h1>Mailchimp setup</h1><p>Connect, preview and sync one Mailchimp audience.</p></div><a className="button secondary" href="/employee">Back to workbook</a></header>
 <section className="mailchimpConnectionBox"><div className="mailchimpCardHeader"><div><span>CONNECTION</span><h2>Mailchimp Marketing</h2></div><b className={`integrationStatus${connected?" connected":""}`}>{connected?"Connected":"Not connected"}</b></div><p className="mailchimpIntro">Your API key is encrypted before it is stored and is never returned to this page.</p>{audienceName&&<p className="mailchimpAudience"><b>Current audience:</b> {audienceName}</p>}
 <form className="mailchimpConnectionForm" onSubmit={(event:FormEvent<HTMLFormElement>)=>save(event,"save")}><label className="mailchimpWideField">Mailchimp API key<input type="password" value={apiKey} onChange={event=>setApiKey(event.target.value)} placeholder={connected?"Leave blank to keep the saved key":"Paste API key"} autoComplete="new-password" required={!connected}/></label><label>Audience ID<input value={audienceId} onChange={event=>setAudienceId(event.target.value)} required/></label><label>Server prefix<input value={serverPrefix} onChange={event=>setServerPrefix(event.target.value)} placeholder="us21" required/></label><label>Default sender name<input value={senderName} onChange={event=>setSenderName(event.target.value)} required/></label><label>Verified sender email<input type="email" value={senderEmail} onChange={event=>setSenderEmail(event.target.value)} required/></label><fieldset className="mailchimpRules"><legend>Contact groups to sync</legend><label><input type="checkbox" checked={syncCustomers} onChange={event=>setSyncCustomers(event.target.checked)}/> Customers</label><label><input type="checkbox" checked={syncProspects} onChange={event=>setSyncProspects(event.target.checked)}/> Prospects</label><label><input type="checkbox" checked={syncVendors} onChange={event=>setSyncVendors(event.target.checked)}/> Vendors</label><p>Existing unsubscribes and cleaned addresses retain their current Mailchimp status. New contacts are added as non-subscribed transactional contacts.</p></fieldset><div className="mailchimpFormActions"><button className="button secondary" type="button" disabled={busy} onClick={event=>save(event,"test")}>Test Connection</button><button className="button" type="submit" disabled={busy}>Save Connection</button></div></form></section>
 {connected&&<section className="mailchimpConnectionBox mailchimpSyncBox"><div className="mailchimpCardHeader"><div><span>SYNC PREVIEW</span><h2>Workbook contacts</h2></div><button className="button secondary" type="button" disabled={busy} onClick={()=>void preview()}>{busy?"Loading…":"Build Preview"}</button></div><p className="mailchimpIntro">Preview compares the selected Deal Workbook groups with the current Mailchimp audience. Nothing is sent until you confirm Sync to Mailchimp.</p>
 {summary&&<><div className="mailchimpSummary"><article><strong>{summary.total}</strong><span>Workbook contacts</span></article><article><strong>{summary.new}</strong><span>New</span></article><article><strong>{summary.existing}</strong><span>Existing</span></article><article><strong>{summary.suppressed}</strong><span>Unsubscribed or cleaned</span></article><article><strong>{summary.invalid+summary.missing}</strong><span>Missing or invalid email</span></article></div><div className="mailchimpPreviewTable"><table><thead><tr><th>Company</th><th>Contact</th><th>Email</th><th>Tags</th><th>Result</th></tr></thead><tbody>{rows.map((row,index)=><tr key={`${row.email}-${index}`}><td>{row.company||"—"}</td><td>{row.contactName||"—"}</td><td>{row.email||"Missing"}</td><td>{row.tags.join(", ")}</td><td><span className={`mailchimpRowStatus ${row.status}`}>{row.status.replaceAll("_"," ")}</span></td></tr>)}</tbody></table></div>{truncated&&<small className="mailchimpPendingNote">Showing the first 250 contacts. The summary includes all contacts.</small>}<div className="mailchimpSyncActions"><p><b>Safe status rule:</b> existing Mailchimp subscription statuses are preserved. New records are not automatically subscribed to marketing.</p><button className="button" type="button" disabled={busy||summary.new+summary.existing+summary.suppressed===0} onClick={()=>void sync()}>{busy?"Working…":"Sync to Mailchimp"}</button></div></>}
 </section>}{connected&&session&&<MailchimpCampaignBuilder session={session}/>} {error&&<p className="mailchimpFormMessage error" role="alert">{error}</p>}{message&&<p className="mailchimpFormMessage success" role="status">{message}</p>}</main></Shell>
}
