import { env } from "cloudflare:workers";
import { customerUser } from "../../../../lib/customer-server";
import { ensureCustomerCompany } from "../../../../lib/business-company";
import { supabaseRequest } from "../../../../lib/supabase";
const clean=(v:unknown,m=200)=>typeof v==="string"?v.trim().slice(0,m):"";
const schema=`CREATE TABLE IF NOT EXISTS customer_profiles (user_id TEXT PRIMARY KEY,email TEXT NOT NULL,company TEXT NOT NULL DEFAULT '',contact_name TEXT NOT NULL DEFAULT '',phone TEXT NOT NULL DEFAULT '',address1 TEXT NOT NULL DEFAULT '',address2 TEXT NOT NULL DEFAULT '',city TEXT NOT NULL DEFAULT '',region TEXT NOT NULL DEFAULT '',postal_code TEXT NOT NULL DEFAULT '',country TEXT NOT NULL DEFAULT 'United States',updated_at TEXT NOT NULL)`;
export async function GET(request:Request){const user=await customerUser(request);if(!user)return Response.json({error:"Sign in required."},{status:401});await env.DB.prepare(schema).run();const profile=await env.DB.prepare("SELECT * FROM customer_profiles WHERE user_id=?").bind(user.id).first();return Response.json({profile:profile||{email:user.email}})}
export async function PUT(request:Request){
 const user=await customerUser(request);if(!user)return Response.json({error:"Sign in required."},{status:401});
 const body=await request.json() as Record<string,unknown>,company=clean(body.company),contactName=clean(body.contactName),phone=clean(body.phone),billing={address1:clean(body.address1),address2:clean(body.address2),city:clean(body.city),region:clean(body.region),postalCode:clean(body.postalCode),country:clean(body.country)||"United States"},dealNumber=clean(body.dealNumber,40);let ownerName="",ownerEmail="";
 if(dealNumber)try{const response=await supabaseRequest(`/rest/v1/pdd_public_deals?select=owner_name,owner_email&deal_number=eq.${encodeURIComponent(dealNumber)}&limit=1`);if(response.ok){const owner=(await response.json() as Array<{owner_name?:string;owner_email?:string}>)[0];ownerName=clean(owner?.owner_name);ownerEmail=clean(owner?.owner_email)}}catch{/* Preserve an existing owner when lookup is unavailable. */}
 await env.DB.prepare(schema).run();await env.DB.prepare("INSERT INTO customer_profiles (user_id,email,company,contact_name,phone,address1,address2,city,region,postal_code,country,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET email=excluded.email,company=excluded.company,contact_name=excluded.contact_name,phone=excluded.phone,address1=excluded.address1,address2=excluded.address2,city=excluded.city,region=excluded.region,postal_code=excluded.postal_code,country=excluded.country,updated_at=excluded.updated_at").bind(user.id,user.email,company,contactName,phone,billing.address1,billing.address2,billing.city,billing.region,billing.postalCode,billing.country,new Date().toISOString()).run();
 const matched=await ensureCustomerCompany({company,contactName,email:user.email,phone,assignedEmployeeName:ownerName,assignedEmployeeEmail:ownerEmail,source:"customer-account"});
 if(matched){const same=body.shippingSameAsBilling!==false,shipping=same?billing:{address1:clean(body.shippingAddress1),address2:clean(body.shippingAddress2),city:clean(body.shippingCity),region:clean(body.shippingRegion),postalCode:clean(body.shippingPostalCode),country:clean(body.shippingCountry)||"United States"},now=new Date().toISOString();await env.DB.prepare("INSERT INTO business_company_addresses (id,record_type,record_id,billing_address1,billing_address2,billing_city,billing_region,billing_postal_code,billing_country,shipping_same_as_billing,shipping_address1,shipping_address2,shipping_city,shipping_region,shipping_postal_code,shipping_country,updated_at) VALUES (?,'customer',?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(record_type,record_id) DO UPDATE SET billing_address1=excluded.billing_address1,billing_address2=excluded.billing_address2,billing_city=excluded.billing_city,billing_region=excluded.billing_region,billing_postal_code=excluded.billing_postal_code,billing_country=excluded.billing_country,shipping_same_as_billing=excluded.shipping_same_as_billing,shipping_address1=excluded.shipping_address1,shipping_address2=excluded.shipping_address2,shipping_city=excluded.shipping_city,shipping_region=excluded.shipping_region,shipping_postal_code=excluded.shipping_postal_code,shipping_country=excluded.shipping_country,updated_at=excluded.updated_at").bind(crypto.randomUUID(),matched.recordId,billing.address1,billing.address2,billing.city,billing.region,billing.postalCode,billing.country,same?1:0,shipping.address1,shipping.address2,shipping.city,shipping.region,shipping.postalCode,shipping.country,now).run()}
 return Response.json({ok:true,companyRecordId:matched?.recordId||null});
}
