import {env} from "cloudflare:workers";
import {employeeUser} from "../../../../lib/employee-server";
import {pddSupabaseKey,pddSupabaseUrl} from "../../../../lib/pdd-auth";

const schema="CREATE TABLE IF NOT EXISTS mailchimp_config (id TEXT PRIMARY KEY,audience_id TEXT NOT NULL,server_prefix TEXT NOT NULL,sender_name TEXT NOT NULL,sender_email TEXT NOT NULL,api_key_ciphertext TEXT NOT NULL,api_key_iv TEXT NOT NULL,sync_customers INTEGER NOT NULL DEFAULT 1,sync_prospects INTEGER NOT NULL DEFAULT 1,sync_vendors INTEGER NOT NULL DEFAULT 0,audience_name TEXT NOT NULL DEFAULT '',member_count INTEGER NOT NULL DEFAULT 0,connected_at TEXT NOT NULL,updated_at TEXT NOT NULL,updated_by TEXT NOT NULL)";
const headers={"Cache-Control":"no-store"};
type SavedConfig={audience_id:string;server_prefix:string;sender_name:string;sender_email:string;api_key_ciphertext:string;api_key_iv:string;sync_customers:number;sync_prospects:number;sync_vendors:number;audience_name:string;member_count:number;connected_at:string;updated_at:string};
type Contact={email:string;company:string;contactName:string;phone:string;country:string;assignedEmployee:string;tags:Set<string>};
type MailchimpMember={id:string;email_address:string;status:string};
const clean=(value:unknown)=>String(value??"").trim();
const validEmail=(value:string)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
const bytesToBase64=(bytes:Uint8Array)=>btoa(String.fromCharCode(...bytes));
const base64ToBytes=(value:string)=>Uint8Array.from(atob(value),character=>character.charCodeAt(0));

async function encryptionKey(){const secret=clean((env as typeof env&{MAILCHIMP_CONFIG_ENCRYPTION_KEY?:string}).MAILCHIMP_CONFIG_ENCRYPTION_KEY);if(!secret)throw new Error("Mailchimp encryption has not been configured on the server.");const raw=base64ToBytes(secret);if(raw.byteLength!==32)throw new Error("Mailchimp encryption is not configured correctly.");return crypto.subtle.importKey("raw",raw,"AES-GCM",false,["encrypt","decrypt"])}
async function encryptApiKey(value:string){const iv=crypto.getRandomValues(new Uint8Array(12));const encrypted=await crypto.subtle.encrypt({name:"AES-GCM",iv},await encryptionKey(),new TextEncoder().encode(value));return{ciphertext:bytesToBase64(new Uint8Array(encrypted)),iv:bytesToBase64(iv)}}
async function decryptApiKey(ciphertext:string,iv:string){const decrypted=await crypto.subtle.decrypt({name:"AES-GCM",iv:base64ToBytes(iv)},await encryptionKey(),base64ToBytes(ciphertext));return new TextDecoder().decode(decrypted)}
async function savedConfig(){await env.DB.prepare(schema).run();return env.DB.prepare("SELECT * FROM mailchimp_config WHERE id='default'").first<SavedConfig>()}
async function requireAdmin(request:Request){const employee=await employeeUser(request);if(!employee)return{error:Response.json({error:"Employee access required."},{status:401,headers})};if(employee.role!=="administrator")return{error:Response.json({error:"Administrator access is required to manage Mailchimp."},{status:403,headers})};return{employee}}
function mailchimpHeaders(apiKey:string){return{Authorization:`Basic ${btoa(`m2m:${apiKey}`)}`,Accept:"application/json","Content-Type":"application/json"}}
async function mailchimpFetch(config:SavedConfig,apiKey:string,path:string,init:RequestInit={}){const response=await fetch(`https://${config.server_prefix}.api.mailchimp.com/3.0${path}`,{...init,headers:{...mailchimpHeaders(apiKey),...(init.headers||{})}});if(!response.ok){const details=await response.json().catch(()=>({})) as {detail?:string;title?:string};throw new Error(clean(details.detail||details.title)||"Mailchimp rejected the request.")}return response}
async function testAudience(apiKey:string,audienceId:string,serverPrefix:string){const config={audience_id:audienceId,server_prefix:serverPrefix} as SavedConfig;let response:Response;try{response=await mailchimpFetch(config,apiKey,`/lists/${encodeURIComponent(audienceId)}?fields=id,name,stats.member_count`)}catch(error){throw new Error(error instanceof Error?error.message:"Mailchimp could not be reached.")}const audience=await response.json() as {id?:string;name?:string;stats?:{member_count?:number}};if(audience.id!==audienceId)throw new Error("Mailchimp returned a different audience than requested.");return{name:clean(audience.name)||"Mailchimp audience",memberCount:Number(audience.stats?.member_count||0)}}

function addContact(map:Map<string,Contact>,raw:Record<string,unknown>,tag:string){const email=clean(raw.email).toLowerCase(),key=email||`missing:${tag}:${clean(raw.company||raw.company_name)}:${clean(raw.contact_name)}`;const existing=map.get(key);if(existing){existing.tags.add(tag);return}map.set(key,{email,company:clean(raw.company||raw.company_name),contactName:clean(raw.contact_name),phone:clean(raw.phone),country:clean(raw.country),assignedEmployee:clean(raw.assigned_employee_name||raw.created_by_name),tags:new Set([tag])})}
async function d1Rows(sql:string){try{return (await env.DB.prepare(sql).all<Record<string,unknown>>()).results||[]}catch{return[]}}
async function supabaseRows(request:Request,path:string){const authorization=request.headers.get("authorization")||"";const response=await fetch(`${pddSupabaseUrl}${path}`,{headers:{apikey:pddSupabaseKey,Authorization:authorization}});if(!response.ok)throw new Error("The Deal Workbook contact directory could not be loaded.");return await response.json() as Record<string,unknown>[]}
async function loadContacts(request:Request,config:SavedConfig){const contacts=new Map<string,Contact>();if(config.sync_customers){const groups=await Promise.all([d1Rows("SELECT email,company,contact_name,phone,country,'' assigned_employee_name FROM customer_profiles"),d1Rows("SELECT email,company,contact_name,phone,country,assigned_employee_name FROM imported_customers"),d1Rows("SELECT email,company,contact_name,phone,'' country,'' assigned_employee_name FROM internal_bids")]);groups.flat().forEach(row=>addContact(contacts,row,"Customer"))}if(config.sync_vendors){const rows=await supabaseRows(request,"/rest/v1/pdd_vendors?select=company_name,contact_name,email,phone,country,created_by_name");rows.forEach(row=>addContact(contacts,row,"Vendor"))}if(config.sync_prospects){const rows=await supabaseRows(request,"/rest/v1/pdd_end_user_prospects?select=company_name,contact_name,email,phone,country,assigned_employee_name");rows.forEach(row=>addContact(contacts,row,"Prospect"))}return[...contacts.values()]}
async function existingMembers(config:SavedConfig,apiKey:string){const members=new Map<string,MailchimpMember>();for(let offset=0;;offset+=1000){const response=await mailchimpFetch(config,apiKey,`/lists/${encodeURIComponent(config.audience_id)}/members?count=1000&offset=${offset}&fields=members.id,members.email_address,members.status,total_items`),data=await response.json() as {members?:MailchimpMember[];total_items?:number};for(const member of data.members||[])members.set(member.email_address.toLowerCase(),member);if(offset+1000>=Number(data.total_items||0))break}return members}
function splitName(value:string){const parts=value.trim().split(/\s+/).filter(Boolean);return{first:parts[0]||"",last:parts.slice(1).join(" ")}}
async function mergeFieldTags(config:SavedConfig,apiKey:string){const response=await mailchimpFetch(config,apiKey,`/lists/${encodeURIComponent(config.audience_id)}/merge-fields?count=100&fields=merge_fields.tag,merge_fields.name`),data=await response.json() as {merge_fields?:{tag:string;name:string}[]};const fields=data.merge_fields||[];const find=(pattern:RegExp)=>fields.find(field=>pattern.test(`${field.tag} ${field.name}`))?.tag;return{first:find(/\b(first|fname)\b/i),last:find(/\b(last|lname)\b/i),company:find(/\b(company|organization)\b/i),phone:find(/\bphone\b/i),country:find(/\bcountry\b/i)}}
function previewRows(contacts:Contact[],members:Map<string,MailchimpMember>){return contacts.map(contact=>{const member=members.get(contact.email);return{email:contact.email,company:contact.company,contactName:contact.contactName,tags:[...contact.tags],status:!contact.email?"missing_email":!validEmail(contact.email)?"invalid_email":member?.status==="unsubscribed"||member?.status==="cleaned"?"suppressed":member?"existing":"new",mailchimpStatus:member?.status||""}})}

export async function GET(request:Request){const auth=await requireAdmin(request);if(auth.error)return auth.error;const saved=await savedConfig();return Response.json(saved?{connected:true,audienceId:saved.audience_id,serverPrefix:saved.server_prefix,senderName:saved.sender_name,senderEmail:saved.sender_email,syncCustomers:Boolean(saved.sync_customers),syncProspects:Boolean(saved.sync_prospects),syncVendors:Boolean(saved.sync_vendors),audienceName:saved.audience_name,memberCount:saved.member_count,connectedAt:saved.connected_at,updatedAt:saved.updated_at}:{connected:false},{headers})}

export async function POST(request:Request){
 const auth=await requireAdmin(request);if(auth.error)return auth.error;
 const body=await request.json().catch(()=>({})) as Record<string,unknown>,action=clean(body.action),existing=await savedConfig();
 if(action==="preview"||action==="sync"){
  if(!existing)return Response.json({error:"Save the Mailchimp connection first."},{status:400,headers});
  try{const apiKey=await decryptApiKey(existing.api_key_ciphertext,existing.api_key_iv),contacts=await loadContacts(request,existing),members=await existingMembers(existing,apiKey),rows=previewRows(contacts,members),summary={total:rows.length,new:rows.filter(row=>row.status==="new").length,existing:rows.filter(row=>row.status==="existing").length,suppressed:rows.filter(row=>row.status==="suppressed").length,invalid:rows.filter(row=>row.status==="invalid_email").length,missing:rows.filter(row=>row.status==="missing_email").length};
   if(action==="preview")return Response.json({ok:true,summary,rows:rows.slice(0,250),truncated:rows.length>250},{headers});
   const eligible=contacts.filter(contact=>validEmail(contact.email)),fields=await mergeFieldTags(existing,apiKey),operations=eligible.map(contact=>{const member=members.get(contact.email),name=splitName(contact.contactName),merge_fields:Record<string,string>={};if(fields.first&&name.first)merge_fields[fields.first]=name.first;if(fields.last&&name.last)merge_fields[fields.last]=name.last;if(fields.company&&contact.company)merge_fields[fields.company]=contact.company;if(fields.phone&&contact.phone)merge_fields[fields.phone]=contact.phone;if(fields.country&&contact.country)merge_fields[fields.country]=contact.country;const bodyData=member?{merge_fields,tags:[...contact.tags]}:{email_address:contact.email,status:"transactional",merge_fields,tags:[...contact.tags]};return{method:member?"PATCH":"POST",path:member?`lists/${existing.audience_id}/members/${member.id}`:`lists/${existing.audience_id}/members`,body:JSON.stringify(bodyData)}}),batchIds:string[]=[];
   for(let index=0;index<operations.length;index+=500){const response=await mailchimpFetch(existing,apiKey,"/batches",{method:"POST",body:JSON.stringify({operations:operations.slice(index,index+500)})}),batch=await response.json() as {id?:string};if(batch.id)batchIds.push(batch.id)}
   return Response.json({ok:true,queued:operations.length,batches:batchIds.length,batchIds,summary,message:`${operations.length} contacts were queued in ${batchIds.length} Mailchimp batch${batchIds.length===1?"":"es"}.`},{headers});
  }catch(error){return Response.json({error:error instanceof Error?error.message:"The Mailchimp sync could not be prepared."},{status:400,headers})}
 }
 if(action!=="test"&&action!=="save")return Response.json({error:"Choose Test Connection, Save Connection, Preview, or Sync."},{status:400,headers});
 const audienceId=clean(body.audienceId),serverPrefix=clean(body.serverPrefix).toLowerCase(),senderName=clean(body.senderName),senderEmail=clean(body.senderEmail).toLowerCase();let apiKey=clean(body.apiKey);if(!apiKey&&existing)apiKey=await decryptApiKey(existing.api_key_ciphertext,existing.api_key_iv);if(!apiKey)return Response.json({error:"Mailchimp API key is required."},{status:400,headers});if(!/^[a-z0-9]+$/i.test(audienceId))return Response.json({error:"Enter a valid Mailchimp Audience ID."},{status:400,headers});if(!/^[a-z]{2}\d+$/i.test(serverPrefix))return Response.json({error:"Enter a server prefix such as us21."},{status:400,headers});if(!senderName)return Response.json({error:"Default sender name is required."},{status:400,headers});if(!validEmail(senderEmail))return Response.json({error:"Enter a valid verified sender email."},{status:400,headers});
 try{const audience=await testAudience(apiKey,audienceId,serverPrefix);if(action==="save"){const protectedKey=await encryptApiKey(apiKey),now=new Date().toISOString();await env.DB.prepare("INSERT INTO mailchimp_config (id,audience_id,server_prefix,sender_name,sender_email,api_key_ciphertext,api_key_iv,sync_customers,sync_prospects,sync_vendors,audience_name,member_count,connected_at,updated_at,updated_by) VALUES ('default',?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET audience_id=excluded.audience_id,server_prefix=excluded.server_prefix,sender_name=excluded.sender_name,sender_email=excluded.sender_email,api_key_ciphertext=excluded.api_key_ciphertext,api_key_iv=excluded.api_key_iv,sync_customers=excluded.sync_customers,sync_prospects=excluded.sync_prospects,sync_vendors=excluded.sync_vendors,audience_name=excluded.audience_name,member_count=excluded.member_count,updated_at=excluded.updated_at,updated_by=excluded.updated_by").bind(audienceId,serverPrefix,senderName,senderEmail,protectedKey.ciphertext,protectedKey.iv,body.syncCustomers===false?0:1,body.syncProspects===false?0:1,body.syncVendors===true?1:0,audience.name,audience.memberCount,existing?.connected_at||now,now,auth.employee.email).run()}return Response.json({ok:true,saved:action==="save",audienceName:audience.name,memberCount:audience.memberCount},{headers})}catch(error){return Response.json({error:error instanceof Error?error.message:"Mailchimp connection failed."},{status:400,headers})}
}
