"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Deal={id:string;deal_number:string;direction:"buying"|"selling";category:string;title:string;description:string;quantity:number;manufacturer:string;part_number:string;closes_at:string;location:string};
const demoDeals:Deal[]=[
 {id:"demo-1",deal_number:"PDD-260821-01",direction:"selling",category:"Server Memory",title:"64GB DDR5 ECC RDIMM Memory",description:"Enterprise server memory available as one wholesale lot. Exact manufacturer labels and test report are available to qualified buyers.",quantity:128,manufacturer:"SK hynix / Micron",part_number:"Multiple qualified P/Ns",closes_at:"2026-08-28T17:00:00-07:00",location:"California, USA"},
 {id:"demo-2",deal_number:"PDD-260821-02",direction:"buying",category:"NVIDIA GPUs",title:"NVIDIA L4 24GB GPUs Wanted",description:"Mac2MacOnline is requesting offers for tested NVIDIA L4 GPUs. Include quantity, condition, warranty status and equipment location.",quantity:24,manufacturer:"NVIDIA",part_number:"L4 24GB",closes_at:"2026-08-30T17:00:00-07:00",location:"Worldwide"},
 {id:"demo-3",deal_number:"PDD-260821-03",direction:"selling",category:"Enterprise SSDs",title:"3.84TB NVMe Enterprise SSD Lot",description:"Data-center NVMe SSDs with quantities and health details supplied in the complete lot file.",quantity:80,manufacturer:"Samsung",part_number:"PM9A3 3.84TB",closes_at:"2026-09-02T12:00:00-07:00",location:"California, USA"}
];
function formatClose(value:string){return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit",timeZoneName:"short"}).format(new Date(value))}

export default function Home(){
 const [direction,setDirection]=useState("all");
 const [query,setQuery]=useState("");
 const [selected,setSelected]=useState<Deal|null>(null);
 const [notice,setNotice]=useState("");
 const [allDeals,setAllDeals]=useState<Deal[]>(demoDeals);
 const [live,setLive]=useState(false);
 const [submitting,setSubmitting]=useState(false);
 useEffect(()=>{let active=true;fetch("/api/deals").then(r=>r.ok?r.json():Promise.reject()).then(data=>{if(active&&Array.isArray(data.deals)&&data.deals.length){setAllDeals(data.deals);setLive(true)}}).catch(()=>{});return()=>{active=false}},[]);
 const deals=useMemo(()=>allDeals.filter(deal=>{const haystack=`${deal.deal_number} ${deal.category} ${deal.title} ${deal.description} ${deal.manufacturer} ${deal.part_number}`.toLowerCase();return(direction==="all"||deal.direction===direction)&&haystack.includes(query.toLowerCase())}),[allDeals,direction,query]);
 async function submitBid(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;setSubmitting(true);setNotice("");const form=event.currentTarget;const body=new FormData(form);body.set("deal_id",selected.id);try{const response=await fetch("/api/bids",{method:"POST",body});const data=await response.json();if(!response.ok)throw new Error(data.error||"Your offer could not be submitted.");setNotice(`Offer ${data.bid_number} was received confidentially. Mac2MacOnline will contact you if it is shortlisted or awarded.`);form.reset()}catch(error){setNotice(error instanceof Error?error.message:"Your offer could not be submitted. Please try again.")}finally{setSubmitting(false)}}
 return <main>
  <header className="topbar"><a className="brand" href="https://www.mac2maconline.com" target="_blank" rel="noreferrer"><img src="https://brainfarmusa.github.io/BrainFarm/assets/m2m-logo-blue.png" alt="Mac2MacOnline"/></a><nav aria-label="Primary navigation"><a href="#deals">Open Deals</a><a href="#how-it-works">How It Works</a><a href="#standards">Standards</a><a className="navButton" href="https://www.mac2maconline.com" target="_blank" rel="noreferrer">Main Website</a></nav></header>
  <section className="hero"><div className="heroCopy"><p className="eyebrow">MAC2MACONLINE PUBLIC DEAL DESK</p><h1>Wholesale technology deals, <span>open to qualified partners.</span></h1><p className="lead">Review active buying requests and available inventory, submit your offer securely and complete awarded purchases through Mac2MacOnline’s Shopify checkout.</p><div className="heroActions"><a className="primaryButton" href="#deals">View Open Deals</a><a className="secondaryButton" href="#how-it-works">How Awards Work</a></div><div className="trustRow"><span>R2v3 Certified</span><span>ISO 9001</span><span>ISO 14001</span><span>ISO 45001</span></div></div><aside className="processCard"><p className="eyebrow">FROM BID TO ORDER</p><ol><li><b>Find a deal</b><span>Search buying requests and available lots.</span></li><li><b>Submit your offer</b><span>Include price, quantity, condition and timing.</span></li><li><b>Receive an award</b><span>Winning bidders receive a private Shopify order.</span></li><li><b>Complete securely</b><span>Confirm shipping and payment through Shopify.</span></li></ol></aside></section>
  <section className="dealSection" id="deals"><div className="sectionHeading"><div><p className="eyebrow">CURRENT OPPORTUNITIES</p><h2>Public Deal Desk</h2><p>All deadlines are shown in Pacific Time unless the deal states otherwise.</p></div><div className="livePill"><i/> {live?"Live Supabase feed":"Review data"}</div></div><div className="controls"><div className="segmented" aria-label="Deal type"><button className={direction==="all"?"active":""} onClick={()=>setDirection("all")}>All deals</button><button className={direction==="selling"?"active":""} onClick={()=>setDirection("selling")}>Inventory for sale</button><button className={direction==="buying"?"active":""} onClick={()=>setDirection("buying")}>Wanted inventory</button></div><label className="search"><span>Search</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Part number, category or keyword"/></label></div><div className="dealGrid">{deals.map(deal=><article className="dealCard" key={deal.id}><div className="dealMeta"><span className={deal.direction}>{deal.direction==="selling"?"For Sale":"Want to Buy"}</span><b>{deal.deal_number}</b></div><p className="category">{deal.category}</p><h3>{deal.title}</h3><p className="description">{deal.description}</p><dl><div><dt>Manufacturer</dt><dd>{deal.manufacturer}</dd></div><div><dt>Part number</dt><dd>{deal.part_number}</dd></div><div><dt>Quantity</dt><dd>{deal.quantity.toLocaleString()}</dd></div><div><dt>Location</dt><dd>{deal.location}</dd></div></dl><div className="deadline"><span>Offers close</span><strong>{formatClose(deal.closes_at)}</strong></div><button className="cardButton" onClick={()=>{setSelected(deal);setNotice("")}}>{deal.direction==="selling"?"Submit an offer":"Offer this inventory"}</button></article>)}</div>{!deals.length&&<div className="emptyState"><h3>No matching deals</h3><p>Try a broader search or view all deal types.</p></div>}</section>
  <section className="howSection" id="how-it-works"><div><p className="eyebrow">AWARD PROCESS</p><h2>Private pricing. Clear awards. Shopify fulfillment.</h2><p>Offers remain private. When Mac2MacOnline awards a deal, the selected buyer receives a Shopify draft order containing the exact awarded items, quantities, pricing, shipping and payment terms.</p></div><div className="awardFlow"><article><b>01</b><h3>Review</h3><p>Our team validates the bidder, offer and delivery requirements.</p></article><article><b>02</b><h3>Award</h3><p>The winning offer is accepted for a limited confirmation period.</p></article><article><b>03</b><h3>Order</h3><p>A private Shopify invoice and secure checkout link are issued.</p></article><article><b>04</b><h3>Close</h3><p>Payment and order status return to PDD and the deal is archived.</p></article></div></section>
  <section className="standards" id="standards"><div><p className="eyebrow">MAC2MACONLINE</p><h2>Built for repeat wholesale relationships.</h2></div><p>Deal records, customer responses and attachments are maintained through Supabase. Shopify handles awarded orders, payment terms and checkout while PDD keeps the complete opportunity history.</p></section>
  <footer><span>© 2026 Mac2MacOnline</span><span>Public Deal Desk (PDD)</span><a href="https://www.mac2maconline.com" target="_blank" rel="noreferrer">mac2maconline.com</a></footer>
  {selected&&<div className="modalBackdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><section className="bidModal" role="dialog" aria-modal="true" aria-labelledby="bid-title"><button className="closeButton" aria-label="Close" onClick={()=>setSelected(null)}>×</button><p className="eyebrow">{selected.deal_number}</p><h2 id="bid-title">{selected.direction==="selling"?"Submit an offer":"Offer your inventory"}</h2><p className="modalDeal">{selected.title}</p><form onSubmit={submitBid}><div className="formGrid"><label>Company<input required name="company"/></label><label>Contact name<input required name="contact"/></label><label>Email<input required type="email" name="email"/></label><label>Phone<input required name="phone"/></label><label>Quantity<input required type="number" min="1" name="quantity"/></label><label>Unit price<input required type="number" min="0" step="0.01" name="unit_price"/></label></div><label>Condition, timing and notes<textarea required name="notes" rows={4}/></label><label className="fileLabel">Supporting file<input type="file" name="attachment" accept=".pdf,.xls,.xlsx,.csv,.jpg,.jpeg,.png"/><small>Spreadsheet, PDF or clear product-label photographs, up to 10 MB.</small></label><button className="primaryButton submitButton" type="submit" disabled={submitting}>{submitting?"Submitting securely…":"Submit confidential offer"}</button>{notice&&<p className="notice">{notice}</p>}</form></section></div>}
 </main>
}
