import Link from "next/link";
import {Shell} from "@/components/SiteShell";

const services=[
  ["Buy from us","Current inventory, tested systems, components and wholesale lots sourced through an established global network.","/want-to-buy","/assets/m2m-buy-card.png","Tested computers, servers and components organized for purchase"],
  ["Sell to us","Turn surplus computers, servers, parts and enterprise equipment into working capital with a direct purchase.","/want-to-sell","/assets/m2m-sell-card.png","Surplus business technology being inventoried for resale"],
  ["Consign with us","Keep more upside on specialized or higher-value equipment while we handle marketing, buyer outreach and transaction support.","/consignment","/assets/m2m-consign-card.png","High-value enterprise equipment receiving a consignment review"],
];
const equipmentCategories=[
  ["Apple computers & parts","/assets/m2m-category-apple.png","Apple-style computers, laptops and service parts"],
  ["Servers & enterprise storage","/assets/m2m-category-servers.png","Rackmount servers and enterprise storage arrays"],
  ["Memory, SSDs & components","/assets/m2m-category-components.png","Server memory, solid-state drives, processors and components"],
  ["GPUs & AI hardware","/assets/m2m-category-gpu.png","Data-center GPUs and AI computing hardware"],
  ["Networking & data-center gear","/assets/m2m-category-network.png","Enterprise network switches, fiber equipment and cabling"],
  ["Chromebooks & business systems","/assets/m2m-category-chromebooks.png","Business laptops and compact desktop systems"],
];

export default function Home(){return <Shell><main>
  <section className="hero"><div className="wrap hero-grid"><div><span className="eyebrow">Technology has a next chapter.</span><h1>Get rid of it.<br/><em>Recover value.</em><br/>Build what’s next.</h1><p>Mac2MacOnline connects businesses, resellers and technology buyers with dependable wholesale equipment, asset recovery and remarketing solutions.</p><div className="actions"><Link className="button" href="/want-to-sell">Sell Equipment</Link><Link className="button secondary" href="/want-to-buy">Find Equipment</Link></div><div className="trust-row"><span>R2v3</span><span>ISO 9001</span><span>ISO 14001</span><span>ISO 45001</span></div></div><div className="hero-card"><div className="orbit"><span>Servers</span><span>Apple</span><span>Parts</span><span>AI</span><strong>M2M</strong></div><div className="metric"><b>20+ years</b><small>technology market experience</small></div></div></div></section>
  <section className="intro wrap"><span className="eyebrow">One market. Multiple ways to work together.</span><h2>Buy, sell or consign with a partner that understands the equipment.</h2><div className="service-grid">{services.map(([title,description,href,image,alt],i)=><Link className="service-card" href={href} key={title}><img className="service-card-image" src={image} alt={alt}/><div className="service-card-body"><span>0{i+1}</span><h3>{title}</h3><p>{description}</p><b>Learn more →</b></div></Link>)}</div></section>
  <section className="categories"><div className="wrap"><div className="section-head"><div><span className="eyebrow">Equipment we handle</span><h2>From current-generation systems to specialized parts.</h2></div><Link href="/equipment-we-buy">View all categories →</Link></div><div className="category-grid">{equipmentCategories.map(([title,image,alt],i)=><div className="category category-with-image" key={title}><img className="category-image" src={image} alt={alt}/><div className="category-body"><span>{String(i+1).padStart(2,"0")}</span><h3>{title}</h3></div></div>)}</div></div></section>
  <section className="partnership wrap"><div><span className="eyebrow">Connected expertise</span><h2>Resale lifecycle meets private AI infrastructure.</h2><p>Mac2MacOnline and BrainFarm USA are collaborating companies with complementary strengths. M2M helps organizations acquire, sell, consign and responsibly move technology. BrainFarm USA engineers, deploys and supports private AI hardware that keeps company data under company control.</p><div className="actions"><Link className="button" href="/about">How we work together</Link><a className="button secondary" href="https://brainfarmusa.github.io/BrainFarm/" target="_blank" rel="noreferrer">Visit BrainFarm USA ↗</a></div></div><div className="partner-mark"><img src="/assets/brainfarm-emblem.png" alt="BrainFarm USA emblem"/><strong>Mac2MacOnline</strong><span>+</span><strong>BrainFarm USA</strong><small>Technology lifecycle + private AI systems</small></div></section>
  <section className="cta"><div className="wrap"><div><span className="eyebrow">Let’s talk equipment.</span><h2>Send us a list. Tell us what you need.</h2></div><div className="actions"><Link className="button light" href="/request-quote">Request a Quote</Link><Link className="text-link" href="/consignment">Explore consignment →</Link></div></div></section>
</main></Shell>}
