import Link from "next/link";
import {Shell} from "@/components/SiteShell";

const services=[
  ["Buy from us","Current inventory, tested systems, components and wholesale lots sourced through an established global network.","/want-to-buy","/assets/m2m-buy-card.png","Tested computers, servers and components organized for purchase"],
  ["Sell to us","Turn surplus computers, servers, parts and enterprise equipment into working capital with a direct purchase.","/want-to-sell","/assets/m2m-sell-card.png","Surplus business technology being inventoried for resale"],
  ["Consign with us","Keep more upside on specialized or higher-value equipment while we handle marketing, buyer outreach and transaction support.","/consignment","/assets/m2m-consign-card.png","High-value enterprise equipment receiving a consignment review"],
];
const equipmentCategories=[
  ["Apple computers & parts","/assets/m2m-category-apple.png","Apple-style computers, laptops and service parts","/we-buy-apple-equipment"],
  ["Servers & enterprise storage","/assets/m2m-category-servers.png","Rackmount servers and enterprise storage arrays","/sell-used-servers-networking"],
  ["Memory, SSDs & components","/assets/m2m-category-components.png","Server memory, solid-state drives, processors and components","/sell-ram-ssds-gpus-apple"],
  ["GPUs & AI hardware","/assets/m2m-category-gpu.png","Data-center GPUs and AI computing hardware","/we-buy-gpus"],
  ["Networking & data-center gear","/assets/m2m-category-network.png","Enterprise network switches, fiber equipment and cabling","/sell-used-servers-networking"],
  ["Chromebooks & business systems","/assets/m2m-category-chromebooks.png","Business laptops and compact desktop systems","/sell-business-laptops-desktops-workstations"],
];

export default function Home(){return <Shell><main>
  <section className="equipmentBuyAlert homeBuyAlert"><div className="wrap"><div><span>WE ARE ACTIVELY BUYING</span><h1>RAM, SSDs &amp; GPUs—Any Condition.</h1><p>New, used, tested, untested or mixed lots. Send your inventory list now for a fast review.</p></div><Link className="button" href="/trade-in">Use Our Upgrade Trade-In Program →</Link></div></section>
  <section className="hero"><div className="wrap hero-grid"><div><span className="eyebrow">WE BUY BUSINESS AND ENTERPRISE TECHNOLOGY</span><h1>Send us your list.<br/><em>Recover its value.</em></h1><p>Sell surplus RAM, enterprise SSDs, GPUs, Apple equipment, servers and networking hardware directly to an experienced wholesale buyer.</p><div className="actions"><Link className="button" href="/want-to-sell">Send Us Your Inventory List</Link><Link className="button secondary" href="/live-bid-board">View Equipment for Sale</Link></div><div className="seller-proof"><strong>Lists do not need to be perfect.</strong><span>Spreadsheets, exports and clear label photos are welcome.</span><span>Tested, untested, sorted and mixed inventory considered.</span></div><Link className="trust-row" href="/certifications" aria-label="View our certifications"><span>R2v3</span><span>ISO 9001</span><span>ISO 14001</span><span>ISO 45001</span></Link></div><div className="hero-card"><div className="orbit"><span>Server RAM</span><span>Enterprise SSDs</span><span>GPUs</span><span>Apple</span><strong>M2M</strong></div><div className="metric"><b>20+ years</b><small>technology market experience</small></div></div></div></section>
  <section className="intro wrap"><span className="eyebrow">One market. Multiple ways to work together.</span><h2>Buy, sell or consign with a partner that understands the equipment.</h2><div className="service-grid">{services.map(([title,description,href,image,alt],i)=><Link className="service-card" href={href} key={title}><img className="service-card-image" src={image} alt={alt}/><div className="service-card-body"><span>0{i+1}</span><h3>{title}</h3><p>{description}</p><b>Learn more →</b></div></Link>)}</div></section>
  <section className="categories"><div className="wrap"><div className="section-head"><div><span className="eyebrow">Equipment we handle</span><h2>From current-generation systems to specialized parts.</h2></div><Link href="/equipment-we-buy">View all categories →</Link></div><div className="category-grid">{equipmentCategories.map(([title,image,alt,href],i)=><Link href={href} className="category category-with-image" key={title}><img className="category-image" src={image} alt={alt}/><div className="category-body"><span>{String(i+1).padStart(2,"0")}</span><h3>{title}</h3></div></Link>)}</div></div></section>
  <section className="homeSellerGuide"><div className="wrap"><div><span className="eyebrow">SELLING RAM OR SSDs?</span><h2>Know what to send before requesting an offer.</h2><p>Our practical guide explains the details that help us evaluate used server memory and enterprise SSD lots—from part numbers and condition to quantities and logistics.</p></div><Link className="button" href="/insights/where-to-sell-used-server-ram-and-ssds-in-bulk">Read the RAM &amp; SSD guide →</Link></div></section>
  <section className="homeCertifications"><div className="wrap homeCertificationGrid"><div><span className="eyebrow">CERTIFIED OPERATIONS</span><h2>Responsible technology handling, backed by audited systems.</h2><p>Sierra Circuit Repair, Inc., doing business as Mac2MacOnline, operates under R2v3, ISO 9001, ISO 14001 and ISO 45001 certifications.</p><Link className="text-link" href="/certifications">View our certifications and official descriptions →</Link></div><div className="homeCertificationMarks"><Link href="/certifications#r2v3"><img src="/assets/certifications/r2v3-standard-logo.png" alt="Official R2v3 standard logo"/><strong>R2v3</strong><span>Responsible electronics</span></Link><Link className="homeIsoMark" href="/certifications#iso-9001"><img src="/assets/certifications/pjr-registrar-logo.png" alt="Official Perry Johnson Registrars logo"/><strong>Certified Management Systems</strong><small><b>ISO 9001</b><b>ISO 14001</b><b>ISO 45001</b></small></Link></div></div></section>
  <section className="partnership wrap"><div><span className="eyebrow">Connected expertise</span><h2>Resale lifecycle meets private AI infrastructure.</h2><p>Mac2MacOnline and BrainFarm USA are collaborating companies with complementary strengths. M2M helps organizations acquire, sell, consign and responsibly move technology. BrainFarm USA engineers, deploys and supports private AI hardware that keeps company data under company control.</p><div className="actions"><Link className="button" href="/about">How we work together</Link><a className="button secondary" href="https://www.brainfarmusa.ai" target="_blank" rel="noreferrer">Visit BrainFarm USA ↗</a></div></div><div className="partner-mark"><div className="partner-brand"><img className="m2m-home-logo" src="/assets/mac2mac-online-home-logo.png?v=2" alt="Mac2MacOnline"/></div><span>+</span><div className="partner-brand"><img src="/assets/brainfarm-emblem.png" alt="BrainFarm USA brain emblem"/><strong>BrainFarm USA</strong></div><small>Technology lifecycle + private AI systems</small></div></section>
  <section className="cta"><div className="wrap"><div><span className="eyebrow">Let’s talk equipment.</span><h2>Send us a list. Tell us what you need.</h2></div><div className="actions"><Link className="button light" href="/request-quote">Request a Quote</Link><Link className="text-link" href="/consignment">Explore consignment →</Link></div></div></section>
</main></Shell>}
