"use client";

import { useEffect, useState } from "react";
import type { PddSession } from "../lib/pdd-auth";
import "./company-contacts.css";

type Contact = { id?: string; contactName: string; jobTitle: string; email: string; phone: string; isPrimary?: boolean };
type Address = { billingAddress1:string; billingAddress2:string; billingCity:string; billingRegion:string; billingPostalCode:string; billingCountry:string; shippingSameAsBilling:boolean; shippingAddress1:string; shippingAddress2:string; shippingCity:string; shippingRegion:string; shippingPostalCode:string; shippingCountry:string };
const emptyAddress:Address={billingAddress1:"",billingAddress2:"",billingCity:"",billingRegion:"",billingPostalCode:"",billingCountry:"United States",shippingSameAsBilling:true,shippingAddress1:"",shippingAddress2:"",shippingCity:"",shippingRegion:"",shippingPostalCode:"",shippingCountry:"United States"};
const addressText=(a:Address,shipping=false)=>shipping&&a.shippingSameAsBilling?"Same as billing":[shipping?a.shippingAddress1:a.billingAddress1,shipping?a.shippingAddress2:a.billingAddress2,shipping?a.shippingCity:a.billingCity,shipping?a.shippingRegion:a.billingRegion,shipping?a.shippingPostalCode:a.billingPostalCode,shipping?a.shippingCountry:a.billingCountry].filter(Boolean).join(", ")||"—";

export default function CompanyContacts({recordType,recordId,session,initialContact,initialAddress}:{recordType:"customer"|"vendor"|"prospect";recordId:string;session:PddSession|null;initialContact:Contact;initialAddress:Partial<Address>}){
 const [contacts,setContacts]=useState<Contact[]>([initialContact]); const [selected,setSelected]=useState(0); const [address,setAddress]=useState<Address>({...emptyAddress,...initialAddress}); const [editing,setEditing]=useState(false); const [message,setMessage]=useState("");
 useEffect(()=>{if(!session)return;void fetch(`/api/business-company-details?recordType=${recordType}&recordId=${encodeURIComponent(recordId)}`,{headers:{Authorization:`Bearer ${session.access_token}`}}).then(r=>r.json()).then(data=>{if(data.contacts?.length)setContacts(data.contacts.map((c:any)=>({id:c.id,contactName:c.contact_name,jobTitle:c.job_title,email:c.email,phone:c.phone,isPrimary:Boolean(c.is_primary)})));if(data.address)setAddress({billingAddress1:data.address.billing_address1||"",billingAddress2:data.address.billing_address2||"",billingCity:data.address.billing_city||"",billingRegion:data.address.billing_region||"",billingPostalCode:data.address.billing_postal_code||"",billingCountry:data.address.billing_country||"United States",shippingSameAsBilling:Boolean(data.address.shipping_same_as_billing),shippingAddress1:data.address.shipping_address1||"",shippingAddress2:data.address.shipping_address2||"",shippingCity:data.address.shipping_city||"",shippingRegion:data.address.shipping_region||"",shippingPostalCode:data.address.shipping_postal_code||"",shippingCountry:data.address.shipping_country||"United States"})}).catch(()=>setMessage("Additional contacts could not be loaded."))},[recordType,recordId,session]);
 const updateContact=(index:number,key:keyof Contact,value:string|boolean)=>setContacts(rows=>rows.map((row,i)=>i===index?{...row,[key]:value}:row)); const updateAddress=(key:keyof Address,value:string|boolean)=>setAddress(a=>({...a,[key]:value}));
 async function save(){if(!session)return;setMessage("");const ordered=[contacts[selected],...contacts.filter((_,i)=>i!==selected)].filter(Boolean).map((c,i)=>({...c,isPrimary:i===0}));const response=await fetch("/api/business-company-details",{method:"PUT",headers:{Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({recordType,recordId,contacts:ordered,address})});if(!response.ok){setMessage("Contacts and addresses could not be saved.");return}setContacts(ordered);setSelected(0);setEditing(false);setMessage("Company contacts and addresses saved.")}
 const contact=contacts[selected]||contacts[0];
 if(!editing)return <section className="companyContactBlock"><div><b>Contact</b>{contacts.length>1?<select value={selected} onChange={e=>setSelected(Number(e.target.value))}>{contacts.map((c,i)=><option value={i} key={c.id||`${c.email}-${i}`}>{c.contactName||c.email} · {c.email}</option>)}</select>:<span>{contact?.contactName||"—"}</span>}<small>{[contact?.jobTitle,contact?.email,contact?.phone].filter(Boolean).join(" · ")}</small></div><div><b>Billing address</b><span>{addressText(address)}</span></div><div><b>Shipping address</b><span>{addressText(address,true)}</span></div><button type="button" className="button secondary" onClick={()=>setEditing(true)}>Edit Contacts &amp; Addresses</button>{message&&<small>{message}</small>}</section>;
 return <section className="companyContactBlock editing"><h4>Company contacts</h4>{contacts.map((c,i)=><div className="companyContactRow" key={c.id||i}><button type="button" onClick={()=>setSelected(i)}>{i===selected?"Primary":"Make primary"}</button><input aria-label="Contact name" placeholder="Contact name" value={c.contactName} onChange={e=>updateContact(i,"contactName",e.target.value)}/><input aria-label="Job title" placeholder="Job title" value={c.jobTitle} onChange={e=>updateContact(i,"jobTitle",e.target.value)}/><input aria-label="Email" placeholder="Email" type="email" value={c.email} onChange={e=>updateContact(i,"email",e.target.value)}/><input aria-label="Phone" placeholder="Phone" value={c.phone} onChange={e=>updateContact(i,"phone",e.target.value)}/><button type="button" disabled={contacts.length===1} onClick={()=>{setContacts(rows=>rows.filter((_,x)=>x!==i));setSelected(0)}}>Remove</button></div>)}<button type="button" onClick={()=>{setContacts(rows=>[...rows,{contactName:"",jobTitle:"",email:"",phone:""}]);setSelected(contacts.length)}}>Add contact</button><h4>Billing address</h4><div className="companyAddressGrid">{(["billingAddress1","billingAddress2","billingCity","billingRegion","billingPostalCode","billingCountry"] as const).map(k=><input key={k} aria-label={k} placeholder={k.replace(/^billing/,"").replace(/([A-Z])/g," $1").trim()} value={String(address[k])} onChange={e=>updateAddress(k,e.target.value)}/>)}</div><label><input type="checkbox" checked={address.shippingSameAsBilling} onChange={e=>updateAddress("shippingSameAsBilling",e.target.checked)}/> Shipping address is the same as billing</label>{!address.shippingSameAsBilling&&<><h4>Shipping address</h4><div className="companyAddressGrid">{(["shippingAddress1","shippingAddress2","shippingCity","shippingRegion","shippingPostalCode","shippingCountry"] as const).map(k=><input key={k} aria-label={k} placeholder={k.replace(/^shipping/,"").replace(/([A-Z])/g," $1").trim()} value={String(address[k])} onChange={e=>updateAddress(k,e.target.value)}/>)}</div></>}<div className="companyContactActions"><button type="button" className="button" onClick={()=>void save()}>Save</button><button type="button" className="button secondary" onClick={()=>setEditing(false)}>Cancel</button></div>{message&&<small>{message}</small>}</section>
}
