"use client";
import {FormEvent,useState} from "react";
import InternationalPhoneField from "@/components/InternationalPhoneField";
type InquiryType="buy"|"sell"|"quote"|"consignment";
const ENDPOINT="/api/inquiries";
const labels={buy:"Want to Buy",sell:"Want to Sell",quote:"Request a Quote",consignment:"Consignment Review"};
export default function InquiryForm({type,individualFriendly=false,sellerFocus=false}:{type:InquiryType;individualFriendly?:boolean;sellerFocus?:boolean}){
 const[status,setStatus]=useState("Your request and attachments will be submitted securely."),[state,setState]=useState(""),[submitting,setSubmitting]=useState(false);const isBuy=type==="buy",isSell=type==="sell";
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const files=Array.from(form.querySelector<HTMLInputElement>('input[type="file"]')?.files||[]);if(files.length>5){setState("error");setStatus("Please attach no more than five files.");return}if(files.some(f=>f.size>10*1024*1024)){setState("error");setStatus("Each attachment must be 10MB or smaller.");return}setSubmitting(true);setState("working");setStatus(files.length?"Securely uploading your files…":"Securely sending your request…");try{const response=await fetch(ENDPOINT,{method:"POST",body:new FormData(form)});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||"The request could not be submitted.");window.dispatchEvent(new CustomEvent("m2m-conversion",{detail:{event:"inquiry_submit",label:type}}));form.reset();setState("success");setStatus(`Thank you. Your request was received. Reference: ${result.reference||"submitted"}`)}catch(error){setState("error");setStatus(error instanceof Error?error.message:"We could not submit your request. Please try again.")}finally{setSubmitting(false)}}
 return <form className={`inquiry-form ${isBuy?"dark-form":""} ${sellerFocus?"seller-focus-form":""}`} onSubmit={submit} encType="multipart/form-data"><input type="hidden" name="Inquiry type" value={isBuy?"want-to-buy":isSell?"want-to-sell":type}/><input type="hidden" name="Website source" value={sellerFocus?"Mac2MacOnline RAM and SSD WTS":individualFriendly?"Mac2MacOnline Parts and Apple Landing Page":"Mac2MacOnline"}/><label className="form-trap" aria-hidden="true">Website<input name="Website" tabIndex={-1} autoComplete="off"/></label><h2>{sellerFocus?"Get an offer for your inventory":labels[type]}</h2><p>{sellerFocus?"Part numbers are best, but a spreadsheet or clear label photos are enough to start.":"Complete what you know. We will follow up for anything else."}</p><div className="form-grid"><label>Full name<input required name="Name" autoComplete="name"/></label><label>{individualFriendly?"Company (optional)":"Company"}<input required={!individualFriendly} name="Company" autoComplete="organization"/></label></div><div className="form-grid"><label>Email<input required type="email" name="Email" autoComplete="email"/></label><InternationalPhoneField/></div>
 {isBuy&&<><label>What do you want to buy?<select name="Buying category"><option>Apple systems and service parts</option><option>Servers, storage or networking</option><option>Memory, SSDs, CPUs or GPUs</option><option>AI and data-center hardware</option><option>Wholesale or recurring requirement</option><option>Mixed request / not sure</option></select></label><div className="form-grid"><label>Manufacturer or platform<input name="Preferred platform" placeholder="Manufacturer, family or model"/></label><label>Quantity<input name="Quantity" placeholder="e.g. 25 systems or 100 DIMMs"/></label></div></>}
 {isSell&&<><div className="form-grid"><label>What are you selling?<select name="Equipment category" defaultValue={sellerFocus?"RAM / memory":"Apple computers or parts"}><option>RAM / memory</option><option>SSDs / storage</option><option>RAM and SSDs</option><option>GPUs / AI accelerators</option><option>Apple computers or parts</option><option>Servers or networking</option><option>Mixed lot / other equipment</option></select></label><label>Condition<select name="Condition"><option>New / sealed</option><option>Tested working</option><option>Working pulls</option><option>Untested</option><option>Mixed condition</option></select></label></div><div className="form-grid seller-spec-grid"><label>Manufacturer<input name="Manufacturer" placeholder="Samsung, Micron, SK hynix…"/></label><label>Part number<input name="Part number" placeholder="Exact label part number"/></label><label>Capacity / type<input name="Capacity and type" placeholder="32GB DDR4 or 1.92TB NVMe"/></label><label>Quantity<input name="Quantity" placeholder="Number of pieces"/></label></div></>}
 <label>{isBuy?"Specifications, part numbers or required capability":isSell?"Additional part numbers, quantities or notes":type==="quote"?"How can we help?":"Describe the equipment for consignment"}<textarea required name={isSell?"Inventory":"Specifications and requirements"} rows={sellerFocus?4:6} placeholder={isSell?"List additional part numbers and quantities, testing status, packaging or anything else we should know.":"Include manufacturer, model or part number, quantity, condition, location and timing."}/></label><div className="form-grid"><label>{isBuy?"Needed by":"Preferred timing"}<input name="Timing" placeholder="Date or timeframe"/></label><label>Equipment or delivery location<input name="Location" placeholder="City and state"/></label></div><label>Attach an inventory spreadsheet or photos<input type="file" name="Attachments" multiple accept=".pdf,.csv,.xls,.xlsx,.doc,.docx,.jpg,.jpeg,.png"/><small>Up to 5 files, 10MB each. No spreadsheet? Clear label photos are fine.</small></label><label className="check"><input type="checkbox" required/> I authorize Mac2MacOnline to contact me about this inquiry.</label><button className="button form-submit" disabled={submitting} type="submit">{submitting?"Submitting…":sellerFocus?"Send My RAM or SSD List":`Submit ${labels[type]}`}</button><p className="form-note" data-state={state}>{status}</p></form>;
}
