"use client";
import {FormEvent,useState} from "react";
import InternationalPhoneField from "@/components/InternationalPhoneField";
type InquiryType="buy"|"sell"|"quote"|"consignment";
const ENDPOINT="/api/inquiries";
const labels={buy:"Want to Buy",sell:"Want to Sell",quote:"Request a Quote",consignment:"Consignment Review"};
export default function InquiryForm({type}:{type:InquiryType}){const[status,setStatus]=useState("Your request and attachments will be submitted securely.");const[state,setState]=useState("");const[submitting,setSubmitting]=useState(false);const isBuy=type==="buy",isSell=type==="sell";
async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const files=Array.from(form.querySelector<HTMLInputElement>('input[type="file"]')?.files||[]);if(files.length>5){setState("error");setStatus("Please attach no more than five files.");return}if(files.some(f=>f.size>10*1024*1024)){setState("error");setStatus("Each attachment must be 10MB or smaller.");return}setSubmitting(true);setState("working");setStatus(files.length?"Securely uploading your files…":"Securely sending your request…");try{const response=await fetch(ENDPOINT,{method:"POST",body:new FormData(form)});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||"The request could not be submitted.");form.reset();setState("success");setStatus(`Thank you. Your request was received. Reference: ${result.reference||"submitted"}`)}catch(error){setState("error");setStatus(error instanceof Error?error.message:"We could not submit your request. Please try again.")}finally{setSubmitting(false)}}
return <form className={`inquiry-form ${isBuy?"dark-form":""}`} onSubmit={submit} encType="multipart/form-data"><input type="hidden" name="Inquiry type" value={isBuy?"want-to-buy":isSell?"want-to-sell":type}/><input type="hidden" name="Website source" value="Mac2MacOnline"/><label className="form-trap" aria-hidden="true">Website<input name="Website" tabIndex={-1} autoComplete="off"/></label><h2>{labels[type]}</h2><p>Complete what you know. We will follow up for anything else.</p><div className="form-grid"><label>Full name<input required name="Name" autoComplete="name"/></label><label>Company<input required name="Company" autoComplete="organization"/></label></div><div className="form-grid"><label>Email<input required type="email" name="Email" autoComplete="email"/></label><InternationalPhoneField/></div>
{isBuy&&<><label>What do you want to buy?<select name="Buying category"><option>Apple systems and service parts</option><option>Servers, storage or networking</option><option>Memory, SSDs, CPUs or GPUs</option><option>AI and data-center hardware</option><option>Wholesale or recurring requirement</option><option>Mixed request / not sure</option></select></label><div className="form-grid"><label>Manufacturer or platform<input name="Preferred platform" placeholder="Manufacturer, family or model"/></label><label>Quantity<input name="Quantity" placeholder="e.g. 25 systems or 100 DIMMs"/></label></div></>}
{isSell&&<div className="form-grid"><label>Request type<select name="Request type"><option>Sell equipment outright</option><option>Trade in toward a purchase</option><option>Evaluate both options</option></select></label><label>Equipment category<select name="Equipment category"><option>Apple computers or parts</option><option>Servers, storage or networking</option><option>Memory, SSDs, CPUs or GPUs</option><option>AI and data-center hardware</option><option>Mixed lot</option></select></label></div>}
<label>{isBuy?"Specifications, part numbers or required capability":isSell?"Manufacturer, part numbers and quantities":type==="quote"?"How can we help?":"Describe the equipment for consignment"}<textarea required name={isSell?"Inventory":"Specifications and requirements"} rows={6} placeholder="Include manufacturer, model or part number, quantity, condition, location and timing."/></label><div className="form-grid"><label>{isBuy?"Needed by":"Preferred timing"}<input name="Timing" placeholder="Date or timeframe"/></label><label>Equipment or delivery location<input name="Location" placeholder="City and state"/></label></div><label>Attach an inventory list, specification or photos<input type="file" name="Attachments" multiple accept=".pdf,.csv,.xls,.xlsx,.doc,.docx,.jpg,.jpeg,.png"/><small>Up to 5 files, 10MB each. PDF, Excel, CSV, Word, JPG or PNG.</small></label><label className="check"><input type="checkbox" required/> I authorize Mac2MacOnline to contact me about this inquiry.</label><button className="button form-submit" disabled={submitting} type="submit">{submitting?"Submitting…":`Submit ${labels[type]}`}</button><p className="form-note" data-state={state}>{status}</p></form>}
