"use client";
import {useEffect,useState} from "react";
import type {PddSession} from "../lib/pdd-auth";

type Deal={deal_number:string;direction:string;category:string;title:string;quantity:number;closes_at:string};
type Preview={subject:string;summary:{total:number;selling:number;buying:number;categories:number};deals:Deal[]};
type Audience={id:string;name:string;member_count:number};
const defaultSenderEmail="frankie@mac2maconline.com";
const normalizedAudienceName=(value:string)=>value.toLowerCase().replace(/[’‘]/g,"'").trim();

export default function MailchimpCampaignBuilder({session}:{session:PddSession}){
 const [preview,setPreview]=useState<Preview|null>(null),[audiences,setAudiences]=useState<Audience[]>([]),[frankieAudienceFound,setFrankieAudienceFound]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("Loading the current Live Bid Board…"),[error,setError]=useState("");
 const [subject,setSubject]=useState(""),[previewText,setPreviewText]=useState(""),[headline,setHeadline]=useState(""),[body,setBody]=useState(""),[buttonLabel,setButtonLabel]=useState(""),[buttonUrl,setButtonUrl]=useState(""),[senderEmail,setSenderEmail]=useState(defaultSenderEmail),[audienceId,setAudienceId]=useState(""),[showCustomPreview,setShowCustomPreview]=useState(false);
 async function request(action:string,payload:Record<string,unknown>={}){setBusy(true);setError("");try{const response=await fetch("/api/admin/mailchimp",{method:"POST",headers:{Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({action,...payload})}),data=await response.json().catch(()=>({})) as Record<string,any>;if(!response.ok)throw new Error(String(data.error||"Mailchimp could not prepare the campaign."));return data}catch(reason){setError(reason instanceof Error?reason.message:"Mailchimp could not prepare the campaign.");return null}finally{setBusy(false)}}
 async function refreshLbb(){const data=await request("lbb_campaign_preview");if(data){setPreview(data as Preview);setMessage("")}}
 useEffect(()=>{void (async()=>{await refreshLbb();const data=await request("campaign_options");if(data){const nextAudiences=(data.audiences||[]) as Audience[];setAudiences(nextAudiences);const frankieContacts=nextAudiences.find(audience=>normalizedAudienceName(audience.name)==="frankie's contacts");setFrankieAudienceFound(Boolean(frankieContacts));setAudienceId(frankieContacts?.id||String(data.connectedAudienceId||""))}})()},[]);
 async function createLbb(){if(!preview||!window.confirm(`Create a Mailchimp draft containing all ${preview.summary.total} current Live Bid Board deals? Nothing will be sent automatically.`))return;const data=await request("lbb_campaign_create",{senderEmail,audienceId});if(data)setMessage(String(data.message))}
 async function createCustom(){if(!window.confirm("Create this custom blast as a Mailchimp draft? Nothing will be sent automatically."))return;const data=await request("campaign_create",{subject,previewText,title:headline,message:body,buttonLabel,buttonUrl,senderEmail,audienceId});if(data)setMessage(String(data.message))}
 return <>
  <section className="mailchimpConnectionBox mailchimpCampaignBox"><div className="mailchimpCardHeader"><div><span>LIVE BID BOARD EMAIL</span><h2>Create LBB Mailchimp Post</h2></div><b className="integrationStatus connected">Draft only</b></div><p className="mailchimpIntro">This creates the current Live Bid Board as a formatted Mailchimp email matching the manual version. It is saved as a draft in Mailchimp for review and sending.</p>
   {preview&&<><div className="mailchimpSummary"><article><strong>{preview.summary.total}</strong><span>Active deals</span></article><article><strong>{preview.summary.selling}</strong><span>Want to Sell</span></article><article><strong>{preview.summary.buying}</strong><span>Want to Buy</span></article><article><strong>{preview.summary.categories}</strong><span>Categories</span></article></div><div className="mailchimpCampaignForm"><label>From email<input type="email" value={senderEmail} onChange={event=>setSenderEmail(event.target.value)}/></label><label>Mailchimp address book<select value={audienceId} onChange={event=>setAudienceId(event.target.value)}>{audiences.map(audience=><option key={audience.id} value={audience.id}>{audience.name} ({audience.member_count.toLocaleString()})</option>)}</select>{audiences.length>0&&!frankieAudienceFound&&<small>The address book named Frankie&apos;s Contacts was not found. Select the correct address book.</small>}</label></div><div className="lbbMailchimpPreview"><small>EMAIL SUBJECT</small><b>{preview.subject}</b><div>{preview.deals.map(deal=><span key={deal.deal_number}><strong>{deal.deal_number}</strong>{deal.title} · {Number(deal.quantity||0).toLocaleString()} pcs</span>)}</div></div><div className="mailchimpFormActions"><button type="button" className="button secondary" disabled={busy} onClick={()=>void refreshLbb()}>Refresh LBB Preview</button><button type="button" className="button" disabled={busy||!preview.summary.total||!senderEmail.trim()||!audienceId} onClick={()=>void createLbb()}>{busy?"Creating Draft…":"Create LBB Draft in Mailchimp"}</button></div></>}
  </section>
  <section className="mailchimpConnectionBox mailchimpCampaignBox"><div className="mailchimpCardHeader"><div><span>CUSTOM EMAIL</span><h2>Build a Custom Mailchimp Blast</h2></div><b className="integrationStatus connected">Draft only</b></div><p className="mailchimpIntro">Create any announcement or offer and save it as a Mailchimp draft. You will review and send it from Mailchimp.</p>
   <div className="mailchimpCampaignForm"><label>From email<input type="email" value={senderEmail} onChange={event=>setSenderEmail(event.target.value)}/></label><label>Mailchimp address book<select value={audienceId} onChange={event=>setAudienceId(event.target.value)}>{audiences.map(audience=><option key={audience.id} value={audience.id}>{audience.name} ({audience.member_count.toLocaleString()})</option>)}</select>{audiences.length>0&&!frankieAudienceFound&&<small>The address book named Frankie&apos;s Contacts was not found. Select the correct address book.</small>}</label><label>Subject line *<input maxLength={150} value={subject} onChange={event=>setSubject(event.target.value)}/></label><label>Preview text<input maxLength={150} value={previewText} onChange={event=>setPreviewText(event.target.value)}/></label><label>Headline *<input maxLength={180} value={headline} onChange={event=>setHeadline(event.target.value)}/></label><label className="wide">Message *<textarea rows={8} maxLength={20000} value={body} onChange={event=>setBody(event.target.value)}/></label><label>Button label<input maxLength={80} value={buttonLabel} onChange={event=>setButtonLabel(event.target.value)} placeholder="View Current Deals"/></label><label>Button link<input type="url" value={buttonUrl} onChange={event=>setButtonUrl(event.target.value)} placeholder="https://mac2maconline.com/"/></label></div>
   <div className="mailchimpFormActions"><button type="button" className="button secondary" onClick={()=>setShowCustomPreview(value=>!value)}>{showCustomPreview?"Close Preview":"Preview Custom Blast"}</button><button type="button" className="button" disabled={busy||!audienceId||!senderEmail.trim()||!subject.trim()||!headline.trim()||!body.trim()} onClick={()=>void createCustom()}>{busy?"Creating Draft…":"Create Custom Draft in Mailchimp"}</button></div>
   {showCustomPreview&&<div className="mailchimpEmailPreview"><small>SUBJECT: {subject||"Campaign subject"}</small><h2>{headline||"Campaign headline"}</h2>{body.split(/\n{2,}/).filter(Boolean).map((text,index)=><p key={index}>{text}</p>)}{buttonLabel&&buttonUrl&&<a href={buttonUrl} onClick={event=>event.preventDefault()}>{buttonLabel}</a>}<footer>Mac2MacOnline · 1420 Locust Street · Chico, CA 95928</footer></div>}
  </section>
  {error&&<p className="mailchimpFormMessage error" role="alert">{error}</p>}{message&&<p className="mailchimpFormMessage success" role="status">{message}</p>}
 </>
}
