"use client";
import {useEffect,useState} from "react";
import type {PddSession} from "../lib/pdd-auth";

type Deal={deal_number:string;direction:string;category:string;title:string;quantity:number;closes_at:string};
type Preview={subject:string;summary:{total:number;selling:number;buying:number;categories:number};deals:Deal[]};
export default function MailchimpCampaignBuilder({session}:{session:PddSession}){
 const [preview,setPreview]=useState<Preview|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("Loading the current Live Bid Board…"),[error,setError]=useState("");
 async function request(action:"lbb_campaign_preview"|"lbb_campaign_create"){setBusy(true);setError("");try{const response=await fetch("/api/admin/mailchimp",{method:"POST",headers:{Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({action})}),data=await response.json().catch(()=>({})) as Record<string,any>;if(!response.ok)throw new Error(String(data.error||"The Live Bid Board campaign could not be prepared."));if(action==="lbb_campaign_preview"){setPreview(data as Preview);setMessage("")}else{setMessage(String(data.message));setPreview(null)}return data}catch(reason){setError(reason instanceof Error?reason.message:"The Live Bid Board campaign could not be prepared.");return null}finally{setBusy(false)}}
 useEffect(()=>{void request("lbb_campaign_preview")},[]);
 async function create(){if(!preview||!window.confirm(`Create a Mailchimp draft containing all ${preview.summary.total} current Live Bid Board deals? Nothing will be sent automatically.`))return;await request("lbb_campaign_create")}
 return <section className="mailchimpConnectionBox mailchimpCampaignBox"><div className="mailchimpCardHeader"><div><span>LIVE BID BOARD EMAIL</span><h2>Create LBB Mailchimp Post</h2></div><b className="integrationStatus connected">Draft only</b></div><p className="mailchimpIntro">This creates the current Live Bid Board as a formatted Mailchimp email like the manual version. It will be saved as a draft in Mailchimp for you to review and send.</p>
  {preview&&<><div className="mailchimpSummary"><article><strong>{preview.summary.total}</strong><span>Active deals</span></article><article><strong>{preview.summary.selling}</strong><span>Want to Sell</span></article><article><strong>{preview.summary.buying}</strong><span>Want to Buy</span></article><article><strong>{preview.summary.categories}</strong><span>Categories</span></article></div><div className="lbbMailchimpPreview"><small>EMAIL SUBJECT</small><b>{preview.subject}</b><div>{preview.deals.map(deal=><span key={deal.deal_number}><strong>{deal.deal_number}</strong>{deal.title} · {Number(deal.quantity||0).toLocaleString()} pcs</span>)}</div></div><div className="mailchimpFormActions"><button type="button" className="button secondary" disabled={busy} onClick={()=>void request("lbb_campaign_preview")}>Refresh LBB Preview</button><button type="button" className="button" disabled={busy||!preview.summary.total} onClick={()=>void create()}>{busy?"Creating Draft…":"Create LBB Draft in Mailchimp"}</button></div></>}
  {error&&<p className="mailchimpFormMessage error" role="alert">{error}</p>}{message&&<p className="mailchimpFormMessage success" role="status">{message}</p>}
 </section>
}
