"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import * as XLSX from "@e965/xlsx";
import {Shell} from "../../../components/SiteShell";
import {clearPddSession,currentPddSession,type PddSession} from "../../../lib/pdd-auth";
import "./imei-checker.css";

type Deal={id:string;po_number:string;customer:string};
type Device={model:string;serialNumber:string;activationStatus:string;warrantyStatus:string;estimatedPurchaseDate:string;coverageEndDate:string;technicalSupport:string;repairsServiceCoverage:string;appleCareEligible:string;replacedByApple:string;findMyStatus:string;mdmLockStatus:string;lockedCarrier:string;simLockStatus:string;orderId:string;price:string;duration:string};
type Result={id:string;deal_id:string;identifier:string;service_id:string;service_name:string;response:Record<string,unknown>;device:Device;response_status:string;checked_by:string;checked_at:string;cached?:boolean;syncedToR2?:boolean};
const deviceFields:Array<[keyof Device,string]>=[["activationStatus","Activation status"],["warrantyStatus","Warranty status"],["estimatedPurchaseDate","Estimated purchase date"],["coverageEndDate","Coverage end date"],["technicalSupport","Telephone technical support"],["repairsServiceCoverage","Repairs and service coverage"],["appleCareEligible","AppleCare eligible"],["replacedByApple","Replaced by Apple"],["findMyStatus","Find My Mac"],["mdmLockStatus","MDM lock status"],["lockedCarrier","Locked carrier"],["simLockStatus","SIM-lock status"]];
const cleanList=(value:string)=>[...new Set(value.split(/[\s,;]+/).map(item=>item.replace(/[-\s]/g,"").toUpperCase()).filter(Boolean))];

export default function ImeiChecker(){
 const [session,setSession]=useState<PddSession|null>(null),[configured,setConfigured]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[identifiers,setIdentifiers]=useState(""),[dealId,setDealId]=useState(""),[deals,setDeals]=useState<Deal[]>([]),[results,setResults]=useState<Result[]>([]),[message,setMessage]=useState("");
 const headers=useMemo(()=>session?{Authorization:`Bearer ${session.access_token}`}:{},[session]);
 async function load(active:PddSession,selectedDeal=""){
  const auth={Authorization:`Bearer ${active.access_token}`},[history,r2]=await Promise.all([fetch(`/api/admin/imei-checker${selectedDeal?`?deal=${encodeURIComponent(selectedDeal)}`:""}`,{headers:auth,cache:"no-store"}),fetch("/api/admin/r2-processing",{headers:auth,cache:"no-store"})]);
  if(history.status===401||r2.status===401){clearPddSession();window.location.replace("/employee-login?return_to=/employee/imei-checker");return}
  const data=await history.json().catch(()=>({})),r2Data=await r2.json().catch(()=>({}));setConfigured(Boolean(data.configured));setResults(data.results||[]);setDeals(r2Data.deals||[]);setLoading(false);
 }
 useEffect(()=>{void(async()=>{const active=await currentPddSession();if(!active){window.location.replace("/employee-login?return_to=/employee/imei-checker");return}setSession(active);const selected=new URLSearchParams(window.location.search).get("deal")||"";setDealId(selected);await load(active,selected)})()},[]);
 async function submit(event:FormEvent){event.preventDefault();if(!session)return;const list=cleanList(identifiers);if(!list.length)return;setBusy(true);setMessage("");const response=await fetch("/api/admin/imei-checker",{method:"POST",headers:{...headers,"Content-Type":"application/json"},body:JSON.stringify({dealId,identifiers:list})}),data=await response.json().catch(()=>({}));if(!response.ok)setMessage(data.error||"IMEICheck could not process the request.");else{const reused=(data.results||[]).filter((row:Result)=>row.cached).length;setIdentifiers("");setMessage(`${data.results.length} ${data.results.length===1?"device":"devices"} checked${reused?` · ${reused} previous result${reused===1?"":"s"} reused at no charge`:""}.`);await load(session,dealId)}setBusy(false)}
 async function chooseFile(file?:File){if(!file)return;try{const book=XLSX.read(await file.arrayBuffer(),{type:"array"}),values=book.SheetNames.flatMap(name=>XLSX.utils.sheet_to_json<unknown[]>(book.Sheets[name],{header:1,defval:""})).flat().map(value=>String(value).trim()).filter(value=>/^[A-Za-z0-9\s-]{8,24}$/.test(value)),list=cleanList(values.join("\n"));if(!list.length)throw new Error("No IMEI or serial-number values were found.");setIdentifiers(list.join("\n"));setMessage(`${list.length} unique values loaded from ${file.name}. Review them, then run the check.`)}catch(error){setMessage(error instanceof Error?error.message:"The spreadsheet could not be read.")}}
 function download(){const known=(value:string)=>value||"Not Known",rows=results.map(result=>({"IMEI / Serial":result.identifier,"Model":known(result.device.model),"Activation Status":known(result.device.activationStatus),"Warranty Status":known(result.device.warrantyStatus),"Estimated Purchase Date":known(result.device.estimatedPurchaseDate),"Coverage End Date":known(result.device.coverageEndDate),"Telephone Technical Support":known(result.device.technicalSupport),"Repairs and Service Coverage":known(result.device.repairsServiceCoverage),"AppleCare Eligible":known(result.device.appleCareEligible),"Replaced by Apple":known(result.device.replacedByApple),"Find My Mac":known(result.device.findMyStatus),"MDM Lock Status":known(result.device.mdmLockStatus),"Locked Carrier":known(result.device.lockedCarrier),"SIM-Lock Status":known(result.device.simLockStatus),"R2 Deal":deals.find(deal=>deal.id===result.deal_id)?.po_number||"","Service":result.service_name,"Price":result.device.price,"Order ID":result.device.orderId,"Checked":new Date(result.checked_at).toLocaleString(),"Checked By":result.checked_by})),sheet=XLSX.utils.json_to_sheet(rows),book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,sheet,"IMEI Results");XLSX.writeFile(book,`M2M_IMEI_Results_${new Date().toISOString().slice(0,10)}.xlsx`)}
 if(loading)return <Shell><main className="imeiPage"><p>Loading IMEI checker…</p></main></Shell>;
 return <Shell><main className="imeiPage"><header><div><p className="eyebrow">DEAL WORKBOOK · R2 PROCESSING</p><h1>IMEI &amp; Serial Checker</h1><p>Run Apple Full Info + Carrier checks and keep results with the R2 processing record.</p></div><a className="button secondary" href="/employee">Back to workbook</a></header>
 <section className="imeiConnection"><div><span>IMEICHECK.COM</span><h2>Service 39 · Apple Full Info [+Carrier] A-updated</h2><p>Current ordering price: $0.12 per device. Previous results are reused automatically to prevent duplicate charges.</p></div><b className={configured?"connected":"notConnected"}>{configured?"API key configured":"API key required"}</b></section>
 <form className="imeiCheckForm" onSubmit={submit}><label>Attach to R2 deal (optional)<select value={dealId} onChange={event=>{setDealId(event.target.value);if(session)void load(session,event.target.value)}}><option value="">Not attached to a deal</option>{deals.map(deal=><option key={deal.id} value={deal.id}>{deal.po_number} · {deal.customer}</option>)}</select></label><label className="wide">IMEI or serial numbers<textarea value={identifiers} onChange={event=>setIdentifiers(event.target.value)} placeholder="Enter one IMEI or serial number per line" required/></label><div className="imeiActions"><label className="button secondary">Upload XLSX, XLS or CSV<input type="file" accept=".xlsx,.xls,.csv" onChange={event=>void chooseFile(event.target.files?.[0])}/></label><button className="button" disabled={!configured||busy}>{busy?"Checking…":`Run ${cleanList(identifiers).length||""} Check${cleanList(identifiers).length===1?"":"s"}`}</button></div></form>
 {message&&<p className={`imeiMessage${/could not|invalid|required|no imei/i.test(message)?" error":""}`} role="status">{message}</p>}
 <section className="imeiHistory"><header><div><span>SAVED RESULTS</span><h2>{dealId?"Results for selected R2 deal":"Recent IMEI checks"}</h2></div><button className="button secondary" onClick={download} disabled={!results.length}>Download XLSX</button></header>{results.length?<div className="imeiResultCards">{results.map(result=><article key={result.id}><header><div><span>{result.identifier}</span><h3>{result.device.model||"Not Known"}</h3></div><span className={`imeiStatus ${result.response_status}`}>{result.response_status}</span></header><dl>{deviceFields.map(([key,label])=><div key={key}><dt>{label}</dt><dd>{result.device[key]||"Not Known"}</dd></div>)}</dl><footer><span>{deals.find(deal=>deal.id===result.deal_id)?.po_number||"Not attached to an R2 deal"}</span><span>{result.syncedToR2?"Saved to serialized R2 item":result.deal_id?"No matching serialized R2 item":"History only"}</span><span>{new Date(result.checked_at).toLocaleString()} · {result.checked_by}</span></footer></article>)}</div>:<p className="imeiEmpty">No checks have been saved for this selection.</p>}</section>
 </main></Shell>
}
