import {PageHero,Shell} from "@/components/SiteShell";

export const metadata={title:"M2M R2 Grading",description:"Mac2MacOnline's R2-aligned ITAD reference for processing, data sanitization, cosmetic condition C0-C9 and functionality F1-F6.",alternates:{canonical:"/m2m-r2-grading"}};
const cosmetic=[["C0","Not categorized","Not yet evaluated or assigned."],["C1","Damaged","Not reusable; designated for materials recovery."],["C2","Used Poor","Heavy wear or damage; critical parts may be missing."],["C3","Used Fair","Moderate wear; dents, scratches, discoloration, damage or some missing noncritical parts may be present."],["C4","Used Good","Normal surface wear or small dents; no damaged hinges, latches or missing parts."],["C5","Used Very Good","Minor cosmetic imperfections from use; complete with no missing parts."],["C6","Used Excellent","Excellent, fully cleaned condition with only light normal wear and no missing parts."],["C7","Certified Pre-Owned","Seller- or manufacturer-refurbished to like-new condition, with warranty and no blemishes or missing parts."],["C8","Unused","New and unused, removed from original packaging, with no wear or alteration."],["C9","New Open Box","New and unused in original packaging with broken factory seals and no wear or alteration."]];
const functional=[["F1","Collectible or Specialty","Rare, vintage or specialized equipment considered viable for reuse or parts; defects or missing parts may exist."],["F2","Verified Specialty Electronics","Removed from operation with no known defects, corrosion or missing parts; identifying numbers verified."],["F3","Key Functions Working","Expected primary functions were tested; secondary functions may be untested, and nonessential missing parts must be disclosed."],["F4","Hardware Functional","All hardware was tested and works; no missing, damaged or defective hardware. Software may not be configured."],["F5","Refurbished","All functions were tested, licensed software is configured, results are available, and no defects remain."],["F6","Like New","Fully tested, restored with original OEM parts, configured to OEM specifications and free of defects."]];
export default function ItadR2Grading(){return <Shell><PageHero eyebrow="M2M EQUIPMENT EVALUATION" title="R2 Equipment Grading Guide" intro="A practical reference for recording an asset's R2 processing category, data-sanitization status, cosmetic condition and tested functionality throughout IT asset disposition."/><main className="r2GradingPage">
<section className="wrap r2GradeIntro"><div><span className="eyebrow">FOUR PART RECORD</span><h2>One grade does not tell the whole story.</h2><p>Equipment is first controlled according to its processing state. Data-bearing devices receive a separate sanitization status. Products prepared for reuse are then described with both a cosmetic C grade and a functional F grade.</p></div><aside><strong>Example final description</strong><b>F4 / C5</b><span>Hardware Functional / Used Very Good</span><small>Data sanitized with software</small></aside></section>
<section className="r2GradeDark"><div className="wrap"><div className="r2GradeHeading"><span className="eyebrow">STEP 1</span><h2>R2 processing category</h2><p>Received equipment remains in an unknown state until it is sorted, evaluated and processed.</p></div><div className="r2ProcessGrid"><article><h3>R2 controlled streams</h3><ul><li>Unevaluated equipment, components and materials</li><li>Unsanitized devices or media</li><li>Equipment requiring test and repair</li><li>Focus-material-containing equipment and focus materials</li></ul></article><article><h3>Unrestricted streams</h3><ul><li>New equipment in unopened original OEM packaging</li><li>Non-electronic equipment and non-focus materials</li><li>Documented planned returns, including warranty, recall, errant shipment or nonconforming delivery</li></ul></article></div></div></section>
<section className="wrap r2Sanitization"><div className="r2GradeHeading"><span className="eyebrow">STEP 2</span><h2>Data-sanitization status</h2></div><div className="r2ProcessGrid"><article><h3>Pre-sanitization</h3><p>Requires data evaluation and/or sanitization.</p><ul><li>Not evaluated - presence of data unknown</li><li>Contains data - sanitization required</li></ul></article><article><h3>Sanitized or non-data</h3><p>Free of data-storage risk for the recorded disposition.</p><ul><li>Non-data device</li><li>Evaluated as not containing data</li><li>Sanitized through physical destruction</li><li>Sanitized with software</li></ul></article></div></section>
<section className="r2GradeTables"><div className="wrap"><div className="r2GradeHeading"><span className="eyebrow">STEP 3</span><h2>Cosmetic categories C0-C9</h2><p>Cosmetic grades describe physical condition and appearance; they do not establish functionality.</p></div><div className="r2GradeTable">{cosmetic.map(([code,title,description])=><article key={code}><b>{code}</b><h3>{title}</h3><p>{description}</p></article>)}</div></div></section>
<section className="wrap r2FunctionSection"><div className="r2GradeHeading"><span className="eyebrow">STEP 4</span><h2>Functionality categories F1-F6</h2><p>Functional grades record testing, verified operation, software readiness and disclosed defects or missing parts.</p></div><div className="r2FunctionGrid">{functional.map(([code,title,description])=><article key={code}><b>{code}</b><h3>{title}</h3><p>{description}</p></article>)}</div></section>
<section className="r2GradeNotice"><div className="wrap"><strong>Important R2 terminology</strong><p>R2 certification applies to a certified facility and its audited processes—not to individual equipment or components. Product records should state the assigned categories without claiming the equipment itself is “R2 certified.”</p><small>Reference: SERI, R2 Equipment Categorization (REC), Version 1.0, effective July 1, 2020. This is a concise operational reference; the governing standard and facility procedures control.</small></div></section>
</main></Shell>}
