"use client";
export type OrderPdfLine={line:number|string;description:string;quantity:number;unitPrice:number;total:number};
export type OrderPdfData={kind:"PURCHASE ORDER"|"SALES ORDER";orderNumber:string;dealNumber:string;partyLabel:"Vendor"|"Customer";partyName:string;contact?:string;email?:string;phone?:string;address?:string;generatedBy?:string;lines:OrderPdfLine[];total:number;notes?:string[];fileBase:string};
const ascii=(value:unknown)=>String(value??"").normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^\x20-\x7E]/g,"-");
const pdfText=(value:unknown)=>ascii(value).replace(/\\/g,"\\\\").replace(/\(/g,"\\(").replace(/\)/g,"\\)");
const money=(value:number)=>value.toLocaleString("en-US",{style:"currency",currency:"USD"});
const wrap=(value:string,width:number)=>{const words=ascii(value).split(/\s+/),lines:string[]=[];let current="";for(const word of words){const next=current?current+" "+word:word;if(next.length<=width)current=next;else{if(current)lines.push(current);current=word.slice(0,width)}}if(current)lines.push(current);return lines.length?lines:[""]};
function pageContent(data:OrderPdfData,pageLines:OrderPdfLine[],page:number,pages:number){
 const out:string[]=["0.08 0.2 0.34 rg","BT","/F2 17 Tf","42 748 Td","("+pdfText("SIERRA CIRCUIT REPAIR, INC. dba Mac2MacOnline")+") Tj","/F1 9 Tf","0 -16 Td","(Wholesale Technology Remarketing) Tj","ET","0.11 0.44 0.72 rg","42 690 528 34 re f","1 1 1 rg","BT","/F2 17 Tf","52 701 Td","("+data.kind+") Tj","ET","0 0 0 rg"];
 const meta=[[data.partyLabel+":",data.partyName],["Contact:",data.contact||""],["Email:",data.email||""],["Phone:",data.phone||""],["Address:",data.address||""],["Order Number:",data.orderNumber],["Deal Number:",data.dealNumber],["Date:",new Intl.DateTimeFormat("en-US",{year:"numeric",month:"long",day:"numeric"}).format(new Date())],["Prepared By:",data.generatedBy||""]];
 let y=670;for(const [label,value] of meta){if(!value)continue;out.push("BT","/F2 9 Tf","42 "+y+" Td","("+pdfText(label)+") Tj","/F1 9 Tf","78 0 Td","("+pdfText(value).slice(0,88)+") Tj","ET");y-=13}
 y-=8;out.push("0.90 0.94 0.97 rg","42 "+(y-18)+" 528 22 re f","0 0 0 rg","BT","/F2 8 Tf","46 "+(y-11)+" Td","(LINE) Tj","32 0 Td","(DESCRIPTION) Tj","294 0 Td","(QTY) Tj","52 0 Td","(UNIT PRICE) Tj","70 0 Td","(TOTAL) Tj","ET");y-=29;
 for(const line of pageLines){const desc=wrap(line.description,51).slice(0,2),height=desc.length>1?34:22,separatorY=y-height+11;out.push("0.82 0.87 0.91 RG","42 "+separatorY+" m 570 "+separatorY+" l S","0 0 0 rg","BT","/F1 8 Tf","46 "+y+" Td","("+pdfText(line.line)+") Tj","32 0 Td","("+pdfText(desc[0])+") Tj","294 0 Td","("+pdfText(line.quantity)+") Tj","52 0 Td","("+pdfText(money(line.unitPrice))+") Tj","70 0 Td","("+pdfText(money(line.total))+") Tj","ET");if(desc[1])out.push("BT","/F1 8 Tf","78 "+(y-11)+" Td","("+pdfText(desc[1])+") Tj","ET");y-=height}
 if(page===pages){y-=8;out.push("0.11 0.44 0.72 rg","390 "+(y-28)+" 180 32 re f","1 1 1 rg","BT","/F2 12 Tf","402 "+(y-8)+" Td","(TOTAL) Tj","56 0 Td","("+pdfText(money(data.total))+") Tj","ET","0 0 0 rg");y-=48;for(const note of data.notes||[])for(const line of wrap(note,90)){out.push("BT","/F1 8 Tf","42 "+y+" Td","("+pdfText(line)+") Tj","ET");y-=11}}
 out.push("0.45 0.52 0.58 rg","BT","/F1 8 Tf","42 28 Td","("+pdfText("Mac2MacOnline | "+data.orderNumber)+") Tj","468 0 Td","("+page+" / "+pages+") Tj","ET");return out.join("\n");
}
export function createOrderPdfBlob(data:OrderPdfData){
 const perPage=13,pages=Math.max(1,Math.ceil(data.lines.length/perPage)),objects:string[]=[],pageIds=Array.from({length:pages},(_,index)=>5+index*2);objects[1]="<< /Type /Catalog /Pages 2 0 R >>";objects[2]="<< /Type /Pages /Kids ["+pageIds.map(id=>id+" 0 R").join(" ")+"] /Count "+pages+" >>";objects[3]="<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>";objects[4]="<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>";
 for(let index=0;index<pages;index++){const pageId=pageIds[index],streamId=pageId+1,stream=pageContent(data,data.lines.slice(index*perPage,(index+1)*perPage),index+1,pages);objects[pageId]="<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents "+streamId+" 0 R >>";objects[streamId]="<< /Length "+new TextEncoder().encode(stream).length+" >>\nstream\n"+stream+"\nendstream"}
 let pdf="%PDF-1.4\n",offsets=[0];for(let id=1;id<objects.length;id++){offsets[id]=new TextEncoder().encode(pdf).length;pdf+=id+" 0 obj\n"+objects[id]+"\nendobj\n"}const xref=new TextEncoder().encode(pdf).length;pdf+="xref\n0 "+objects.length+"\n0000000000 65535 f \n";for(let id=1;id<objects.length;id++)pdf+=String(offsets[id]).padStart(10,"0")+" 00000 n \n";pdf+="trailer\n<< /Size "+objects.length+" /Root 1 0 R >>\nstartxref\n"+xref+"\n%%EOF";return new Blob([pdf],{type:"application/pdf"});
}
export function downloadOrderPdf(data:OrderPdfData){const link=document.createElement("a");link.href=URL.createObjectURL(createOrderPdfBlob(data));link.download=data.fileBase+".pdf";link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)}
