import InquiryForm from "@/components/InquiryForm";
import {Shell} from "@/components/SiteShell";
export const metadata={title:"Sell RAM, SSDs, GPUs & Apple Equipment",description:"Sell computer memory, SSDs, GPUs, MacBooks, iMacs and Apple equipment through R2v3 and ISO-certified technology recovery operations."};
const categories=[
 ["RAM & Memory","DDR3, DDR4 and DDR5 DIMMs, SODIMMs, ECC memory, RDIMMs and server memory. Include manufacturer, part number, capacity, speed and quantity."],
 ["SSDs & Storage","SATA SSDs, NVMe drives, enterprise SSDs and storage components. New, used, tested and clearly identified untested inventory is considered."],
 ["GPUs & Accelerators","NVIDIA and AMD graphics cards, workstation GPUs, data-center accelerators and AI hardware evaluated by exact model, memory and condition."],
 ["Apple Equipment","MacBooks, iMacs, Mac minis, Mac Studios, displays, iPads, service parts and accessories from individuals, businesses and retired fleets."],
];
export default function Page(){return <Shell><main className="partsSellPage"><section className="partsHero"><div className="wrap partsHeroGrid"><div><p className="eyebrow">SELL DIRECTLY TO MAC2MACONLINE</p><h1>Turn RAM, SSDs, GPUs and Apple equipment into value.</h1><p>Individuals, businesses and technology teams can send a list or a few clear photos. We evaluate reusable equipment for direct purchase, trade-in or responsible downstream processing.</p><div className="actions"><a className="button" href="#inventory-form">Submit Your Equipment</a><a className="button secondary" href="mailto:sales@mac2maconline.com">Email Your List</a></div></div><aside><b>FASTEST EVALUATION</b><h2>Part numbers matter.</h2><ul><li>Photograph labels clearly</li><li>Include quantities and condition</li><li>Note testing and data status</li><li>Add your city and state</li></ul></aside></div></section>
<section className="partsTrust"><div className="wrap"><div><strong>R2v3</strong><span>Responsible electronics reuse and recycling</span></div><div><strong>ISO 9001</strong><span>Quality management</span></div><div><strong>ISO 14001</strong><span>Environmental management</span></div><div><strong>ISO 45001</strong><span>Health and safety management</span></div></div></section>
<section className="wrap partsCategories"><div className="section-head"><p className="eyebrow">WHAT WE ARE ACTIVELY BUYING</p><h2>High-demand components and Apple hardware.</h2><p>Small quantities from end users and larger recurring inventories from businesses are welcome.</p></div><div>{categories.map(([title,copy])=><article key={title}><span>BUYING</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
<section className="partsSecurity"><div className="wrap"><div><p className="eyebrow">CERTIFIED OPERATIONS</p><h2>Responsible handling is part of the transaction.</h2><p>Equipment is evaluated through our R2v3 and ISO-certified operations, with documented procedures for quality, environmental responsibility, worker safety and appropriate data-bearing device handling.</p></div><div className="partsSecuritySteps"><article><b>01</b><h3>Send details</h3><p>Upload a spreadsheet or clear photos of labels and equipment condition.</p></article><article><b>02</b><h3>Receive an evaluation</h3><p>We review market demand, specifications, condition, quantity and logistics.</p></article><article><b>03</b><h3>Choose the path</h3><p>Accept a direct purchase, discuss trade-in value or arrange responsible processing.</p></article></div></div></section>
<section className="partsForm" id="inventory-form"><div className="wrap inquiry-layout"><div><p className="eyebrow">SELL YOUR EQUIPMENT</p><h2>Start with whatever information you have.</h2><p>You do not need a formal inventory spreadsheet. A photo of the part-number labels and an estimated quantity can be enough to begin.</p><div className="detail-panel"><h3>Useful details</h3><ul><li>Manufacturer and exact part number</li><li>Capacity, speed or GPU memory</li><li>Quantity and condition</li><li>Testing or lock status</li><li>Pickup or shipping location</li></ul></div></div><InquiryForm type="sell" individualFriendly/></div></section></main></Shell>}
