import Link from "next/link";
import {Shell} from "@/components/SiteShell";
import InquiryForm from "@/components/InquiryForm";
export const metadata={title:"Sell Used IT Equipment for a Wholesale Offer",description:"Sell RAM, SSDs, GPUs, Apple equipment, servers and networking hardware. Upload a list or photos for a wholesale inventory review.",alternates:{canonical:"/want-to-sell"}};
const wanted=[["RAM & server memory","DDR3, DDR4 and DDR5; ECC, RDIMM, LRDIMM, SODIMM and desktop memory."],["SSDs & storage","SATA, SAS and NVMe drives; enterprise SSDs, working pulls and excess inventory."],["Any lot size","Single high-value parts, small quantities, retired fleets and wholesale lots."],["Simple submissions","Exact part numbers are best, but clear photos or a rough inventory are welcome."]];
export default function Page(){return <Shell><main className="ramSsdWtsPage" id="top">
 <section className="ramSsdHero"><div className="wrap ramSsdHeroGrid"><div><span className="eyebrow">MAC2MACONLINE IS ACTIVELY BUYING</span><h1>Send us the technology inventory you have for sale.</h1><p>We buy RAM, enterprise SSDs, GPUs, Apple equipment, servers, networking hardware and mixed technology lots from individuals, businesses, IT departments, recyclers and wholesale suppliers.</p><div className="ramSsdHeroPoints"><span>Small quantities &amp; bulk lots</span><span>Tested or untested inventory</span><span>Sorted or mixed lots</span><span>R2v3 &amp; ISO-certified operations</span></div><p className="ramSsdMicrocopy"><strong>Send us what you have and we will generally respond with an offer within 24 hours.</strong></p><p className="ramSsdMicrocopy">No formal spreadsheet? Upload clear photos of the labels and tell us the approximate quantity. We will help identify the equipment.</p></div><InquiryForm type="sell" individualFriendly sellerFocus/></div></section>
 <section className="partsTrust"><div className="wrap"><div><strong>R2v3</strong><span>Responsible reuse and recycling</span></div><div><strong>ISO 9001</strong><span>Quality management</span></div><div><strong>ISO 14001</strong><span>Environmental management</span></div><div><strong>ISO 45001</strong><span>Health and safety management</span></div></div></section>
 <section className="ramSsdWanted"><div className="wrap"><div className="ramSsdSectionHead"><p className="eyebrow">WHAT WE WANT TO BUY</p><h2>RAM and SSD inventory in nearly every common form.</h2><p>Send the manufacturer, part number, capacity, quantity and condition when available. Missing details will not stop you from submitting a list.</p></div><div className="ramSsdWantedGrid">{wanted.map(([title,copy],index)=><article key={title}><b>0{index+1}</b><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="ramSsdCategoryLinks"><Link href="/sell-ddr4-server-ram">Sell DDR4 server RAM →</Link><Link href="/sell-ddr5-server-ram">Sell DDR5 server RAM →</Link><Link href="/sell-mixed-untested-ram">Sell mixed or untested RAM →</Link><Link href="/sell-enterprise-nvme-ssds">Sell enterprise NVMe SSDs →</Link></div></div></section>
 <section className="ramSsdProcess"><div className="wrap"><div><p className="eyebrow">A SIMPLE SELLING PROCESS</p><h2>From inventory list to purchase offer.</h2></div><ol><li><b>1</b><h3>Send your list or photos</h3><p>Upload part numbers, a spreadsheet or clear label photos.</p></li><li><b>2</b><h3>We evaluate it</h3><p>We review specifications, quantity, condition, demand and logistics.</p></li><li><b>3</b><h3>Receive an offer</h3><p>We generally respond with an offer within 24 hours.</p></li><li><b>4</b><h3>Arrange shipment</h3><p>We coordinate the next steps and document the transaction with your team.</p></li></ol></div></section>
 <section className="ramSsdTrust"><div className="wrap"><div><p className="eyebrow">WHY SELL TO MAC2MACONLINE</p><h2>Experienced hardware buyers backed by certified operations.</h2></div><div><p>Mac2MacOnline has more than 20 years of technology-market experience and understands how manufacturer, part number, capacity, condition and quantity affect resale value.</p><p>Our R2v3 and ISO 9001, ISO 14001 and ISO 45001 certified operations support responsible handling, quality management and appropriate processes for data-bearing equipment.</p><a className="button" href="#top">Submit Your Inventory Above</a></div></div></section>
 </main></Shell>}
