"use client";
import {useEffect,useMemo,useState} from "react";
import {clearPddSession,currentPddSession,pddAuthFetch,type PddSession} from "../../../lib/pdd-auth";

type Vendor={id:string;company_name:string;contact_name:string;email:string;phone:string;address1:string;address2:string;city:string;region:string;postal_code:string;country:string;created_by_name:string;created_by_email:string;updated_at:string};
type Customer={id:string;company:string;contact_name:string;email:string;phone:string;address1:string;address2:string;city:string;region:string;postal_code:string;country:string;updated_at:string;last_bid_at:string;bid_count:number;has_account:boolean;assigned_employee_name?:string;assigned_employee_email?:string};
type ContactDraft={company:string;contactName:string;email:string;phone:string;address1:string;address2:string;city:string;region:string;postalCode:string;country:string};
const emptyDraft:ContactDraft={company:"",contactName:"",email:"",phone:"",address1:"",address2:"",city:"",region:"",postalCode:"",country:"United States"};
const address=(item:{address1:string;address2:string;city:string;region:string;postal_code:string;country:string})=>[item.address1,item.address2,[item.city,item.region,item.postal_code].filter(Boolean).join(", "),item.country].filter(Boolean).join(" · ");
const date=(value:string)=>value?new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(new Date(value)):"—";

export default function ContactsDirectory(){
 const [session,setSession]=useState<PddSession|null>(null),[vendors,setVendors]=useState<Vendor[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[scope,setScope]=useState<"vendors"|"customers">("vendors"),[query,setQuery]=useState(""),[open,setOpen]=useState(""),[editing,setEditing]=useState(""),[draft,setDraft]=useState<ContactDraft>(emptyDraft),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{if(new URLSearchParams(window.location.search).get("type")==="customers")setScope("customers")},[]);
 useEffect(()=>{void(async()=>{const active=await currentPddSession();if(!active){window.location.replace("/employee-login?return_to=/employee/contacts");return}setSession(active);const headers={Authorization:`Bearer ${active.access_token}`};const [vendorResponse,customerResponse]=await Promise.all([pddAuthFetch("/rest/v1/pdd_vendors?select=id,company_name,contact_name,email,phone,address1,address2,city,region,postal_code,country,created_by_name,created_by_email,updated_at&order=company_name.asc",{headers}),fetch("/api/admin/contacts",{headers})]);if(vendorResponse.status===401||customerResponse.status===401){clearPddSession();window.location.replace("/employee-login");return}if(!vendorResponse.ok||!customerResponse.ok){setMessage("The directory could not be loaded.");setLoading(false);return}setVendors(await vendorResponse.json() as Vendor[]);setCustomers(((await customerResponse.json()) as {customers:Customer[]}).customers||[]);setLoading(false)})()},[]);
 const normalized=query.trim().toLowerCase(),visibleVendors=useMemo(()=>vendors.filter(v=>!normalized||Object.values(v).some(value=>String(value||"").toLowerCase().includes(normalized))),[vendors,normalized]),visibleCustomers=useMemo(()=>customers.filter(v=>!normalized||Object.values(v).some(value=>String(value||"").toLowerCase().includes(normalized))),[customers,normalized]),items=scope==="vendors"?visibleVendors:visibleCustomers;
 const field=(name:keyof ContactDraft,value:string)=>setDraft(current=>({...current,[name]:value}));
 function editVendor(v:Vendor){setEditing(`v-${v.id}`);setDraft({company:v.company_name,contactName:v.contact_name,email:v.email,phone:v.phone,address1:v.address1,address2:v.address2,city:v.city,region:v.region,postalCode:v.postal_code,country:v.country||"United States"});setMessage("")}
 function editCustomer(c:Customer){setEditing(`c-${c.id}`);setDraft({company:c.company,contactName:c.contact_name,email:c.email,phone:c.phone,address1:c.address1,address2:c.address2,city:c.city,region:c.region,postalCode:c.postal_code,country:c.country||"United States"});setMessage("")}
 async function saveVendor(v:Vendor){if(!session||!draft.company.trim())return;setSaving(true);setMessage("");try{const updatedAt=new Date().toISOString(),response=await pddAuthFetch(`/rest/v1/pdd_vendors?id=eq.${encodeURIComponent(v.id)}`,{method:"PATCH",headers:{Authorization:`Bearer ${session.access_token}`,Prefer:"return=representation"},body:JSON.stringify({company_name:draft.company.trim(),contact_name:draft.contactName.trim(),email:draft.email.trim(),phone:draft.phone.trim(),address1:draft.address1.trim(),address2:draft.address2.trim(),city:draft.city.trim(),region:draft.region.trim(),postal_code:draft.postalCode.trim(),country:draft.country.trim()||"United States",updated_at:updatedAt})});if(!response.ok)throw new Error("The vendor could not be updated.");const rows=await response.json() as Vendor[],saved=rows[0];if(!saved)throw new Error("The updated vendor could not be loaded.");setVendors(current=>current.map(item=>item.id===v.id?{...item,...saved}:item));setEditing("");setMessage(`${saved.company_name} was updated.`)}catch(error){setMessage(error instanceof Error?error.message:"The vendor could not be updated.")}finally{setSaving(false)}}
 async function saveCustomer(c:Customer){if(!session||!draft.company.trim())return;setSaving(true);setMessage("");try{const response=await fetch("/api/admin/contacts",{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({id:c.id,hasAccount:c.has_account,...draft})}),data=await response.json();if(!response.ok)throw new Error(data.error||"The customer could not be updated.");const saved=data.customer as Partial<Customer>;setCustomers(current=>current.map(item=>item.id===c.id?{...item,...saved}:item));setEditing("");setMessage(`${draft.company.trim()} was updated.`)}catch(error){setMessage(error instanceof Error?error.message:"The customer could not be updated.")}finally{setSaving(false)}}
 const editor=(onSave:()=>void)=><form className="contactDirectoryEditor" onSubmit={event=>{event.preventDefault();onSave()}}><label>Company<input required value={draft.company} onChange={event=>field("company",event.target.value)}/></label><label>Contact name<input value={draft.contactName} onChange={event=>field("contactName",event.target.value)}/></label><label>Email<input type="email" value={draft.email} onChange={event=>field("email",event.target.value)}/></label><label>Phone<input value={draft.phone} onChange={event=>field("phone",event.target.value)}/></label><label className="wide">Address<input value={draft.address1} onChange={event=>field("address1",event.target.value)}/></label><label className="wide">Address line 2<input value={draft.address2} onChange={event=>field("address2",event.target.value)}/></label><label>City<input value={draft.city} onChange={event=>field("city",event.target.value)}/></label><label>State / Region<input value={draft.region} onChange={event=>field("region",event.target.value)}/></label><label>ZIP / Postal code<input value={draft.postalCode} onChange={event=>field("postalCode",event.target.value)}/></label><label>Country<input value={draft.country} onChange={event=>field("country",event.target.value)}/></label><div className="contactDirectoryEditActions"><button type="button" className="button secondary" onClick={()=>setEditing("")} disabled={saving}>Cancel</button><button type="submit" className="button" disabled={saving||!draft.company.trim()}>{saving?"Saving…":"Save Changes"}</button></div></form>;
 return <main className="contactDirectoryPage"><header><div><p className="eyebrow">DEAL WORKBOOK</p><h1>Vendors &amp; Customers</h1><p>Look up and update complete company, contact and address information in one place.</p></div><a href="/employee">← Deal Workbook</a></header><section className="contactDirectoryStats"><article><strong>{vendors.length}</strong><span>Vendors</span></article><article><strong>{customers.length}</strong><span>Customers</span></article><article><strong>{vendors.filter(v=>v.created_by_name).length}</strong><span>Assigned vendors</span></article></section><section className="contactDirectoryTools"><div className="contactDirectoryTabs"><button className={scope==="vendors"?"active":""} onClick={()=>{setScope("vendors");setOpen("");setEditing("")}}>Vendors <span>{vendors.length}</span></button><button className={scope==="customers"?"active":""} onClick={()=>{setScope("customers");setOpen("");setEditing("")}}>Customers <span>{customers.length}</span></button></div><label>Search directory<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Company, contact, email, phone, city or employee"/></label></section>
 {message&&<p className="contactDirectoryMessage">{message}</p>}{loading?<div className="contactDirectoryEmpty">Loading vendors and customers…</div>:<section className="contactDirectoryList"><div className="contactDirectoryHeading"><h2>{scope==="vendors"?"Vendor database":"Customer database"}</h2><span>{items.length} shown</span></div>
 {scope==="vendors"?visibleVendors.map(v=>{const key=`v-${v.id}`;return <article key={v.id} className={open===key?"open":""}><button className="contactDirectorySummary" onClick={()=>{setOpen(open===key?"":key);setEditing("")}} aria-expanded={open===key}><div><span>VENDOR</span><h3>{v.company_name}</h3><p>{v.contact_name||"No contact name"} · {[v.city,v.region].filter(Boolean).join(", ")}</p></div><div><b>{v.created_by_name||"Unassigned"}</b><small>Assigned employee</small></div><strong>{open===key?"Close":"View details"}</strong></button>{open===key&&<div className="contactDirectoryDetails">{editing===key?editor(()=>void saveVendor(v)):<><dl><div><dt>Contact</dt><dd>{v.contact_name||"—"}</dd></div><div><dt>Email</dt><dd>{v.email?<a href={`mailto:${v.email.split(",")[0].trim()}`}>{v.email}</a>:"—"}</dd></div><div><dt>Phone</dt><dd>{v.phone?<a href={`tel:${v.phone}`}>{v.phone}</a>:"—"}</dd></div><div><dt>Address</dt><dd>{address(v)||"—"}</dd></div><div><dt>Assigned to</dt><dd>{v.created_by_name}<small>{v.created_by_email}</small></dd></div><div><dt>Last updated</dt><dd>{date(v.updated_at)}</dd></div></dl><div className="contactDirectoryActions"><button className="button" type="button" onClick={()=>editVendor(v)}>Edit Vendor</button></div></>}</div>}</article>}):visibleCustomers.map(c=>{const key=`c-${c.id}`;return <article key={c.id} className={open===key?"open":""}><button className="contactDirectorySummary" onClick={()=>{setOpen(open===key?"":key);setEditing("")}} aria-expanded={open===key}><div><span>CUSTOMER</span><h3>{c.company||c.email||"Unnamed customer"}</h3><p>{c.contact_name||"No contact name"} · {[c.city,c.region].filter(Boolean).join(", ")||"No city entered"}</p></div><div><b>{c.assigned_employee_name||`${c.bid_count} ${c.bid_count===1?"bid":"bids"}`}</b><small>{c.assigned_employee_name?"Assigned employee":c.has_account?"Customer account":"Bid contact"}</small></div><strong>{open===key?"Close":"View details"}</strong></button>{open===key&&<div className="contactDirectoryDetails">{editing===key?editor(()=>void saveCustomer(c)):<><dl><div><dt>Contact</dt><dd>{c.contact_name||"—"}</dd></div><div><dt>Email</dt><dd>{c.email?<a href={`mailto:${c.email}`}>{c.email}</a>:"—"}</dd></div><div><dt>Phone</dt><dd>{c.phone?<a href={`tel:${c.phone}`}>{c.phone}</a>:"—"}</dd></div><div><dt>Address</dt><dd>{address(c)||"—"}</dd></div><div><dt>Assigned to</dt><dd>{c.assigned_employee_name||"Unassigned"}{c.assigned_employee_email&&<small>{c.assigned_employee_email}</small>}</dd></div><div><dt>Customer record</dt><dd>{c.has_account?"Activated customer account":c.assigned_employee_name?"Imported customer":"Created from a submitted bid"}</dd></div><div><dt>Last bid</dt><dd>{date(c.last_bid_at)}</dd></div></dl><div className="contactDirectoryActions"><button className="button" type="button" onClick={()=>editCustomer(c)}>Edit Customer</button></div></>}</div>}</article>})}
 {!items.length&&<div className="contactDirectoryEmpty">No {scope} match that search.</div>}</section>}</main>;
}
