import {env} from "cloudflare:workers";
import {employeeUser} from "../../../lib/employee-server";

const allowed=new Set(["pdf","xls","xlsx","csv","doc","docx","txt","rtf","jpg","jpeg","png","webp","zip"]),types=new Set(["vendor","customer","prospect"]),maxFiles=25,maxSize=15*1024*1024;
const safe=(value:string)=>value.replace(/[^a-zA-Z0-9._ -]/g,"_").replace(/\s+/g," ").slice(-120)||"document";
const row=(value:any)=>({id:String(value.id),filename:String(value.filename),content_type:String(value.content_type),size_bytes:Number(value.size_bytes),uploaded_by:String(value.uploaded_by),created_at:String(value.created_at)});

export async function GET(request:Request){
 const employee=await employeeUser(request);if(!employee)return Response.json({error:"Employee access required."},{status:401});
 const url=new URL(request.url),id=url.searchParams.get("id")||"";
 if(id){const file=await env.DB.prepare("SELECT object_key,filename,content_type FROM business_record_attachments WHERE id=?").bind(id).first<{object_key:string;filename:string;content_type:string}>();if(!file)return Response.json({error:"Document not found."},{status:404});const object=await env.BUCKET.get(file.object_key);if(!object)return Response.json({error:"Document not found."},{status:404});return new Response(object.body,{headers:{"content-type":file.content_type||"application/octet-stream","content-disposition":`attachment; filename*=UTF-8''${encodeURIComponent(file.filename)}`,"x-content-type-options":"nosniff","cache-control":"private, no-store"}})}
 const recordType=url.searchParams.get("recordType")||"",recordId=url.searchParams.get("recordId")||"";if(!types.has(recordType)||!recordId)return Response.json({error:"A valid business record is required."},{status:400});const result=await env.DB.prepare("SELECT id,filename,content_type,size_bytes,uploaded_by,created_at FROM business_record_attachments WHERE record_type=? AND record_id=? ORDER BY created_at ASC").bind(recordType,recordId).all();return Response.json({attachments:(result.results||[]).map(row)},{headers:{"cache-control":"private, no-store"}})
}

export async function POST(request:Request){
 const employee=await employeeUser(request);if(!employee)return Response.json({error:"Employee access required."},{status:401});
 try{const form=await request.formData(),recordType=String(form.get("recordType")||""),recordId=String(form.get("recordId")||"").trim(),recordName=String(form.get("recordName")||"").trim().slice(0,200),documents=form.getAll("documents").filter((value):value is File=>value instanceof File&&value.size>0);if(!types.has(recordType)||!recordId||!documents.length)return Response.json({error:"Choose at least one document."},{status:400});const count=await env.DB.prepare("SELECT COUNT(*) total FROM business_record_attachments WHERE record_type=? AND record_id=?").bind(recordType,recordId).first<{total:number}>(),remaining=Math.max(0,maxFiles-Number(count?.total||0));if(!remaining)return Response.json({error:`This record already has the maximum of ${maxFiles} documents.`},{status:400});const saved=[];for(const file of documents.slice(0,Math.min(10,remaining))){const filename=safe(file.name),extension=filename.split(".").pop()?.toLowerCase()||"";if(!allowed.has(extension)||file.size>maxSize)continue;const id=crypto.randomUUID(),objectKey=`business-records/${recordType}/${encodeURIComponent(recordId)}/${id}-${filename}`,contentType=file.type||"application/octet-stream",createdAt=new Date().toISOString();await env.BUCKET.put(objectKey,await file.arrayBuffer(),{httpMetadata:{contentType},customMetadata:{recordType,recordId,recordName,filename,uploadedBy:employee.email}});await env.DB.prepare("INSERT INTO business_record_attachments (id,record_type,record_id,record_name,object_key,filename,content_type,size_bytes,uploaded_by,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)").bind(id,recordType,recordId,recordName,objectKey,filename,contentType,file.size,employee.email,createdAt).run();saved.push({id,filename,content_type:contentType,size_bytes:file.size,uploaded_by:employee.email,created_at:createdAt})}if(!saved.length)return Response.json({error:"Use PDF, Excel, Word, CSV, text, image, or ZIP files under 15MB each."},{status:400});return Response.json({attachments:saved})}catch{return Response.json({error:"Documents could not be uploaded."},{status:500})}
}

export async function DELETE(request:Request){
 const employee=await employeeUser(request);if(!employee)return Response.json({error:"Employee access required."},{status:401});
 const id=String((await request.json().catch(()=>({})) as {id?:string}).id||"");if(!id)return Response.json({error:"Document not found."},{status:400});const file=await env.DB.prepare("SELECT object_key,uploaded_by FROM business_record_attachments WHERE id=?").bind(id).first<{object_key:string;uploaded_by:string}>();if(!file)return Response.json({error:"Document not found."},{status:404});if(employee.role!=="administrator"&&file.uploaded_by.toLowerCase()!==employee.email.toLowerCase())return Response.json({error:"Only the uploader or an administrator can delete this document."},{status:403});await env.BUCKET.delete(file.object_key);await env.DB.prepare("DELETE FROM business_record_attachments WHERE id=?").bind(id).run();return Response.json({ok:true})
}
