import {env} from "cloudflare:workers";
import {employeeUser} from "../../../../lib/employee-server";
import {pddSupabaseKey,pddSupabaseUrl} from "../../../../lib/pdd-auth";
export async function GET(request:Request){const employee=await employeeUser(request);if(!employee)return Response.json({error:"Employee access required."},{status:401});await env.DB.prepare(`CREATE TABLE IF NOT EXISTS internal_bid_agents (bid_id TEXT PRIMARY KEY,employee_user_id TEXT NOT NULL,employee_name TEXT NOT NULL,employee_email TEXT NOT NULL,customer_key TEXT NOT NULL DEFAULT '',uploaded_file_name TEXT NOT NULL DEFAULT '',entered_at TEXT NOT NULL)`).run();const url=new URL(request.url);const number=url.searchParams.get("bid");if(number){const bid=await env.DB.prepare("SELECT b.internal_bid_number,b.deal_number,b.company,b.contact_name,b.email,b.phone,b.customer_notes,b.line_items_json,b.line_count,b.total_quantity,b.total_bid,b.status,b.submitted_at,COALESCE(c.address1,'') address1,COALESCE(c.address2,'') address2,COALESCE(c.city,'') city,COALESCE(c.region,'') region,COALESCE(c.postal_code,'') postal_code,COALESCE(c.country,'') country,COALESCE(a.employee_name,'') entered_by_name,COALESCE(a.employee_email,'') entered_by_email,COALESCE(a.uploaded_file_name,'') uploaded_file_name,COALESCE((SELECT owner.assigned_employee_name FROM imported_customers owner WHERE owner.id=COALESCE(a.customer_key,'') OR (owner.email<>'' AND lower(owner.email)=lower(b.email)) ORDER BY CASE WHEN owner.id=COALESCE(a.customer_key,'') THEN 0 ELSE 1 END LIMIT 1),'') sales_owner_name,COALESCE((SELECT owner.assigned_employee_email FROM imported_customers owner WHERE owner.id=COALESCE(a.customer_key,'') OR (owner.email<>'' AND lower(owner.email)=lower(b.email)) ORDER BY CASE WHEN owner.id=COALESCE(a.customer_key,'') THEN 0 ELSE 1 END LIMIT 1),'') sales_owner_email FROM internal_bids b LEFT JOIN internal_bid_customers c ON c.bid_id=b.id LEFT JOIN internal_bid_agents a ON a.bid_id=b.id WHERE b.internal_bid_number=? LIMIT 1").bind(number).first();if(!bid)return Response.json({error:"Bid not found."},{status:404});return Response.json({bid:{...bid,line_items:JSON.parse(String(bid.line_items_json||"[]")),line_items_json:undefined}})}const result=await env.DB.prepare("SELECT b.internal_bid_number,b.deal_number,b.company,b.contact_name,b.line_count,b.total_quantity,b.total_bid,b.status,b.submitted_at,COALESCE(a.employee_name,'') entered_by_name,COALESCE(a.employee_email,'') entered_by_email,COALESCE(a.uploaded_file_name,'') uploaded_file_name FROM internal_bids b LEFT JOIN internal_bid_agents a ON a.bid_id=b.id ORDER BY b.submitted_at DESC LIMIT 100").all();return Response.json({bids:result.results||[]})}
export async function PATCH(request:Request){const employee=await employeeUser(request);if(!employee)return Response.json({error:"Employee access required."},{status:401});const body=await request.json() as {bidNumber?:string;status?:string};if(!body.bidNumber||!["submitted","won","lost"].includes(body.status||""))return Response.json({error:"Choose a valid bid status."},{status:400});const bid=await env.DB.prepare("SELECT deal_number FROM internal_bids WHERE internal_bid_number=? LIMIT 1").bind(body.bidNumber).first<{deal_number:string}>();if(!bid)return Response.json({error:"Bid not found."},{status:404});const result=await env.DB.prepare("UPDATE internal_bids SET status=? WHERE internal_bid_number=?").bind(body.status,body.bidNumber).run();if(!result.meta.changes)return Response.json({error:"Bid not found."},{status:404});if(body.status==="won"){const token=(request.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");await fetch(`${pddSupabaseUrl}/rest/v1/pdd_public_deals?deal_number=eq.${encodeURIComponent(bid.deal_number)}`,{method:"PATCH",headers:{apikey:pddSupabaseKey,Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({status:"pending",published:false,updated_at:new Date().toISOString()})})}return Response.json({ok:true})}

export async function DELETE(request:Request){
 const employee=await employeeUser(request);if(!employee)return Response.json({error:"Employee access required."},{status:401});
 if(employee.role!=="administrator")return Response.json({error:"Administrator access required."},{status:403});
 const bidNumber=new URL(request.url).searchParams.get("bid");if(!bidNumber)return Response.json({error:"Awarded bid number is required."},{status:400});
 const awarded=await env.DB.prepare("SELECT id,internal_bid_number FROM internal_bids WHERE internal_bid_number=? AND status='won' LIMIT 1").bind(bidNumber).first<{id:string;internal_bid_number:string}>();
 if(!awarded)return Response.json({error:"Awarded bid not found."},{status:404});
 await env.DB.batch([
  env.DB.prepare("DELETE FROM internal_bid_customers WHERE bid_id=?").bind(awarded.id),
  env.DB.prepare("DELETE FROM internal_bid_agents WHERE bid_id=?").bind(awarded.id),
  env.DB.prepare("DELETE FROM bid_notification_log WHERE bid_number=?").bind(awarded.internal_bid_number),
  env.DB.prepare("DELETE FROM internal_bids WHERE id=? AND status='won'").bind(awarded.id)
 ]);
 return Response.json({ok:true,deleted:1,bidNumber:awarded.internal_bid_number});
}
