"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {Shell} from "@/components/SiteShell";
import "./pdd.css";

type Deal={id:string;deal_number:string;direction:"buying"|"selling";category:string;title:string;description:string;quantity:number;manufacturer:string;part_number:string;closes_at:string;location:string};
const sampleDeals:Deal[]=[
 {id:"b081026-01-ddr5-memory",deal_number:"B081026-01",direction:"selling",category:"DDR5 Server Memory",title:"435-Piece DDR5 Server Memory Offering",description:"Twenty-eight line items of 32GB, 64GB, 96GB and 128GB server memory from Samsung, Hynix, Micron and JBR. Seller prices are not published; qualified buyers may submit confidential line-item offers.",quantity:435,manufacturer:"Samsung / Hynix / Micron / JBR",part_number:"28 qualified memory line items",closes_at:"",location:"California, USA"},
 {id:"b082126-01-itamg-server-lot",deal_number:"B082126-01",direction:"selling",category:"Enterprise Servers",title:"181-Unit Mixed Enterprise Server Lot",description:"Mixed enterprise server lot including Dell, Lenovo, IBM, HP, HPE, Buffalo and Intel systems. Detailed configurations are available in the customer bid spreadsheet.",quantity:181,manufacturer:"Dell / Lenovo / IBM / HP / HPE / Buffalo / Intel",part_number:"Mixed enterprise server models",closes_at:"2026-08-28T17:00:00-07:00",location:"California, USA"},
 {id:"bd79dd7b-8aa8-4e21-9699-6b04b569a501",deal_number:"PDD-BETA-001",direction:"selling",category:"DDR5 Server Memory",title:"108-Piece Samsung & Micron DDR5 RDIMM Lot",description:"Five-lot enterprise memory offering with 64GB and 16GB modules at DDR5-4800, 5600 and 7200 speed grades.",quantity:108,manufacturer:"Samsung / Micron",part_number:"Five qualified lots",closes_at:"2026-09-04T17:00:00-07:00",location:"California, USA"}
];
function formatClose(value:string){return value?new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit",timeZoneName:"short"}).format(new Date(value)):"Open for offers"}
function detailHref(dealNumber:string){return dealNumber==="B082126-01"?"/public-deal-desk/b082126-01":dealNumber==="B081026-01"?"/public-deal-desk/b081026-01":""}
function excelHref(dealNumber:string){return dealNumber==="B081026-01"?"/deals/B081026-01-Public-Inventory.xlsx":dealNumber==="B082126-01"?"/deals/B082126-01-Public-Inventory.xlsx":dealNumber==="PDD-BETA-001"?"/deals/PDD-BETA-001-Deal-Summary.xlsx":""}

export default function PublicDealDesk(){
 const [direction,setDirection]=useState("all");
 const [query,setQuery]=useState("");
 const [selected,setSelected]=useState<Deal|null>(null);
 const [notice,setNotice]=useState("");
 const [allDeals,setAllDeals]=useState<Deal[]>(sampleDeals);
 const [live,setLive]=useState(false);
 const [submitting,setSubmitting]=useState(false);
 useEffect(()=>{let active=true;fetch("/api/deals").then(r=>r.ok?r.json():Promise.reject()).then(data=>{if(active&&Array.isArray(data.deals)&&data.deals.length){setAllDeals([...sampleDeals,...data.deals.filter((deal:Deal)=>!sampleDeals.some(sample=>sample.deal_number===deal.deal_number))]);setLive(true)}}).catch(()=>{});return()=>{active=false}},[]);
 const deals=useMemo(()=>allDeals.filter(deal=>{const haystack=`${deal.deal_number} ${deal.category} ${deal.title} ${deal.description} ${deal.manufacturer} ${deal.part_number}`.toLowerCase();return(direction==="all"||deal.direction===direction)&&haystack.includes(query.toLowerCase())}),[allDeals,direction,query]);
 async function submitBid(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;setSubmitting(true);setNotice("");const form=event.currentTarget;const body=new FormData(form);body.set("deal_id",selected.id);try{const response=await fetch("/api/bids",{method:"POST",body});const data=await response.json();if(!response.ok)throw new Error(data.error||"Your offer could not be submitted.");setNotice(`Offer ${data.bid_number} was received confidentially. Mac2MacOnline will contact you if it is shortlisted or awarded.`);form.reset()}catch(error){setNotice(error instanceof Error?error.message:"Your offer could not be submitted. Please try again.")}finally{setSubmitting(false)}}
 return <Shell><main className="pdd">
  <section className="pddHero"><div><p className="pddEyebrow">MAC2MACONLINE PUBLIC DEAL DESK</p><h1>Wholesale technology deals, <span>open to qualified partners.</span></h1><p className="pddLead">Review active buying requests and available inventory, submit your offer securely and complete awarded purchases through Mac2MacOnline.</p><div className="pddActions"><a className="pddPrimary" href="#pdd-deals">View Open Deals</a><a className="pddSecondary" href="#pdd-process">How Awards Work</a></div><div className="pddTrust"><span>R2v3 Certified</span><span>ISO 9001</span><span>ISO 14001</span><span>ISO 45001</span></div></div><aside className="pddProcess"><p className="pddEyebrow">FROM BID TO ORDER</p><ol><li><b>Find a deal</b><span>Search buying requests and available lots.</span></li><li><b>Submit your offer</b><span>Include price, quantity, condition and timing.</span></li><li><b>Receive an award</b><span>Winning bidders receive private purchase instructions.</span></li><li><b>Complete securely</b><span>Confirm shipping and payment with Mac2MacOnline.</span></li></ol></aside></section>
  <section className="pddDeals" id="pdd-deals"><div className="pddHeading"><div><p className="pddEyebrow">CURRENT OPPORTUNITIES</p><h2>Public Deal Desk</h2><p>All deadlines are shown in Pacific Time unless the deal states otherwise.</p></div><div className="pddLive"><i/>{live?"Live deal feed":"Beta deal data"}</div></div><div className="pddControls"><div className="pddSegments"><button className={direction==="all"?"active":""} onClick={()=>setDirection("all")}>All deals</button><button className={direction==="selling"?"active":""} onClick={()=>setDirection("selling")}>Inventory for sale</button><button className={direction==="buying"?"active":""} onClick={()=>setDirection("buying")}>Wanted inventory</button></div><label className="pddSearch"><span>Search</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Part number, category or keyword"/></label></div><div className="pddGrid">{deals.map(deal=>{const href=detailHref(deal.deal_number);const download=excelHref(deal.deal_number);return <article className="pddCard" key={deal.id}><div className="pddMeta"><span className={deal.direction}>{deal.direction==="selling"?"For Sale":"Want to Buy"}</span><b>{deal.deal_number}</b></div><p className="pddCategory">{deal.category}</p><h3>{deal.title}</h3><p className="pddDescription">{deal.description}</p><dl><div><dt>Manufacturer</dt><dd>{deal.manufacturer}</dd></div><div><dt>Part number</dt><dd>{deal.part_number}</dd></div><div><dt>Quantity</dt><dd>{deal.quantity.toLocaleString()}</dd></div><div><dt>Location</dt><dd>{deal.location}</dd></div></dl><div className="pddDeadline"><span>{deal.closes_at?"Offers close":"Status"}</span><strong>{formatClose(deal.closes_at)}</strong></div><div className="pddCardActions">{href?<a className="pddCardButton" href={href}>Enter Line-Item Offer</a>:<button className="pddCardButton" onClick={()=>{setSelected(deal);setNotice("")}}>{deal.direction==="selling"?"Submit an offer":"Offer this inventory"}</button>}{download&&<a className="pddDownload" href={download} download>Download Excel</a>}</div></article>})}</div>{!deals.length&&<div className="pddEmpty"><h3>No matching deals</h3><p>Try a broader search or view all deal types.</p></div>}</section>
  <section className="pddHow" id="pdd-process"><div><p className="pddEyebrow">AWARD PROCESS</p><h2>Private pricing. Clear awards. Secure fulfillment.</h2><p>Offers remain private. Mac2MacOnline validates each bidder, selects an offer and sends the awarded party the exact quantities, pricing, shipping and payment terms.</p></div><div className="pddFlow"><article><b>01</b><h3>Review</h3><p>We validate the bidder, offer and delivery requirements.</p></article><article><b>02</b><h3>Award</h3><p>The winning offer is accepted for a limited confirmation period.</p></article><article><b>03</b><h3>Order</h3><p>Final order, shipping and payment instructions are issued.</p></article><article><b>04</b><h3>Close</h3><p>The completed opportunity is archived in the Deal Desk.</p></article></div></section>
  {selected&&<div className="pddBackdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><section className="pddModal" role="dialog" aria-modal="true" aria-labelledby="pdd-bid-title"><button className="pddClose" aria-label="Close" onClick={()=>setSelected(null)}>×</button><p className="pddEyebrow">{selected.deal_number}</p><h2 id="pdd-bid-title">{selected.direction==="selling"?"Submit an offer":"Offer your inventory"}</h2><p>{selected.title}</p><form onSubmit={submitBid}><div className="pddFormGrid"><label>Company<input required name="company"/></label><label>Contact name<input required name="contact"/></label><label>Email<input required type="email" name="email"/></label><label>Phone<input required name="phone" inputMode="tel" placeholder="+1 530-555-1234"/></label><label>Quantity<input required type="number" min="1" name="quantity"/></label><label>Unit price<input required type="number" min="0" step="0.01" name="unit_price"/></label></div><label>Condition, timing and notes<textarea required name="notes" rows={4}/></label><label>Supporting file<input type="file" name="attachment" accept=".pdf,.xls,.xlsx,.csv,.jpg,.jpeg,.png"/><small>Spreadsheet, PDF or clear product-label photographs, up to 10 MB.</small></label><button className="pddPrimary pddSubmit" type="submit" disabled={submitting}>{submitting?"Submitting securely…":"Submit confidential offer"}</button>{notice&&<p className="pddNotice">{notice}</p>}</form></section></div>}
 </main></Shell>
}
