import {PageHero,Shell} from "@/components/SiteShell";
import InquiryForm from "@/components/InquiryForm";

const steps=[
  ["Evaluate","We review the equipment, condition, documentation, market demand and likely selling range.","/assets/m2m-consign-evaluate-v4.png","Professional evaluating warehouse equipment with an android following closely behind"],
  ["Agree","We define the term, target price, commissions, expenses, custody and approval requirements in writing.","/assets/m2m-consign-agree-v2.png","Man and blonde woman reviewing a legal-size consignment contract together at a desk"],
  ["Market","We prepare listings, contact qualified buyers and promote the inventory through our established channels.","/assets/m2m-consign-market.png","Computer and enterprise equipment connected to buyers throughout the global technology market"],
  ["Close","We coordinate buyer communication, payment, logistics and provide a clear settlement statement after the sale.","/assets/m2m-consign-close-v2.webp","Man and woman completing the agreement while workers and androids load technology into a truck"],
];

export default function Page(){return <Shell><PageHero eyebrow="A higher-upside alternative" title="Mac2MacOnline Consignment" intro="For specialized, high-value or slower-moving equipment, consignment can provide greater market exposure and potentially stronger recovery than an immediate wholesale sale."/><section className="steps wrap"><div className="section-head"><div><span className="eyebrow">The program</span><h2>We do the market work. You keep visibility.</h2></div></div><div className="step-grid consignment-step-grid">{steps.map(([title,description,image,alt])=><article key={title}><img src={image} alt={alt}/><div><h3>{title}</h3><p>{description}</p></div></article>)}</div></section><section className="program-details"><div className="wrap two-col"><div><h2>Best suited for</h2><ul><li>Enterprise servers, storage and networking</li><li>AI systems, GPUs and high-value components</li><li>Large uniform lots with documented condition</li><li>Specialized equipment with a defined buyer market</li><li>Inventory where the owner can allow time for a better outcome</li></ul></div><div><h2>Program safeguards</h2><ul><li>Written consignment agreement before marketing begins</li><li>Agreed reserve price and approval rules</li><li>Inventory identification and condition records</li><li>Defined commission, expenses and payment timing</li><li>Regular status reporting and transparent settlement</li></ul></div></div></section><section className="form-section wrap"><div className="form-copy"><h2>Request a consignment review.</h2><p>Submitting a list does not obligate either party. After review, we will recommend direct purchase, consignment or another practical route.</p></div><InquiryForm type="consignment"/></section></Shell>}
