"use client";
import {FormEvent,useEffect,useState} from "react";
import {Shell} from "../../../components/SiteShell";
import {clearPddSession,currentPddSession,type PddSession} from "../../../lib/pdd-auth";

type Result={report:{id:string;digitalId:string;reportDate:string;softwareVersion:string};erasure:{totalDisks:string;successfulDisks:string;failedDisks:string;method:string;verification:string;writePasses:string};device:{manufacturer:string;model:string;sku:string;systemSerial:string;chassisSerial:string;boardSerial:string;uuid:string;memory:string;autopilotStatus:string};hardwareTests:{name:string;status:string}[];disks:{diskNumber:string;model:string;serial:string;size:string;mediaType:string;smartStatus:string;badSectors:string;method:string;status:string;started:string;completed:string;duration:string}[];processors:{manufacturer:string;model:string;cores:string;speed:string}[];memoryModules:{manufacturer:string;sizeBytes:string;speed:string;formFactor:string;serial:string}[]};
const label=(value:string)=>value||"—";
const bytes=(value:string)=>{const size=Number(value);return Number.isFinite(size)&&size>0?`${(size/1073741824).toFixed(0)} GB`:label(value)};

export default function BitRaserConnectionPage(){
 const [session,setSession]=useState<PddSession|null>(null),[loading,setLoading]=useState(true),[configured,setConfigured]=useState(false),[busy,setBusy]=useState(false),[value,setValue]=useState(""),[error,setError]=useState(""),[result,setResult]=useState<Result|null>(null);
 useEffect(()=>{void(async()=>{const active=await currentPddSession();if(!active){window.location.replace("/employee-login?return_to=/employee/bitraser");return}setSession(active);const response=await fetch("/api/admin/bitraser",{headers:{Authorization:`Bearer ${active.access_token}`},cache:"no-store"});if(response.status===401){clearPddSession();window.location.replace("/employee-login?return_to=/employee/bitraser");return}const data=await response.json().catch(()=>({})) as {configured?:boolean};setConfigured(Boolean(data.configured));setLoading(false)})()},[]);
 async function test(event:FormEvent){event.preventDefault();if(!session)return;setBusy(true);setError("");setResult(null);const response=await fetch("/api/admin/bitraser",{method:"POST",headers:{Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({value})}),data=await response.json().catch(()=>({})) as {report?:Result;error?:string};if(!response.ok)setError(data.error||"The BitRaser connection could not be tested.");else setResult(data.report||null);setBusy(false)}
 if(loading)return <Shell><main className="bitraserPage"><p>Loading BitRaser connection…</p></main></Shell>;
 return <Shell><main className="bitraserPage"><header><div><p className="eyebrow">DASHBOARD · R2 PROCESSING</p><h1>BitRaser connection</h1><p>Verify the secure connection and retrieve one Drive Eraser report.</p></div><a className="button secondary" href="/employee">Back to Dashboard</a></header>
 <section className="bitraserConnectionCard"><div className="bitraserConnectionHeading"><div><span>SERVER CONNECTION</span><h2>BitRaser Cloud API</h2></div><b className={configured?"connected":"notConnected"}>{configured?"Credentials configured":"Not configured"}</b></div><p>The saved username and password remain protected on the server and are never sent to this page.</p>
 <form onSubmit={test}><label>System serial number<input value={value} onChange={event=>setValue(event.target.value)} placeholder="Example: MP2Z4QL7" required/></label><button className="button" disabled={!configured||busy}>{busy?"Connecting…":"Test BitRaser Connection"}</button></form></section>
 {error&&<p className="bitraserMessage error" role="alert">{error}</p>}
 {result&&<><section className="bitraserResultHeader"><div><span>CONNECTION SUCCESSFUL</span><h2>{label(result.device.manufacturer)} {label(result.device.model)}</h2><p>System serial <b>{label(result.device.systemSerial)}</b> · Report <b>{label(result.report.id)}</b></p></div><b>{label(result.erasure.method)}</b></section>
 <section className="bitraserSummaryGrid"><article><small>ERASURE STATUS</small><strong>{result.erasure.successfulDisks} successful</strong><span>{result.erasure.failedDisks} failed · {label(result.erasure.verification)}</span></article><article><small>MEMORY</small><strong>{label(result.device.memory)}</strong><span>{result.memoryModules.map(item=>`${item.manufacturer} ${bytes(item.sizeBytes)} ${item.speed}`).join(" · ")||"No module details"}</span></article><article><small>PROCESSOR</small><strong>{result.processors[0]?.model||"—"}</strong><span>{result.processors[0]?.manufacturer||"No processor details"}</span></article></section>
 <section className="bitraserDetailCard"><h2>Erased drives</h2><div className="bitraserTable"><table><thead><tr><th>Disk</th><th>Model</th><th>Serial</th><th>Size / Type</th><th>SMART</th><th>Result</th><th>Completed</th></tr></thead><tbody>{result.disks.map((disk,index)=><tr key={`${disk.serial}-${index}`}><td>{disk.diskNumber}</td><td>{label(disk.model)}</td><td>{label(disk.serial)}</td><td>{label(disk.size)} · {label(disk.mediaType)}</td><td>{label(disk.smartStatus)}</td><td>{label(disk.status)}</td><td>{label(disk.completed)}</td></tr>)}</tbody></table></div></section>
 <section className="bitraserDetailCard"><h2>Hardware tests</h2><div className="bitraserTestGrid">{result.hardwareTests.map(test=><div key={test.name}><span>{test.name}</span><b>{test.status}</b></div>)}</div></section></>}
 </main></Shell>
}
